packages/chart/src/components/BarChart.tsx
packages/chart/src/components/LinearChart.tsx

- When a lollipop chart is chosen shift bars to the top to create space for labels below bar
- Readjusts label position

Lollipop > label adjustments for below bar

---

packages/core/styles/v2/components/editor.scss

- We moved the reset out to avoid style bleeds, but it looks like other issues moved into the editor. Adding this back temporarily just for the editor.

[wcmsrd-14492b] Add Reset in Waffle Chart Editor

---

packages/waffle-chart/src/CdcWaffleChart.tsx
packages/waffle-chart/src/components/EditorPanel.js
packages/waffle-chart/src/scss/waffle-chart.scss

- No text centering on vertical waffle charts
- Move font size nesting @at-root out, nesting not working
- Add a quickfix for reversing checkbox label positions

[wcmsrd-14492b] Update Waffle Editor Styles for release

---

packages/chart/src/components/BarChart.tsx
packages/chart/src/components/EditorPanel.js
packages/chart/src/components/LinearChart.tsx
packages/chart/src/data/initial-state.js

Divided chart height into two parts. Vertical charts can be manually updated by user.Horizontal charts is gets updated dynamically based on bar height, bar space etc..
Fixed: When switching from horizontal charts to vertical, the vertical chart used to inherit the size(height) from horizontal.
now it doesn't inherit. each chart has own height.

[DEV-2128] Divide config height in a vertical & horizontal 

---

packages/chart/src/components/BarChart.tsx
packages/chart/src/components/EditorPanel.js
packages/chart/src/data/initial-state.js

Added "Bar Space" feature which is on "Visual panel" to bars when labels are below bar.Previously it was only when labels are outside of bar.Bar space adds margin to each bar to increase or decrease space between bars.Works only in Horizontal (regular,stacked,lollipop) bars.

[DEV-2759a] Add barSpace while labels are below bar

---

packages/chart/package.json
packages/core/package.json
packages/dashboard/package.json
packages/map/package.json
yarn.lock

Update dependencies for non-beta `react-tooltip` release

Update tooltips to 5.8 release

---

packages/chart/index.html
packages/chart/src/components/EditorPanel.jsx

Robin and Bill asked to hide vertical option when it is Deviation bar. added use effect to force it to be horizontal when user switches to Deviation bar.
- [] CDC Internal Checks

[hide-vertical] Hide vertical option in Deviaton bar

---

packages/map/src/components/EditorPanel.jsx

Fixed minor  issue with expandDataTable state update code.
And yes tested it in standone, editor and dashboard.

[dev-3305-update-state-edit] Fixed map init-state expand issue

---

packages/chart/src/data/initial-state.js
packages/core/components/DataTable.jsx
packages/map/src/components/EditorPanel.jsx
packages/map/src/data/initial-state.js

Checkbox for Show Download CSV Link was not working right and also wrong initial state.  Fixed and tested on charts and maps (and in dashboard)
Also if Show Vertical was checked then it was always showing the Download CSV Link and ignoring the checkbox setting.
Both are fixed.
Set Show Vertical to be default TRUE so that the default for DataTable is now vertical.

[DEV-930-fix-iniitial-state] Fixed download link and initial state

---

packages/map/src/CdcMap.jsx
packages/map/src/components/EditorPanel.jsx

Restored code from March that allows you to click a checkbox and move the special classes in the map legend to last.
Got it working in editor and dashboards as well.

DRAFT: [DEV-784-special-classes-last] Added back special classes last in legend

---

packages/chart/src/components/Legend.jsx

Added logic to reverse the  legend labels while legend is in bottom position

[DEV-2183] Add legend bottom label reverse feature

---

packages/core/components/DataTable.jsx

The FullGeoName was showing up on too many maps that didn't make sense to be there.
Now limiting it to ONLY the us-county maps.

Bugfix/DEV 4612 suppress fullgeoname on all maps but us-county

---

packages/chart/src/components/EditorPanel.jsx

applied help text tooltip to all charts that have the "Region" dialog.

[DEV-5142] Add help tooltip text for Regions tab

---

packages/map/src/CdcMap.tsx

@adamdoe I'd appreciate if you looked at this one a little closer. 
Super niche issue: If you have an equalnumber style map, with special class, and filter, and certain sub-filter datasets don't have a value for the special class, the map blanks (I can send example config if needed). Looks like the issue is that in generateRuntimeLegend, the special classes are only added if a row in the data has that special class value, but the index when iterating for equalnumber accounts for a special class being added either way. I changed the index to go off of the last thing added to result, since somehting is added to result in the code block above. Not sure the ramifications of this, but it appears to fix the issue for me.

Fixes Map Breaking, Special Class Filter Issue

---

packages/editor/src/components/DataImport.jsx

You should be able to pull example files from the original ticket, save them under a private folder in editor/example/private as `wt=json` or `wt=csv`. You can then mock the request using something like `http://localhost:8080/example/private/wt=csv` Based on if the wt value is found we determine if the solr request is csv or json and get the data.

[DEV-6472-solr] initial work for solr requests

---

packages/core/styles/_global-variables.scss
packages/core/styles/base.scss

Proposal to set all TP4 vars to the global CSS context.
1) We almost never need write a hex code or define scss color variables.
2) These vars can be used inside our existing scss.
3) We will be able to use these vars in regular css files.
4) We can access these variables in Javascript:

Global CSS Vars

---

packages/waffle-chart/src/CdcWaffleChart.tsx

* decision made to skip over chart elements
* stop screen readers from reading chart elements because alternative formats are available

[DEV-7443] Accessibility > Remove waffle chart markup

---

yarn.lock

This upgrades the packages below to remove the error we've been seeing across files:
_Parsing error: DeprecationError: 'originalKeywordKind' has been deprecated since v5.0.0 and can no longer be used. Use 'identifierToKeywordKind(identifier)_
With this in place we should be able to stop using the `-n` flag on commits for better formatting (prettier) and provide objective eslint rules that should pass on files.
**Updates**
- eslint
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser

[eslint-errors] fix eslint errors

---

packages/dashboard/index.html
packages/dashboard/src/CdcDashboardComponent.tsx

This is related to issue #1080 
I would not mark this feature as complete or ready to be used, but this fixes the work that was done before. 
Currently if you don't have the table configuration "show": true this feature doesn't work. The bottom table that is rendered to the page is doing an additional filterData function which has a side effect. There may be a rerender that's happening too.

[DEV-6574] added side effect back that was allowing the feature to work

---

packages/dashboard/src/_stories/Dashboard.stories.tsx
packages/dashboard/src/components/Row.tsx

the multi-viz enhancement introduced a bug where changing the column layout would trigger an error if the first viz column was blank and you were shifting the layout to have less columns. 
let me know if we need a separate ticket for this, but for now I just tagged the original MultiViz ticket

Fix: [DEV-7047] error changing column layout

---

package.json
packages/core/components/DataTable/DataTableStandAlone.tsx
packages/core/components/DataTable/components/DataTableEditorPanel.tsx
packages/core/components/EditorWrapper/EditorWrapper.tsx
packages/core/components/EditorWrapper/editor-wrapper.style.css
packages/dashboard/src/CdcDashboardComponent.tsx

Storybook was not building the editor panel Accordion for the standalone table. After these changes it's fixed. I've already rebuilt storybook with this change so that we can have this for the demo tomorrow. No urgency in getting this out.
1) In storybook go to Pages/Dashboard/Pivot Filter.
2) in the config panel below toggle the isEditor to true
3) in dashboard click on the tools icon to bring up the table editor.
Expected: you should see the Columns and Data Table accordions on the left.

fixed storybook build

---

packages/dashboard/src/CdcDashboardComponent.tsx

1) Create a dashboard visualization.
2) add this data source: [nccd-cove-public-api.apps.ecpaas-dev.cdc.gov/od-public?$datakey=nyctaxi](https://nccd-cove-public-api.apps.ecpaas-dev.cdc.gov/od-public?$datakey=nyctaxi)
3) click the dashboard filter tab and create a new filter.
4) select URL filter.
5) set the filter url to: [nccd-cove-public-api.apps.ecpaas-dev.cdc.gov/od-public?$datakey=nyctaxi](https://nccd-cove-public-api.apps.ecpaas-dev.cdc.gov/od-public?$datakey=nyctaxi)&$select=dropoff_zip
6) set the key and value to: dropoff_zip
7) select the dashboard preview tab
Expected: the new dropdown should show a list of zip options.

Fix: [dev-8065] dashboard preview api filters

---

packages/core/components/DataTable/helpers/chartCellMatrix.tsx
packages/core/components/DataTable/helpers/getDataSeriesColumns.ts
packages/core/components/DataTable/helpers/getRowType.ts
packages/dashboard/src/CdcDashboardComponent.tsx
packages/dashboard/src/components/Header/FilterModal.tsx
packages/dashboard/src/helpers/getFilteredData.ts
packages/dashboard/src/helpers/getVizConfig.ts

Chart filter testing instructions are in the ticket https://websupport.cdc.gov/browse/DEV-8332
footnotes regression test is here: https://websupport.cdc.gov/browse/DEV-7696

FIX: [dev-8332][dev-7696] chart filter columns and footnotes

---

packages/chart/src/components/ScatterPlot/ScatterPlot.jsx

Updated tooltip for scatter plot and configured prefix/suffix/commas

[DEV-7977a] Update scatter plot tooltips

---

packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
packages/dashboard/src/helpers/changeFilterActive.ts

noticed a regression issue on https://wcms-wp-test.cdc.gov/wcms/wp-admin/post.php?action=edit&post=73617 where child filters weren't loading.

Fix: [dev-8409] dashboard filters change filter active

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
packages/chart/src/components/EditorPanel/useEditorPermissions.js
packages/chart/src/components/LinearChart.jsx
packages/chart/src/hooks/useTooltip.tsx

Testing Steps:
Select a Line Chart or an Area Chart (STACKED) and add multiple series.
Go to the VISUAL PANEL.
Click "Show hover for single data series."
After the checkbox is ON, hover over the lines in the Line Chart. You should only see the HOVERED series and its corresponding values.
Perform the same test for the stacked Area Chart.

[DEV-6410d] Add single series tooltip for Area and Line chart

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
packages/chart/src/types/ChartConfig.ts

Open the Editor component and select Bar.
In the General Panel, set the "Bar Style" to Lollipop.
Before adding any series, go to the Visual section, where you should see the options for "Lollipop Shape," "Lollipop Color Style," and "Lollipop Size" available.
Note: Ensure you do not press the "I am done" button. The options should remain available as long as the bar style is set to Lollipop.

[DEV-8756] Fix lollipop chart bug

---

packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx

Open a vertical (regular) bar chart and add only one series.
Go to the Legend panel and select any option from the "Color Code by Category" dropdown menu. Once selected, you should see the bar chart and legend display in different colors.
While maintaining a single series, switch to Lollipop charts and ensure it functions similarly.
Note : it works only with Single Series, non stacked Vertical and Horizontal bars/lollipops.

[DEV-8847] Fix bug Color Code by Category for vertical bars & lollipop

---

packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
packages/core/components/Filters.tsx
packages/core/components/MultiSelect/MultiSelect.tsx
packages/core/helpers/addValuesToFilters.ts
packages/core/helpers/coveUpdateWorker.ts
packages/core/helpers/tests/addValuesToFilters.test.ts
packages/core/helpers/ver/4.24.9.ts
packages/core/helpers/ver/tests/4.24.9.test.ts
packages/core/package.json
packages/core/types/VizFilter.ts

Scenario: User in the Editor has selected Dashboard Visualization. User has selected the "United States: State Sample Data" as the data source and navigated to the Configure tab.
1) Drag and drop a bar chart to the visualization panel. 
2) Select valid-data-map.csv as the data source. (vertical, not multiple series)
3) click the tools icon.
4) Select Rate for the Data Series.
5) Select Location for the Data Key.
6) Add Filters: 
Filter 1: Location
Filter 2: State
7) on Filter 2 select Location as the parent filter.
Expected: In the preview selecting different Location options in the first filter will change the filter options in the second State filter, as well as update the data visualization. 
- I have commented my code, particularly in …

Feature: [dev-8797] viz filter parent

---

packages/core/components/ui/Icon.tsx
packages/dashboard/src/components/MultiConfigTabs/MultiConfigTabs.tsx

1) Create a dashboard.
2) Add visualizations.
3) click "Make Multi-Visualization"
4) Add another tab.
5) Click the left arrow 
Expected: One tab should have visualizations and the other should not.
I also fixed the Icon so that we can get type hints for the icon types. I did this thinking I would use an icon on the tabs but ended up not using it. I can pull that change into another PR though if you'd like.

Fix [dev-8899] MultiDashboard: tab ordering UI glitches  & <Icon/> updated

---

packages/markup-include/src/CdcMarkupInclude.tsx
packages/markup-include/src/components/Variables.tsx

1. Create dashboard, add markup include
2. Bind numeric variable into markup include
3. Check "Add Commas to Number"
4. Ensure in preview that commas are being added to bound number

Adds Option for Commas in Markup Include Variables

---

packages/chart/src/components/LineChart/index.tsx

This PR simplifies line chart DOM in two ways:
* Moves the transparent `<rect>` used for the tooltip mouse listener outside the data loop. This renders it once instead of once for each data point in the chart.
* Changes a Group to a Fragment so the `<g>` isn't rendered for every data point when it's empty (which is for most charts, I'd assume, now that the rect was moved).
For a sample chart from the Respiratory Illness page, this reduces DOM nodes from about 800 to 200.
It also removes some variables that no longer appear to be used.
Load up some detailed line charts and see that they still work and they have fewer nodes.

Simplify LineChart DOM

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/core/components/Filters.tsx

1. Run chart package
2. Select line chart type
3. Enable dynamic series checkbox
4. Ensure that series type dropdown shows below once enabled
5. Ensure series type dropdown options work and control the series type
6. When series type is "Line" ensure another dropdown appears controlling curve type

Adds Support for Line Types to Dynamic Series

---

packages/chart/src/CdcChart.tsx
packages/core/components/EditorPanel/VizFilterEditor/NestedDropdownEditor.tsx
packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
packages/core/components/EditorPanel/VizFilterEditor/components/FilterOrder.tsx
packages/core/components/Filters.tsx
packages/core/components/NestedDropdown/NestedDropdown.tsx
packages/core/components/NestedDropdown/nesteddropdown.styles.css
packages/core/helpers/addValuesToFilters.ts
packages/core/helpers/filterVizData.ts
packages/core/helpers/tests/addValuesToFilters.test.ts
packages/core/helpers/tests/filterVizData.test.ts
packages/core/types/VizFilter.ts

Scenario:  In Editor, user has selected Bar Chart Visualization.
1. Import data. The following link is a csv file with data that works for this example. Download and upload file:  [nested_dropdown_sample.csv](https://cdc-my.sharepoint.com/:x:/g/personal/syf8_cdc_gov/EZnxIFiWxC9HunCh-smLsS0BkmaVLTtzwgEWUobEYILo_g?e=WSOdaf). Click Vertical, No to multiple series, and then Configure your Visualization button.
2. In Visualization, click on Data Series accordion, and select Data_Value in the Data Series dropdown.
3. Click on the Date/Category Axis accordion. And Select YearStart from the DATA KEY dropdown
4. Click the I'm Done button.
5. Click the Filters accordion and Add Filter
6. Choose Nested Dropdown from the FILTER STYLE dropdown
7. In the LABEL text box write "Stratification 1" …

Dev 8275 nested data driven dropdown editor integration

---

packages/markup-include/src/CdcMarkupInclude.tsx

Scenario: In Cove Editor running on your local environment, Select Dashboard, Select some Data set, drag and drop a markup include section onto the visualization panel. Open the Editor.
1) Open the browser console and find the file packages/dashboard/CdcDashboardComponent.
2) put a breakpoint in the updateChildConfig function. (line 228)
Expected you should not immediately hit a breakpoint.
You hit the breakpoint a few times on load but there is no infinite loop.
Functional changes are on lines 233, the deleting of useEffect. The rest of the changes are just linter changes.

dev-8923 Memory leak fixed

---

packages/chart/src/components/LinearChart.tsx

This was added in https://github.com/CDCgov/cdc-open-viz/commit/f48961c2f9399525941ae4dcb79a2e64a5a4d010, must have been a bad merge.

Fix gridline

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/data/initial-state.js

Create a chart with a "Date (Date Time Scale)" x-axis and see that the padding is 0 instead of 6%, and there are no gaps to the left of the data.

[DEV-9286] Set default x-axis padding on date charts to zero

---

packages/chart/src/_stories/Chart.stories.tsx
packages/chart/src/_stories/ChartPrefixSuffix.stories.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/LinearChart.tsx
packages/core/components/BlurStrokeText.tsx
packages/core/components/EditorPanel/Inputs.tsx
packages/core/components/_stories/BlurStrokeTest.stories.tsx
packages/core/types/Axis.ts

Option to have Y Axis labels sit above of gridlines.
Only available on vertical LinearCharts
Extends the visx Text component. Used to add a softer stroke to text
Check out storybook previews and 
Build a chart in the editor and select the "Labels above gridlines" checkbox
***Show gridlines must be checked**

[DEV-9340] Feature: Option to place Y Axis labels above Gridlines

---

packages/core/components/DataTable/DataTableStandAlone.tsx

1) create standalone table.
Expected: Toggling 'expand by default' and navigating to the dashboard preview should show a matching expanded state on page load.

fix [dev-9461] data-table-standalone-expanded-by-default

---

packages/core/components/EditorPanel/Inputs.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
packages/dashboard/src/types/DashboardFilters.ts

https://websupport.cdc.gov/projects/DEV/issues/DEV-9125
Allow a user to change the text of the Apply Filter Button that currently says GO!
There is a 20 character limit to the text 
If the Text box is left empty then the button text will remain GO!
Scenario: Open a Default Editor and choose the Dashboard Viz, select the "United States: State Sample Data" and then press Configure Your Data button
Expected: There is a Visualization box
1. Drag a Filter Dropdowns into the Visualization Box
2. Click on the tools icon
Expected: Filter Dropdowns editor opens up with a blank screen on the right.
3. Click on the General Accordion Tab
4. Select Apply Button in the Filter Behavior box
5. Click on the Filters Accordion Tab
6. Click the down arrow next to New Dashboard Filter 1
7. Select Data in the …

Dev-9125 Customizable Apply Filter Button Label

---

packages/core/helpers/cove/number.js

No ticket
**This functionality decision was made because onlyShowTopPrefixSuffix is commonly paired with a long suffix that would be overkill on each table value**
Turn on onlyShowTopPrefixSuffix and confirm prefixes and suffixes are left out

Fix [onlyShowTopPrefixSuffix] don't show prefix suffix in table when onlyShowTopPrefixSuffix

---

packages/chart/src/CdcChart.tsx
packages/chart/src/_stories/ChartAxisLabels.stories.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/data/initial-state.js
packages/chart/src/hooks/useScales.ts
packages/core/types/Axis.ts

This does four main things: 
* Makes abbreviated months with period work correctly for May
* Adds option to show each year only once in axis labels
* Padding only applies to left side
* Calculates the width of the chart correctly so gridlines extend to the end of the x-axis
Use the config attached to the ticket.
* Note that May is correctly formatted
* Toggle the "show years once" button in the date/category axis and see it has the desired effect
* Adjust the padding option in the date/category axis and see that it applies only to the left side
* Note that gridlines extend to the end of the x-axis

[DEV-9416] X-axis improvements for time series charts

---

packages/dashboard/src/components/VisualizationsPanel/VisualizationsPanel.tsx

When making a change to any multidashboard via the advanced editor the changes are saved and apply.
Scenario: Open a Default Editor and choose the Dashboard Viz and open the Configuration tab, 
1. Click on the "make multidashboard" checkbox
2. Upload dev-9358-Multidashboard.json [Linked here](https://github.com/user-attachments/files/17426364/dev-9358-Multidashboard.json) to Advanced Options
3. Save and press Apply
Expected: The visualization on the right will be populated with the information in the dev-9358-Multidashboard.json file. 

Fix: DEV-9358 Advanced Editor: Multidashboard changes not saving

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx

Rename from "Labels above gridlines" to "Tick labels on top of gridlines"
1. Open the editor
2. Make a bar or line chart
3. Open the "Left Value Axis" panel
4. Observe the field is now called "Tick labels on top of gridlines"

Refactor [DEV-9340] feedback to rename to "Tick labels on top of gridlines"

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/Annotations/components/AnnotationDraggable.tsx
packages/chart/src/components/EditorPanel/components/Panels/Panel.Annotate.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/types/ChartContext.ts

- Moves svgRef state to CdcChart
- Forwards ref from the rendered svg element to CdcChart so that it can be passed to additional components
- Annotation Panel now uses svgRef to calculate adding the annotations width/height placements
- Open a bar, line, or area chart. 
- Click add annotation
- The annotation should appear in the middle of the chart when added

[DEV-9187] Fixes Chart Annotations

---

packages/map/src/CdcMap.tsx
packages/map/src/components/Annotation/AnnotationDropdown.styles.css

- Removes red border
- Removes duplicated dropdowns
- Open Maps and add annotation
- Choose show annotation dropdown
- Verify the dropdown doesn't have a red border
- Verify only one dropdown is showing

[DEV-9558] Update annotation dropdowns on maps

---

packages/core/components/EditorPanel/DataTableEditor.tsx

https://websupport.cdc.gov/projects/DEV/issues/DEV-8345
When you remove a column from the Exclude Columns section, it puts it back on the data table and it automatically checks "Show in Data Table" in the Column Configuration 
Scenario:
Open a Default Editor and choose the Dashboard Viz and in Configuration, upload [dev-8345-stand-alone-table-excludes.json](https://github.com/user-attachments/files/17416079/dev-8345-stand-alone-table-excludes.json) to Advanced Options, then click the tools Icon on the Table Viz
Instructions:
1. 	Open the Data Table section 
2. 	In the Exclude Columns multiselect, choose STATE
Expectations: The STATE column in the Table should be removed
3. 	Open Columns Section
4. Open the STATE configuration
Expectations: The "Show in data table" checkbox is not checked …

Fix: dev-8345 Stand-alone Table Excludes Option Doesn't Communicate Between Panels

---

packages/chart/src/CdcChart.tsx
packages/chart/src/_stories/ChartPrefixSuffix.stories.tsx
packages/chart/src/components/Axis/Categorical.Axis.tsx
packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.StackedHorizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
packages/chart/src/components/BarChart/helpers/index.ts
packages/chart/src/components/BrushChart.tsx
packages/chart/src/components/DeviationBar.jsx
packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/components/Legend/Legend.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/components/PairedBarChart.jsx
packages/chart/src/components/ZoomBrush.tsx
packages/chart/src/types/ChartContext.ts
packages/core/components/Legend/Legend.Gradient.tsx
packages/map/src/CdcMap.tsx
packages/map/src/components/Legend/components/Legend.tsx
packages/map/src/types/MapContext.ts

Two things happening here:
So:
"5lbs": pushes to the left
"5lbs per meter":  overflows
"5 units": overflows
In the editor:
1. Create a Bar or Line chart
2. Open the "Left Value Axis" panel
3. Select the checkbox labeled "Only Show Prefix/Suffix" 
4. Add a Suffix without a space (i.e. something like 'lbs')
5. Observe that the suffix pushes the tick labels to the left, to the left
6. Add a suffix with a space (i.e. something like " units" or "lbs of something")
7. Observe that the suffix now overflows to the right instead

Refactor [DEV-9285] top suffix behavior and implementation adjustment

---

packages/core/components/DataTable/data-table.css
packages/core/styles/_reset.scss

The chart font was unintentionally changed from `sans-serif` to `system-ui` during the table refactor.
This fixes it by restoring `div` to `_reset.scss` (was removed in https://github.com/CDCgov/cdc-open-viz/commit/8c74a5483e112d5afec764925c52a5fba59711e3) and updating affected table styles.
Open a chart and see that the font on axis labels is `sans-serif`, not `system-ui`.

[DEV-6966] Fix chart font

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/EditorPanel/helpers/tests/updateFieldRankByValue.test.ts
packages/chart/src/components/EditorPanel/helpers/updateFieldRankByValue.ts
packages/chart/src/helpers/handleRankByValue.ts
packages/chart/src/helpers/tests/handleRankByValue.test.ts
packages/chart/src/types/ChartConfig.ts

DEV-9406
1. Run editor
2. Create bar chart with single series
3. In series settings, change rank by value to the different options and ensure they sort the x axis point appropriately
4. Return to data import tab, then back to configure and ensure setting remains

Fix: [Dev-9406] Rank By Value

---

packages/chart/src/CdcChart.tsx
packages/core/components/EditorPanel/VizFilterEditor/NestedDropdownEditor.tsx
packages/core/components/Filters/Filters.tsx
packages/core/helpers/addValuesToFilters.ts

[https://websupport.cdc.gov/browse/DEV-9346](https://websupport.cdc.gov/browse/DEV-9346)
When a nested dropdown option is selected and parameters are used, the URL will change showing the newly selected option. 
Also, when parameters are used, using the URL with parameters will selected the nested dropdown option and display the correct chart on the screen  
Scenario: Upload [dev-9346-nested-dropdown-using-parameters.json](https://github.com/user-attachments/files/17509307/dev-9346-nested-dropdown-using-parameters.json), Click on Dashboard Preview 
Expected: There is a bar chart with a nested dropdown filter.  
1. Click on the Nested Dropdown and select Age Group 3 - Overall
2. Once loaded, copy the URL
3. Click on the Nested Dropdown and select Age Group - 50-64 years
4. Replace current …

FIX: DEV-9346 Nested Dropdown: not populating filter options (Viz level)

---

packages/core/components/BlurStrokeText.tsx

No ticket
Make a chart with overlapping Y-Axis labes (i.e. "Only show top prefix/suffix" or "Labels above gridlines") and observe larger stroke

refactor [BlurStrokeText] make blur stroke default 8

---

packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/scss/main.scss
packages/map/src/components/Legend/components/Legend.tsx

https://websupport-cdc.msappproxy.net/browse/DEV-9617
Removes unused properties passed to LegendShape

[DEV-9617] align legend shape and labels for circles and squares

---

packages/editor/src/components/DataImport.tsx

Fixes Issue With Trailing Space in URL
1. Create bar chart
2. Load dataset from URL, add trailing space to end of url
3. Check "Always Load from URL"
4. Ensure column options populate correctly for "series" selection on configure screen

Fixes Issue With Trailing Space in URL

---

packages/chart/examples/feature/scatterplot/scatterplot.json
packages/chart/src/_stories/Chart.CustomColors.stories.tsx
packages/chart/src/components/ScatterPlot/ScatterPlot.jsx

1. run `yarn storybook`
2. Open `http://localhost:6006/?path=/story/components-templates-chart-custom-colors--scatter-plot`
3. Verify the circles on the chart are red and orange
The only additions are line 55 in scatter plot and the testing files. The rest is formatting from prettier since this is an older file. I used the /example file as mock data to reduce file size on the repo.

[DEV-9632] Add custom color palette for scatter plots

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/LinearChart.tsx

Only show year once not showing with small number of ticks
1. Create or view linear chart with date axis and "Show years once" activated
2. Change number of ticks and confirm it still shows years on the first tick and anytime the year changes

Fix [showYearsOnce] only show date once

---

packages/core/components/DataTable/DataTable.tsx
packages/dashboard/src/_stories/_mock/group-pivot-filter.json

Scenario: Running storybook navigate to the Pages/Dashboard/Group Pivot Filter story.
Expected: You should see groupings in blue with New York and San Fransciso, Each grouping should have two rows under them. There should be 3 columns total. Selecting from the multiselect filter will toggle the respective column.

fix [dev-9648] pivot tables adding additional rows

---

packages/core/styles/_button-section.scss

Open Data table panel ==>click "Show Download Image" the button has to be always on the right side of chart.
We had bug that it is on the left sometimes.

[DEV-9182] Align image button to the right

---

packages/map/src/components/UsaMap/components/HexIcon.tsx
packages/map/src/components/UsaMap/components/Territory/Territory.Hexagon.tsx
packages/map/src/components/UsaMap/components/Territory/Territory.Rectangle.tsx
packages/map/src/components/UsaMap/components/Territory/TerritoryShape.ts
packages/map/src/components/UsaMap/components/UsaMap.State.tsx
packages/map/src/types/MapConfig.ts

- Hex Territories > add tooltip to text
- Rectangle Territories > add tooltip to text
- Update props on UsaMap.State.tsx for Shapes
- Add TerritoryShape.ts file
- Resolved LegendShapeItem TS Issue
- Added Territory Shape TS file

[DEV-9601] maps > update tooltip hovers on territory names

---

packages/chart/src/components/LinearChart.tsx

See the ticket; the height of horizontal bar charts is initially wrong when created in the editor, and doesn't correct itself until another option is toggled.
1. Run the editor locally
2. Create a bar chart with the sample data set, change orientation to horizontal
3. Click "I'm done"
4. See that the chart is the correct height and isn't cut off by the data table on this branch

[DEV-9555] Fix initial height of horizontal bar charts in editor

---

packages/dashboard/src/store/dashboard.reducer.ts

[https://websupport.cdc.gov/projects/DEV/issues/DEV-9643](https://websupport.cdc.gov/projects/DEV/issues/DEV-9643)
Scenario: Upload [dev-9643-config.json](https://github.com/user-attachments/files/17558934/dev-9643-config.json) and open the Configuration tab. There are 4 dashboard tabs at the top: Dashboard, Compare Years, Compare Locations, All Locations
1. Hover over Dashboard and click the "X"
Expectations: The "Dashboard" dashboard will be deleted and the new first dashboard "Compare Years" will be showing.

Fix: DEV-9643 Issue with deleting tab within multi tabs

---

packages/core/components/EditorPanel/DataTableEditor.tsx

[https://websupport.cdc.gov/browse/DEV-9529](https://websupport.cdc.gov/browse/DEV-9529)
The stand-alone table has the functionality to download the table data with the "Download Data (CSV)" link.
Scenario: Upload [dev-9529-config.json](https://github.com/user-attachments/files/17575095/dev-9529-config.json), click Configuration, click the tools icon on the Table visualization
Expected: The Table editor is open with a table with some data
1. Open Data Table section
2. Check the checkbox next to Show download CSV link
Expected: Above the table to the right the Download Data (CSV) link is showing
3. Check the checkbox next to Show Download Link Below Table
Expected: The Download Data (CSV) link in now below the Table
- My changes generate no new …

Enhancement: Dev-9529 Download Data CSV link on stand alone table

---

packages/chart/src/CdcChart.tsx
packages/chart/src/_stories/Chart.Legend.Gradient.stories.tsx
packages/chart/src/components/Legend/Legend.Component.tsx
packages/core/components/Layout/components/Visualization/visualizations.scss
packages/core/components/Legend/Legend.Gradient.tsx
packages/core/types/Legend.ts
packages/map/src/CdcMap.tsx

Allow long legend labels to wrap
1. Create or view a chart with long data labels (Storybook: "Legend Gradient Wrapping Label")
2. Observe that the label wraps

Feat [DEV 9552] Wrap legend label

---

packages/core/helpers/useDataVizClasses.ts
packages/map/src/_stories/CdcMapLegend.stories.tsx
packages/map/src/_stories/_mock/wastewater-map.json
packages/map/src/components/Legend/components/Legend.tsx
packages/map/src/components/Legend/components/index.scss

Patterns were disappearing from the legend when switching to gradient
1. Create or view map with pattern (Storybook example: Templates/Map/Legend/Gradient With Patterns)
2. Switch to gradient legend
3. Observe pattern is represented

Fix [DEV-9652] Gradient legend patterns not showing up

---

packages/map/src/components/EditorPanel/components/EditorPanel.tsx

Ensures Category Values Order Holds on Filter Change
1. Get config from ticket, copy locally to example in dashboard project
2. Run dashboard project, edit first map in the dashboard
3. In Legend section, change category values order
4. Change filter dropdown in preview
5. Change filter dropdown back, ensure change made to category values order was not erased

Ensures Category Values Order Holds on Filter Change

---

packages/map/src/CdcMap.tsx
packages/map/src/_stories/CdcMapLegend.stories.tsx

Remove duplicate special class value from legend
1. Create or view map with special class gradient legend (Storybook: Components/Templates/Map/Legend/Gradient Special Class)

Fix [DEV-9652] Remove duplicate special class value from legend

---

packages/chart/src/components/LinearChart.tsx

See ticket, fixes issue flagged by Cailin when adding filters to horizontal bar charts in the editor.
* Run the editor locally
* Create a bar chart using sample data
* Change orientation to horizontal, set x/y axes, click "I'm done"
* Add a filter, see that chart height resizes correctly (unlike on `dev`)

[DEV-9555] Fix height not updating when filter added in editor

---

packages/core/components/Filters/Filters.tsx
packages/core/components/NestedDropdown/NestedDropdown.tsx
packages/core/components/NestedDropdown/nesteddropdown.styles.css
packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx

[https://websupport.cdc.gov/browse/DEV-9755](https://websupport.cdc.gov/browse/DEV-9755)
Scenario: Upload [dev-9755-config.json](https://github.com/user-attachments/files/17721438/dev-9755-config.json) and navigate to the dashboard preview.
Expected: There are 2 dashboard filters. The first is a Nested Dropdown and the second is a Dropdown filter. 
1. Click on the Nested dropdown box
Expected: The Nested dropdown filter opens up
2. Click anywhere outside of the Nested Dropdown
Expected: The Nested dropdown filter closes

Fix: Dev-9755 - Nested dropdown doesn't close on blur to another dropdown

---

packages/core/components/Legend/Legend.Gradient.tsx
packages/map/src/CdcMap.tsx
packages/map/src/_stories/CdcMapLegend.stories.tsx
packages/map/src/components/Legend/components/Legend.tsx

Match font for "limited coverage" to the legend labels
Wrapped map labels extra "line-height"
More bottom-padding to legend when hideBorders
Remove cursor pointer from gradient
1. Create map with gradient legend
2. Observe changes

Refactor [DEV-9652] gradient legend improvement feedback

---

packages/chart/src/components/LinearChart.tsx

[https://websupport.cdc.gov/browse/DEV-9744](https://websupport.cdc.gov/browse/DEV-9744)
The bar graphs display a "No Data Available"
Scenario: Upload [dev-9744-config.json](https://github.com/user-attachments/files/17756894/dev-9744-config.json) and navigate to the dashboard preview.
Expected: There is a dashboard filters with "No Option Selected" and there is a message that says, "No Data Available." This is the chart that has no data. 
1. In the Location Filter choose a state
Expected: The chart now appears with data
2. In the Location Filter, select "No Option Selected"
Expected: "No Data Available" has taken the place of the chart

Fix: Dev-9744 - Charts: No data state doesn't show

---

packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx

Stacked bar charts that use a Date (Linear Scale) x-axis are currently positioned too far to the left by half a bar. This PR shifts the bars to the right by half a bar so they're lined up correctly
Use the attached config, see that the position of bars is correct on this branch.
dev/test:
this branch:
[vaxbars.json](https://github.com/user-attachments/files/17802911/vaxbars.json)

Fix position of stacked Date (Linear Scale) bars

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/components/Legend/helpers/getLegendClasses.ts
packages/chart/src/components/Legend/tests/getLegendClasses.test.ts
packages/chart/src/data/initial-state.js
packages/chart/src/scss/main.scss

- Fixes an issue when building charts where "hide legend border" only worked in the chart package
- Removes `.no-border` class to favor bootstraps `.border-0` on legends
- Updates reversed legend ordering to have better spacing on the first item when the legend is reversed
- Moves `hooks/useLegendClasses` to `helpers/getLegendClasses`
- Adds tests for legend classes
- Removes duplicated hide legend item toggle

[DEV-9553] Chart > Legend Updates

---

packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
packages/core/components/Filters/Filters.tsx

- When a filter is hidden from view stop showing the intro text
- It doesn't seem like the active or columnName properties should hold any weight with intro text being displayed
- Update `addNewFilter` handler to add the showDropdown property 

[DEV-9564] Filters > Hide Intro Text

---

packages/map/src/components/Legend/components/Legend.tsx

Gradient legend shouldn't be tabbable since nothing is selectable
1. Create or view map or chart with gradient legend
2. Try selecting via click or tab
3. Observe that is doesn't get selected

Fix: Gradient legend shouldn't be selectable

---

packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx

Open Bar chart vertical (regular)
Switch to Lollipop
Make sure we have negative values in our data set example (Data 1: -300) 
select that series while chart is lillipop;
on visual panel change lollipop shape from circle to square. 
Square should be on top of the bar even if that bar is negative.

FIX [DEV-9233] Update y position for lollipop chart

---

packages/core/components/Loader/Loader.tsx
packages/core/components/MultiSelect/MultiSelect.tsx
packages/core/components/MultiSelect/multiselect.styles.css
packages/core/components/NestedDropdown/NestedDropdown.tsx
packages/core/components/NestedDropdown/nesteddropdown.styles.css
packages/core/styles/_reset.scss
packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
packages/dashboard/src/components/DashboardFilters/dashboardfilter.styles.css

testing instructions are in the ticket and require an api connection for the api dropdowns.

enhancement [dev-9440] loading states on dropdowns

---

packages/map/src/CdcMap.tsx
packages/map/src/components/UsaMap/components/UsaMap.State.tsx

- Create a state map
- Upload a csv file with "District of Columbia" as the state value in a csv file.
- Under Type > Check "Display as hex map"
Previously the only value that was working was "DC". This was because that value is in the state dictionary file. These changes fit a number of the possibilities of DC to fit the US-DC code in the hex code topojson file.

[DEV-9802] District of Columbia support on hex maps

---

packages/core/components/Filters/Filters.tsx
packages/core/components/NestedDropdown/NestedDropdown.tsx

https://websupport.cdc.gov/browse/DEV-9864
On Nested Dropdowns the label does not repeat.
Scenario: Upload [dev-9864-config.json](https://github.com/user-attachments/files/17821457/dev-9864-config.json) and navigate to the dashboard preview.
Expected: There are 3 filters on top, a markup include, and then 2 filters in the Trends over Time section. The Demographic filter's title is only shown once.

Fix: Dev-9864 Duplicate Dropdown label in Dashboard

---

packages/core/components/Filters/Filters.tsx
packages/core/components/NestedDropdown/NestedDropdown.tsx

Reverts CDCgov/cdc-open-viz#1702
This is breaking labels for the Dashboard Filters.

Revert "Fix: Dev-9864 Duplicate Dropdown label in Dashboard"

---

packages/core/components/DataTable/components/ExpandCollapse.tsx
packages/core/components/DataTable/components/SortIcon/sort-icon.css
packages/core/components/Table/components/Row.tsx
packages/core/styles/_global-variables.scss
packages/dashboard/src/components/CollapsibleVisualizationRow.tsx

This does three things:
1) Changes the mobile breakpoint for displaying mobile data table font sizes from `768px` to `576px` so desktop font sizes will be used in the DFE center column
2) Reduces font size of mobile table headers, increases size of mobile cells
3) Improves layout of sorting triangles on mobile
View some charts with data tables on all screens sizes.
Before:
After:
There is a larger data table font refactor coming from the UX team, this PR just makes some interim improvements.

[DEV-9859] Improve mobile data table font sizes

---

packages/map/src/_stories/UsaMap.NoData.stories.tsx
packages/map/src/_stories/_mock/example-city-state.json
packages/map/src/components/UsaMap/components/UsaMap.State.tsx

Part of this ticket was already resolved where territories were showing black when no data was passed in. This adds the stroke color around the squares as well.

[DEV-9801] review territory no data state

---

packages/chart/src/_stories/Chart.stories.tsx
packages/chart/src/_stories/_mock/line_chart_confidence_intervals.json
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx
packages/chart/src/components/LineChart/index.tsx

CI's are added under the series level as a repeating field. This decision was made because not all CI's will be uniform. The repeater allows multiple confidence intervals to be added to the line if needed (ie. 25/50/95). We're re-using the pattern from Forecasting charts to keep the config lean `series.confidenceIntervals` since its the same feature.

[DEV-9840] add confidence intervals to line charts

---

packages/dashboard/src/CdcDashboardComponent.tsx
packages/dashboard/src/components/VisualizationRow.tsx

[https://websupport.cdc.gov/browse/DEV-9448](https://websupport.cdc.gov/browse/DEV-9448)
When a drop-down option is changed, all affected items in the dashboard are hidden and the message "Please complete your selection to continue." appears
Scenario: Upload [dev-9448-config.json](https://github.com/user-attachments/files/17751499/dev-9448-config.json)  and navigate to the dashboard preview.
Expected: There are 2 dashboard filters and under them the message "Please complete your selection to continue." 
Make a selection in both dropdowns
Click the Go! Button
Expected: The message has been removed and a new Quarter dropdown has taken its place. There is also the Expand and Collapse All toggles and the Table toggle for multi-viz rows. 
Change the option in the Location dropdown
Expected: …

Enhancement: Dev-9448 Data Reset Scenario

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
packages/dashboard/src/helpers/filterData.ts

To verify the fix, follow these steps in the dashboard:
Open the Dashboard: Navigate to the main dashboard view.
Add Shared Filters: Include shared filters applicable to the dataset.
Insert Visualization: Add either a Bar chart or a Map to the dashboard.
Configure Shared Filters: Setup the shared filters to interact with the visualization.
Set Reset Label: In the filter configuration, set the "Reset Label" to a valid entry such as "Arizona" (assuming the filter category is "State").
Expected Behavior
Before the Fix: Selecting "Arizona" as a reset label resulted in its duplication in the filter selector—one as a reset label and once as a data value.
After the Fix: "Arizona" now only appears once in the selector. It is set as the default (active) filter value and filters the data based on …

[DEV-9624] Update filters reset label logic

---

packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
packages/core/components/Filters/Filters.tsx
packages/core/components/MultiSelect/MultiSelect.tsx
packages/core/components/NestedDropdown/NestedDropdown.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
packages/map/src/components/EditorPanel/components/EditorPanel.tsx
packages/map/src/data/initial-state.js
packages/map/src/types/MapConfig.ts

Adds an editor field to customize the filter intro text, and removes forced capitalization from filter labels.
* Create a chart with a filter, change the text in the "filter intro text" field, see the intro text change.
* Change the filter label, note that it doesn't have forced capitalization
* Compare to the dev branch, where the filter intro text is hardcoded and can not be hidden, and filter labels are always capitalized.
Try a few setups (single chart, map, dashboard).

[DEV-9858] Make filter intro text customizable

---

packages/chart/src/hooks/useMinMax.ts

https://websupport.cdc.gov/browse/DEV-9910
The Max and Min values can be set for the yAxis
Scenario: Upload [dev-9910.json](https://github.com/user-attachments/files/17922575/dev-9910.json) and navigate to Configuration
Expected: The Editor is open for a Bar Graph. The left axis's max amount is 50+.
1. Open the "Left Value Axis" accordion
2. In the "Left Axis Max Value" box, change the amount to 100
Expected: The left axis's max amount is 100

Fix: Dev-9910 yAxis Max and Min height can be set

---

packages/chart/examples/feature/tests-date-exclusions/date-exclusions-config.json
packages/chart/index.html
packages/chart/src/_stories/Chart.Anchors.stories.tsx
packages/chart/src/components/LinearChart.tsx

Anchor lines weren't plotting at the correct location. This accounts for the xScale.bandwidth() / 2 (middle point of linear axis tick) when the scale type is either date (linear) or categorical (linear).
**Before**
**After**

[DEV-9822] Resolve issues with plotting anchors properly on the x axis

---

packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/hooks/useScales.ts

Label latest tick for charts with a "Date (Linear Scale)" x-axis.
Using the config attached to the ticket or another chart with a "Date (Linear Scale") x-axis, verify that the last tick is always labeled on all screen sizes.
Before:
After:

Enhancement [DEV-9857] Label last tick

---

packages/map/src/components/EditorPanel/components/EditorPanel.tsx

On maps when Legend position set to Top or Bottom the Legend box border should be removed by default and checkbox
"Hide Legend Box" should be ON after change.

Fix[DEV-9561c] Default Legend Box for Maps: Change to off for Top and Bottom

---

packages/chart/src/hooks/useMinMax.ts

Preventing the yAxis Max from exceeding the max amount set unless a value is higher than the max. 
Scenario: Upload [dev-9916-config.json](https://github.com/user-attachments/files/17925557/dev-9916-config.json) and navigate to Dashboard preview.
Expected: There are a 6 filters
1. Select the following choices for the fitlers:
- Dataset: NationWide
- Location: States - Georgia
- Class: Chronic Health Indicators
- Topic: Asthma
- Year: 2021
- Question: 1st choice - Adults who have been...
2. Push View Results button
Expected: A bar chart is shows with the "No" response approaching 100% and the yAxis does not exceed 100%

Fix/Dev-9916 Y-Axis not responding to max value for line chart

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/EditorPanel/useEditorPermissions.ts
packages/chart/src/components/LinearChart.tsx
packages/chart/src/helpers/countNumOfTicks.ts

In an effort to never overlap data with grid when "Only show top prefix/suffix" is activated - auto generate padding if gridline is above maxValue
1. Create of view linear chart vertical chart with "Only show top prefix/suffix" activated
2. Observe the label does not overlap data

Enhancement: auto calculate padding for overflowing grid labels

---

packages/map/examples/default-geocode.json
packages/map/src/CdcMap.tsx
packages/map/src/_stories/CdcMap.stories.tsx
packages/map/src/_stories/_mock/example-city-state.json
packages/map/src/helpers/applyColorToLegend.ts

Prior to this release custom color palettes were using the color distributions array which was confusing folks. For example if users had a legend with three items they would need to enter ['red', 'red', 'yellow', 'yellow', 'orange', 'orange'] as a workaround to achieve red, yellow, and orange since thats how the color distribution matrix picks our sandard colors. This also moves the ts file out of CdcMap and fixes issues with calculating special class colors. See testing steps for more info.

Fix: [DEV-9931] Adjust color palette settings on maps

---

packages/chart/src/_stories/Chart.stories.tsx
packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx
packages/core/helpers/coveUpdateWorker.ts
packages/core/helpers/ver/4.24.12.ts
packages/core/types/Series.ts

From the ticket:
Multiple data series confidence intervals on charts are not currently supported. You can hack this by using a dynamic series and still having the CI options display, but then they cause issues with the y-axis (ex max height isn't maintained and the suffix overlaps the number).

Fix: [DEV-9850] Add confidence interval migrations to bar charts

---

packages/chart/src/hooks/useTooltip.tsx

This fixes an issue introduced in DEV-9285 that prevented a prefix/suffix from showing in tooltips. This fix shows it only on the first item.
Create a chart with the "onlyShowTopPrefixSuffix", ensure that the prefix/suffix is visible on the first item in the tooltip.
Before:
After:

Fix [DEV-9285] Show prefix/suffix on top tooltip item

---

packages/map/src/CdcMap.tsx
packages/map/src/components/Legend/components/Legend.tsx
packages/map/src/components/WorldMap/WorldMap.tsx
packages/map/src/hooks/useTooltip.ts

https://websupport.cdc.gov/browse/DEV-9453
When there is no data to show in the map, a "No Data" message is added to the legend and a tooltip is created with no data on hover.
Scenario: Upload [dev-9453-config.json](https://github.com/user-attachments/files/17816638/dev-9453-config.json) and navigate to the dashboard preview.
Expected: There is a world map with some countries highlighted according to the Legend and the Legend has a category call "No Data"
Hover over a country that is gray.
Expected: A tooltip appears with the country name and "No Data" at the bottom of the tooltip.

Enhancement: Dev-9453 World Map No Data Scenario

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx

https://websupport.cdc.gov/browse/DEV-9917
Made the option to Isolate or Highlight a bar graph in the Legend when there are multiple bars on a singular xAxis point.
Scenario: Upload [dev-9917-config.json](https://github.com/user-attachments/files/18026134/dev-9917-config.json) and click on the Configuration tab, and click on the tools icon in the Bar graph visualization 
Expected: There is a bar graph with multiple bars and multiple legend icons. 
1. In the Legend, click USA
Expected: The Canada and Germany bars have been removed and USA has been Isolated
2. Open the Legend tab on the left
3. Under the "Legend Behavior (When Clicked)," change Isolate to Highlight
Expected: The Canada and Germany bars have returned and USA has been Highlighted
- …

Fix/Dev-9917 Highlight option was disabled from the Bar graph

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/LinearChart.tsx
packages/core/components/Layout/components/Visualization/visualizations.scss

Last tick sometimes overflows the bounds of the viz
Add Padding
Force wrap if tick is close to edge
1. Open linear chart with long tick close to edge (Storybook ex: components-templates-chart--multiple-lines)
2. Observe tick should not overflow

Fix [X-Axis] Last tick overflow

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx

Removes the `.text-capitalize` class that was added back in [this PR](https://github.com/CDCgov/cdc-open-viz/pull/1710).
Look at a dashboard and ensure filter labels aren't capitalized.

Fix [DEV-9858] Remove capitalize

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx

Open Dashboard Filters. Select "Data" as main filter. set filter as "Nested Dropdown"
Before fix : No dropdown options to select
After fix : Dropdown works.
Check image result:

FIX:[DEV-9765] Dashboard Filters - Parent & Nested

---

packages/dashboard/src/components/VisualizationRow.tsx

https://websupport.cdc.gov/browse/DEV-9448
Hide the toggle buttons on in no Data scenario
Scenario: Upload [dev-9448-Hide-Toggle-config.json](https://github.com/user-attachments/files/18082867/dev-9448-Hide-Toggle-config.json) and open Dashboard Preview
Expected: There are 2 dashboard filter with no selections made. The "Please complete your selection to continue." message is shown with no results
1. Make selections for both filters
2. Press View Results
Expected: There is a table with toggles of "Table" and "Chart" that were no showing when there was no data.

Enchancement/Fix Dev-9448 Hide Toggle on Data Reset Scenario

---

packages/core/components/MultiSelect/multiselect.styles.css
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx

https://websupport.cdc.gov/browse/DEV-9951
Used By section has a title 
the rows are not repeating
dropdown to select the rows is appearing 
rows can be added and deleted
Scenario: Upload [dev-9951-config.json](https://github.com/user-attachments/files/18081715/dev-9951-config.json) and open the Configuration tab. Then click on the tools icon on the Filter Dropdowns.
Expected: There is a Quarter filter.
1. Open the Filters section in the Accordion
2. Open the Quarter filter
3. Scroll down to the Used By section
Expected:
- There is a "USED BY: (OPTIONAL)" Title
- In the Used By selection area, there are Rows 2, 3, 5, 6, and 7. And they do not have duplicates.
- Clicking on the down arrow in will create a dropdown with options of Rows to select from.
- I have added testing steps for …

Fix/Dev-9951 Dashboard Filter Used By rows Duplicating

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx

https://websupport.cdc.gov/browse/DEV-9988
The Apply button is disabled until all filters are filled out
Scenario: Upload [dev-9988-config.json](https://github.com/user-attachments/files/18085390/dev-9988-config.json) and open Dashboard Preview
Expected: 2 Dashboard Filters with no options selected. The "View Results" button is grayed out and disabled
1. Click the View Results button
Expected: Nothing happens
2. Select a Topic and Location
Expected: The View Results button in no longer grayed out and is enabled
3. Click the View Results button
Expected: Button works as expected
4. Change the Topic filter
Expected: the View Results button is grayed out and disabled until you choose a location.
- New and …

Fix/Dev-9988 Apply button can be clicked with empty filters

---

packages/dashboard/src/components/VisualizationRow.tsx

Footnotes hide on Data Reset Scenario
Scenario: Upload [Footnotes-remain-on-data-reset.json](https://github.com/user-attachments/files/18100125/Footnotes-remain-on-data-reset.json) and open Dashboard Preview
Expected: 4 Dashboard filters with no selections made. The "Please complete your selection to continue." message is in place of the visualizations.
1. Make a selection for all 4 filters and click View Results
Expectation: The visualizations show and when the tester scrolls down they will find the footnotes that start with "** Median value reported with no confidence intervals..."
2. Change a filter selection without pressing View Results
Expectation: The "Please complete your selection to continue." message is in place of the visualizations including the Footnotes.
- I have added …

Enhancement/Fix - Dev-10060-Footnotes are showing in Data Reset Scenario

---

packages/dashboard/src/components/VisualizationRow.tsx

https://websupport.cdc.gov/browse/DEV-9978
Footnotes filter based off dashboard filter
Scenario: Upload [dev-9978-config.json](https://github.com/user-attachments/files/18100671/dev-9978-config.json) and open Dashboard Preview
Expected: There is a Year filter and scrolling down there are Footnotes that start with "*In 2017–2019, race or ethnicity was..."
1. Select the year 2020 in the Year filter. 
Expected: The Footnotes have changed and now start with "*In 2020, race or ethnicity was missing..."

Fix/Dev-9978 MMRIA issues footnotes not filtering

---

packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx

Correctly labeled Parent Filter
Scenario: Upload [dev-10076-config.json](https://github.com/user-attachments/files/18102591/dev-10076-config.json) and open Configuration. Click the tools icon on the second Filter Dropdowns
Expected: Dashboard filter with the title New Dashboard Filter 5
1. Click on Filters and open the filter
Expected: Scrolling down there is a Parent Filter(s) dropdown

Fix/Dev-10076 Parent filter section labeled incorrectly

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
packages/dashboard/src/helpers/filterData.ts

If reset label example "Florida" is exist in the list of filter values it should not be duplicated in the list.
see attached image. Reset label is Florida. from the list I removed second Florida.

FIX:[DEV-9666a] Dashboard Reset Label: When present in the data set shouldn't appear twice

---

packages/dashboard/src/CdcDashboardComponent.tsx

https://websupport.cdc.gov/browse/DEV-10048
Datasets are not saved in footnote's config
Scenario: Upload [dev-10048-config.json](https://github.com/user-attachments/files/18117875/dev-10048-config.json) and open the Configuration Tab. 
Expected: There is a single Bar visualization
1. Click on Add Footnotes on the Bar Visualization
2. Select valid-data-chart.csv from the Select a footnote dataset
3. Click Back to Dashboard
4. Click Advanced Options
5. Scroll down to Visualizations and then footnotes1734040286223
Expected: The footnotes config does not have datasets saved in it's config

Fix/Dev Datasets saved in footnote's config

---

packages/dashboard/src/components/Widget.tsx
packages/dashboard/src/store/dashboard.actions.ts
packages/dashboard/src/store/dashboard.reducer.ts

Open dashbpard. add Bar chart or line chart widgets, setup bars and come back to default page. remove widget and try to add new widget to the removed space.
Before fix: New widget cannot be added if old widget removed
After Fix: new widget can be added after removing old one.

FIX:[DEV-9666] New widget can't be add to a visualization box after an old widget is deleted

---

packages/chart/src/components/LinearChart.tsx

Problem: data was still overflowing despite auto-padding
cause: padding percentage was so minuscule that the js decimal math was throwing it off enough it wasn't enough to reach the next tick - and even if it did, since it was so close to the next tick the text would still overlap the data
solution: if the auto padding percentage is below a certain threshold (0.02), then add 1 tick worth of EXTRA padding to take it to the next tick.
1. Open 
[Respiratory-Virus-Activity-Age_relative.json](https://github.com/user-attachments/files/18212798/Respiratory-Virus-Activity-Age_relative.json) and click the "Influenza" tab
2. Observe that the data should not overflow the top tick and the text should not cover the data
- I have commented my code, …

Fix [Auto Padding] insufficient auto padding added

---

packages/chart/src/components/LinearChart.tsx

Chart breaking when auto padding on and only 1 tick is generated
1. use [trends-nhsn.json](https://github.com/user-attachments/files/18232852/trends-nhsn.json)
2. Select Arkansas
3. Observe it doesn't break

Fix[Auto Padding]: auto padding breaking when only one tick

---

packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
packages/core/components/Filters/Filters.tsx
packages/core/components/Filters/helpers/handleSorting.ts
packages/core/helpers/addValuesToFilters.ts
packages/core/types/VizFilter.ts

Scenario: Upload [dev-9990.json](https://websupport.cdc.gov/secure/attachment/72969/72969_dev-9990.json) and navigate to the visualization panel.
1) click on the tools icon next to the table widget.
Expected: data should appear unordered in the table.
2) under the filters accordion add a new filter.
3) select 'Text' as the filter.
Expected: by default the filter options will be sorted alphabetically
4) change Filter Order to "Order by Data Column"
5) Select OrderCol as the Order Column.
Expected: The filter options should now be in the order: this, is, the, order.

PATCH Enhancement [dev-9990] filter order column

---

packages/chart/src/CdcChart.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/components/Legend/Legend.tsx
packages/chart/src/scss/main.scss
packages/chart/src/types/ChartContext.ts
packages/core/components/Legend/index.tsx
packages/core/helpers/useDataVizClasses.ts
packages/map/src/components/Legend/components/Legend.tsx
packages/map/src/components/Legend/components/index.scss

specs from [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
- Apply a border to the container and when swatch/category is selected update "Reset" button so it aligns with TP5.
- Change "Reset" button label to "Show All" 
1. open map or chart with legend
2. click legend item
3. confirm non-hidden items have border
4. confirm reset button now says "Show All"

Enhancement [DEV-10068] legend updates

---

packages/chart/src/components/LinearChart.tsx

specs from [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
1. open linear chart in mobile view
2. confirm tick labels are 13px
3. confirm axis labels are 14px

enhancement [DEV-10068] Mobile font sizes for charts

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx

Add character limit to axis labels
1. Open editor
2. try and type more than 35 characters in the axis label field
3. confirm you are restricted from doing so

Enhancement [DEV-10066] axis label character limit

---

packages/chart/src/hooks/useTooltip.tsx

Open Pie Chart
Update decimal point to 1 and hover on Pie, 
the tooltips should follow decimal point updates.
See attached image resul:

FIX:[DEV-10195]   Pie chart: Hover showing wrong decimals

---

packages/map/src/_stories/_mock/DEV-9989.json
packages/map/src/components/Modal.tsx
packages/map/src/scss/main.scss
packages/map/src/scss/map.scss

On maps, when the modal is too large the modal was cutoff by the overflow CSS property and then extended above the top fold of the screen. This keeps the modal in view and allows vertical scrolling.

[DEV-9989] update modals

---

packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx

1) upload 
[explore-by-topic-2025-01-09.json](https://github.com/user-attachments/files/18398614/explore-by-topic-2025-01-09.json)
2) navigate to the filter accordion for the first map visualization editor.
3) expand the second filter accordion.
Expected: you should see an item under the "filter parents" selection.

PATCH fix [dev-10273] viz filter editor not showing selected parents

---

packages/core/components/Filters/Filters.tsx
packages/core/helpers/addValuesToFilters.ts
packages/core/helpers/filterVizData.ts
packages/core/helpers/tests/addValuesToFilters.test.ts
packages/map/src/CdcMap.tsx

Scenario: Upload [dev-9866.config.json](https://github.com/user-attachments/files/18412453/dev-9866.config.json) open the Configuration tab, and open the map editor
Expected: There is a Map of the US with no filters.
1. Open the Filters Accordion
2. Add Filter
3. Select Nested Dropdown from the Filter Style
4. Select STATE as the Grouping and Rate as the Subgrouping
5. Make selections in the Nested Dropdown
Expected: The Map will highlight the state with the correct data.

PATCH FIX/dev-9866 Nested Dropdown filter availability - maps

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.General.tsx
packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
packages/chart/src/data/initial-state.js

Bar chart labels and outline enabled by default, add tooltips recommending to remain enabled.
- Create a new bar chart or use a config that does not specify `barHasBorder` or `labels` (boolean)
- Bar chart should have border and text labels by default
- Check editor for both options for tooltip that recommends the options be enabled
n/a
n/a

[DEV-9281] Bar charts with no labels or borders fail non-text contrast

---

packages/chart/src/CdcChart.tsx
packages/core/components/DataTable/DataTable.tsx

make generic defaultSortBy for datatable
1. Open chart with date axis
2. confirm sorting is newest to oldest

Enhancement [DEV-10198] make generic defaultSortBy for datatable

---

packages/chart/src/CdcChart.tsx

Problem: Time axis default sort not showing when changing from categorical in the editor
Solution: Remount datatable when default sort changes
1. create or open table
2. toggle between categorical and date axis
3. datatable should be sorting by date when date axis and should have no sort when categorical

enhancement [DEV-10198] remount data table if default sort changes

---

packages/chart/src/components/LinearChart.tsx

Fixes date/time manual ticks.
* Load the provided config
* Change the xAxis to "Date (Date Time)"
* Check the "manual ticks" option
On `dev`, this will break the chart, on this branch it will not. 

Fix xAxis date/time manual ticks

---

packages/chart/src/data/initial-state.js

Revert to default labels off on all charts, including bar graphs, after concerns with text overlaps on most data per recent meeting.
- Create a new chart, or use a config that does not specify a `labels` option.
- Charts should no longer display labels by default
- Bar charts should continue to default to have borders on
n/a
n/a

[DEV-9281] Revert inititial chart label state

---

packages/dashboard/src/CdcDashboardComponent.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
packages/dashboard/src/store/dashboard.reducer.ts

https://websupport.cdc.gov/browse/DEV-10215
Scenario: Upload [dev-10215-config.json](https://websupport.cdc.gov/secure/attachment/73456/73456_dev-10215-config.json) and open the configuration tab.
Expected: A multi-dashboard editor with only one dashboard
1. Click the + button next to New Dashboard 1 to create a second Dashboard
2. Click on the New Dashboard 2 tab
Expected: The Dashboard Editor for New Dashboard 2 opens with no errors
I am not putting a Milestone because I am not sure if this can be pushed through quickly

Fix/Dev-10215 Issue Opening Second Dashboard

---

packages/chart/src/components/LinearChart.tsx

If maxValue is too close to last tick add enough padding to render next tick
1. Open:
[test-in-percent-test-positivity-in-usa.json](https://github.com/user-attachments/files/18564526/test-in-percent-test-positivity-in-usa.json)
2. Confirm line does not go all the way to top

Fix [linearChart] auto padding adjustment

---

packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/DeleteFilterModal.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
packages/dashboard/src/store/dashboard.reducer.ts

Scenario: upload [dev-10241.json](https://github.com/user-attachments/files/18662996/dev-10241.json) and navigate to dashboard preview.
1) change the race in the first "First" dropdown.
2) scroll down and change the second "First" dropdown to a different value that the first.
Expected: The charts should be filtered based on their respective filter value.
3) navigate to one of the dashboard filter widgets' editor panel.
4) add a two new filters and give them the same label.
Expected: The second filter you add should have the label you typed plus ' (1)'
5) add another filter with the same label.
Expected: The third filter you add should have the label you typed plus ' (2)'
- My …

fix [dev-10241] shared filter keys repeating

---

packages/dashboard/src/CdcDashboard.tsx
packages/dashboard/src/store/dashboard.reducer.ts

PATCH fix [dev-10471] [dev-10413] issues saving changes on dashboard

---

packages/chart/src/hooks/useScales.ts

Fixed issue with numbers like 99.5  to round for scatter plot if X axis type categorical. for continues axis it is working properly.

FIX: [DEV-10222] Scatter Plot X Axis Rounding Down

---

packages/dashboard/src/helpers/getFilteredData.ts

https://websupport.cdc.gov/browse/DEV-10303
Multi-viz Rows are able to be filtered by Dashboard Filters
Scenario: Upload [multiviz dash.json](https://websupport.cdc.gov/secure/attachment/73225/73225_multiviz+dash.json)and open Dashboard Preview
Expected: There is a filtered text Viz with the word Overall in it and 2 Dashboard Filters for State and Location. There is a Multiviz Table that is show information for Vehicle.
1. Change the State filter to another state
Expectations: The Filtered Text Viz will change and the name of the chosen state will be displayed.
2. Change the Location filter to another Location
Expectations: The Multiviz Table and Footnotes will show information for the Location that was chosen.
- I have commented my code, …

FIX: Dev-10303 Filters not applying on Multi-viz Elements

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx
packages/chart/src/hooks/useTooltip.tsx

Open Charts. Under Data Series Panel now each series has default value on the Title textfield. if you clean it the toltips will be cleaned as well. Legend will remain. This is requirement from ticket. Thet want remove blank fields from tooltip while keeping value.

FIX:[DEV-10224] Blank Column Name or Series Name Displays Colon in Hover

---

packages/chart/src/components/LineChart/index.tsx

When dynamic series was On and Legend behavior was isolate mode the Line chart lines was missing when user clicked Legend items to make visible only specific lines. now they work properly.

FIX:[DEV-10304a] Dynamic Series Legends Can't be Isolated

---

packages/core/components/Filters/Filters.tsx
packages/dashboard/index.html
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
packages/dashboard/src/helpers/addValuesToDashboardFilters.ts

For filters:
new field that is explicitly the default filter value that is separate from the "active" selection could potentially. This will allow users to select a default value without having to change the sort order.
On a shared filter there should be a new dropdown for setting the active value on data filters.

[DEV-10402] Set Default Filter Value

---

packages/core/components/DataTable/helpers/chartCellMatrix.tsx
packages/core/components/Table/Table.tsx

Group by presents the data in the order it is passed through the dataset
In the Ticket https://websupport.cdc.gov/browse/DEV-10508
Did not test with URL data with the server acting up. But I believe there shouldn't be a difference.

Fix: Dev-10508 Group By column doesn't allow column order

---

packages/core/components/Filters/Filters.tsx
packages/core/styles/filters.scss

Filters should be in a row
1. Open Viz with multiple filters
2. Filters should be in a row until they wrap for screensize
3. "Tab-Simple" should still take up a whole row

fix: filters should be in a row when possible

---

packages/dashboard/src/components/CollapsibleVisualizationRow.tsx

Testing steps are on ticket. https://websupport.cdc.gov/browse/DEV-9932
Needed to remove more space around the Heading title
Scenario: Upload [dev-9932-config.json](https://websupport.cdc.gov/secure/attachment/73774/73774_dev-9932-config.json) and open Dashboard Preview.
Expected: There is a multi-viz table row that is separated by Race with Expand All/Collapse All buttons.
Expected change: There are no white spaces around the table headers

Fix: Dev 9932 Table heading spacing issue for Multi-Visualizations

---

packages/dashboard/src/components/CollapsibleVisualizationRow.tsx

Needed to remove more space around the Heading title
Scenario: Upload [dev-9932-config.json](https://github.com/user-attachments/files/18945335/dev-9932-config.json) and open Dashboard Preview.
Expected: There is a multi-viz table row that is separated by Race with Expand All/Collapse All buttons.
Expected change: There are no white spaces around the table headers

Hot Fix: Dev-9932 Multiviz h4 adding white space

---

packages/chart/src/CdcChartComponent.tsx
packages/map/src/CdcMap.tsx

This fixes the `cove_loaded` event so it runs after charts finish loading. I'm pretty sure it used to work that way, but was changed during one of the refactors.
Load a chart/map with subtext. Right after the `publish('cove_loaded'` lines touched in this PR, add:
```
console.log(['COVE LOADED', container.querySelector('.subtext')])
```
On the `test` branch, the `querySelector` will not find anything, on this branch it will. Also test various chart configs to ensure it doesn't break.

Hot Fix: Run cove_loaded after charts load

---

packages/dashboard/src/components/VisualizationRow.tsx

The toggle rows do not disappear after switching between toggles
Scenario: Upload [oral-health-update.json](https://github.com/user-attachments/files/19012087/oral-health-update.json) and open Dashboard Preview
Expected: There are 4 dashboards and the current dashboard, All States, has 2 filters. 
1. Make a selection for both filters and Click Run Report 
Expected: The dashboard loads with a map in a toggle row. There are 3 buttons: Map, Chart, and Table 
2. Click the Table button
Expected: The Map will be replaced with a Table.
3. Click on the Dashboard tab Single County
Expected: The Single County Dashboard opens up and there are 5 filters
4. Make a selection for all 5 filters and click Run Report
Expected: The dashboard loads with a chart in a toggle row. There are 2 buttons: Table and …

Fix: Dev-10558 Toggle Data Viz disappears when toggle changes

---

packages/chart/src/CdcChart.tsx

This removes a double data request for charts that load remote data via a `dataUrl`.
It's not clear to me what situation this `loadDataFromConfig` function is needed. It only loads remote data when 1) there's a `dataUrl` and 2) there are no url filters, but then [this useEffect](https://github.com/CDCgov/cdc-open-viz/blob/dev/packages/chart/src/CdcChartComponent.tsx#L405-L421) in CDCChartComponent also loads the remote data in that situation.
In my testing I didn't find any configurations where it's needed, but it's possible I missed something.
[sample config](https://github.com/user-attachments/files/19030623/covid-vaccination-intent-viz.json)
Load a `dataUrl` chart locally. On the `dev` branch, there will be two network requests for the data file in the network tab, on this branch there …

Fix [DEV-9150] Fix double chart request

---

packages/chart/src/CdcChartComponent.tsx
packages/chart/src/components/EditorPanel/helpers/updateFieldRankByValue.ts
packages/chart/src/components/LineChart/index.tsx

Open Line chart
On visual panel check "Append Series Name to End of Line Charts" 
It should show text to the end of line chart.
if text is more than 10 letters it will start truncating it.
if legend on the right the text will be hidden.
Line text colors follows the line colors
update series names manually to see different text results.

FIX:[DEV-9662] Handle Line chart append text

---

packages/core/helpers/formatConfigBeforeSave.ts
packages/core/helpers/tests/formatConfigBeforeSave.test.ts
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
packages/dashboard/src/helpers/removeDashboardFilter.ts
packages/dashboard/src/helpers/tests/removeDashboardFilter.test.ts

Scenario: In cove editor. select dashboard visualization. Select a data set and navigate to the configure tab.
1) drag and drop a "dashboard filters" widget onto the visualization panel.
2) navigate to the editor panel for the dashboard filters widget.
3) add some dashboard filters.
4) navigate back to the dashboard panel.
5) delete the dashboard filters widget.
6) click to toggle the advanced editor
Expected: the sharedFilters under dashboard should be empty. The visualizations should be empty.

Fix/ [new-50345] unused dashboard filters

---

packages/chart/src/hooks/useScales.ts

Open Scatter Plot
Set axis to Categorical
dots(plots) should be properly aligned with ticks

FIX[DEV-10222] : Scatter plot plots alighment issue

---

packages/chart/src/components/LinearChart.tsx

Don't override yaxis max with auto padding if max is set.
Create a chart using "only show top suffix/prefix", set a max for the y-axis, ensure that it's not overridden by automatic padding.

Fix [NEW-50348] Don't calculate auto padding if yaxis max is set

---

packages/core/helpers/isRightAlignedTableValue.js

Don't right-align columns formatted like dates, such as 2024-01-12.
Create a chart with dates like "2024-01-12", ensure that they are left-aligned in the data table.

Fix [DEV-10399] Don't consider dates to be numbers for table alignment

---

packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx

Open Dashboards
Create 2 viz : Markup Include & Filters
On Markup Include update title "Custom title"
on the filters see two dropdowns "setby" "usedBy" these drop downs should show updated title of the component.
Before: it used to show viz key "markup-include9429829024" even after title update.

FIX:[DEV-10302a] Fix Markup-Include title with Filters

---

packages/core/components/DataTable/DataTable.tsx
packages/core/components/DataTable/components/ChartHeader.tsx
packages/core/components/DataTable/helpers/getChartCellValue.ts
packages/core/components/DataTable/helpers/getDataSeriesColumns.ts
packages/core/helpers/pivotData.ts
packages/core/helpers/tests/pivotData.test.ts

Scenario: Load storybook and navigate to Pages/Dashboard/Pivot Filter. Toggle the Edit mode.
1) Click the tools icon to edit the data table.
2) Make sure to select some values from the multi select panel.
3) Under columns add a column configuration.
4) Select Age-adjusted Rate.
5) Increase the Round to 1.
Expected: the values in the table should show a decimal place.

Fix [new-50356] data table pivot rounding

---

packages/chart/src/components/LineChart/components/LineChart.Circle.tsx

Scenario: upload https://cdc.sharepoint.com/teams/OADC-DPA-DMB-WCMS-TPVisualizationsProject/_layouts/15/download.aspx?UniqueId=8235bee51f5f4d36ba6feb00fa34369c&e=vle37l and open the Dashboard Preview
Expected: There is a Line Chart with multiple lines. There is also individual points for both Am/Alaskan Native and Black, non-Hispanic data. These points are the same sizes of each other but, are bigger than the points on the lines of the chart.

Fix: NEW-50362 Data value dots vary in size on dynamic series line charts

---

packages/core/components/DataTable/DataTable.tsx
packages/core/components/DataTable/helpers/mapCellMatrix.tsx

upload: 
[explore-by-location-pre-prod.json](https://github.com/user-attachments/files/19370734/explore-by-location-pre-prod.json)
1) make the following selections: Nationwide, CA, Health Care Access/Coverage, Last Checkup, 2023, About how long has it been since you last visited a doctor for a routine checkup?, race/ethnicity.
2) scroll down to last chart and toggle the table visualization.
3) click download csv.
Expected: you should get a csv with a Response_Filter column. The column should show the same selection repeated.

Enhancement fix/[dev-10412] csv download viz filter column added

---

packages/chart/src/components/LinearChart.tsx
packages/chart/src/helpers/sizeHelpers.ts

Issue where chart jitters when opening (caused by padding being constantly changes)
1. open http://localhost:6006/?path=/story/components-templates-chart-axis-labels--abbreviated-dates
2. confirm that it doesn't "jitter" resizing on open 

fix [auto right padding]: auto padding issue

---

packages/core/components/Filters/helpers/handleSorting.ts

Scenario: Upload [dev-10566.config.json](https://github.com/user-attachments/files/19470901/dev-10566.config.json) and open the Configuration Tab
1. Choose the Explore by Indicator tab
2. Scroll down to the Row 3, the second set of filters, and click on the tools menu to open the filters
3. Click on Filters from the left menu
4. Open the Breakdown filter and scroll down to Parent Filters
5. Add Population Survey, Topic or MPower, Indictor and Who Region and close the Breakdown filter
6. Open the Breakdown Detail filter just below the Breakdown filter
7. Add Population Survey, Topic or MPower, Indictor, and Who Region. It already has Breakdown selected and please leave that there.
8. Click OK at the bottom and then Save.
9. Reopen to check to see of the Parent Filter settings saved as they …

Hot Fix/Dev-10566 Parent Filters are not saving Sorting issue

---

packages/map/src/components/UsaMap/components/UsaMap.State.tsx

State labels were missing on state maps:
While viewing a standalone map:
- Open Type > Show State Labels
- Under Visual > Make the map dark
- Verify the black color shows out in the ocean
- Switch to Type > Display as hex map
- Make sure white shows on dark hex tiles

[DEV-50379] fix state labels

---

packages/chart/src/components/AreaChart/components/AreaChart.jsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/hooks/useRightAxis.ts
packages/chart/src/hooks/useScales.ts

upload:
[dev-10534-download-image.json](https://github.com/user-attachments/files/19391282/dev-10534-download-image.json) and navigate to dashboard preview.
1) click download image:
Expected: you should get an image download with none of the visualization cut off.
2) navigate to the chart editor and switch the legend from bottom to right.
3) click download image.
Expected: visualization shouldn't be cut off

Fix [dev-10534] download image cutting

---

packages/core/components/DataTable/components/MapHeader.tsx
packages/map/src/components/EditorPanel/components/EditorPanel.tsx
packages/map/src/data/initial-state.js
packages/map/src/types/MapConfig.ts

Open Maps
Under Data table panel added new "Table Cell Min Width" 
It is used to have for charts and now Maps support.
See attached image: 

Feature: [DEV-50383] - Add Table Cell Min Width for Maps

---

packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/helpers/dataHelpers.ts

fix issue with dynamicCategory
1. open [oral-health-data.json](https://github.com/user-attachments/files/19474705/oral-health-data.json)
2. match these settings 
3. Confirm "Multicultural" does not exist in the legend
4. confirm other charts legends are showing properly

fix: dashboard dynamic category issue

---

packages/waffle-chart/src/CdcWaffleChart.tsx
packages/waffle-chart/src/components/EditorPanel.jsx
packages/waffle-chart/src/data/initial-state.js
packages/waffle-chart/src/types/Config.ts

Open Waffle Chart
on General Panel added new checbox to control title hide/show
See Below image 

Feature: [NEW-50358] Add Show Title feature to Waffle Chart

---

packages/core/components/DownloadButton.tsx

Scenario: upload 
[adhap-test.json](https://github.com/user-attachments/files/19492082/adhap-test-test_1.1.1.1.json) and navigate to dashboard preview.
1) Select: Northeast, Caregiving, Duration of Caregiving Among older adults 
2) View "Trends over Time" line graph -- select "All Available" Age Groups and "Overall-Overall" in the Demographic dropdown
3) Go to table view (via toggle)
Expected: symbol renders properly in table.
4) Click "Download Data (CSV)" 
5) View downloaded file. 
Expected: See the superscripted symbol "~~" in the download render Properly

fix [dev-10553] csv special chars

---

packages/dashboard/src/components/DataDesignerModal.tsx
packages/dashboard/src/store/dashboard.actions.ts
packages/dashboard/src/store/dashboard.reducer.ts

Delete the dataKey from the Vizualizations in a row if the Row is given a dataKey
Scenario: upload [dev-50360-config.json](https://github.com/user-attachments/files/19291987/dev-50360-config.json) and open the Configuration tab
Expected: There is a Row with a table widget in it.
1. Click on the Widgets gear icon and choose a dataset
2. Click Vertical, No, and then Continue
3. In the Editor panel on the left, scroll all of the way down click Advanced Options
Expected: The Advanced Options menu will open and there will be a list of properties with arrows next to them. The two main properties to look at are rows and visualizations. In visualizations under table1741961876645, there will be dataKey: "valid-data-chart.csv"
4. Leave the Advanced Options open
5. Click on the 3 gears icon on the …

Enhancement: New 50360 Widgets having datasets when in a Row with a dataset causing config issues

---

packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/index.jsx
packages/dashboard/src/index.tsx
packages/data-bite/src/index.jsx
packages/editor/src/index.jsx
packages/filtered-text/src/index.jsx
packages/map/src/index.jsx
packages/markup-include/src/index.jsx
packages/waffle-chart/src/index.jsx

This imports CSS before components in all packages. It makes it possible to use css variables anywhere in the codebase, [like here](https://github.com/CDCgov/cdc-open-viz/blob/dev/packages/core/helpers/constants.ts#L3).
Run the map package locally. The default map does not work in `dev`, but works in this branch.

Fix [NEW-50385] Swap css/component import order

---

packages/core/helpers/pivotData.ts
packages/core/helpers/tests/pivotData.test.ts

Under the Never Pivot column there were missing Ethnicities and they were out of order. 
Scenario: Upload [new-50380.config.json](https://github.com/user-attachments/files/19474985/new-50380.config.json) and open Dashboard Preview
Expected: A row of Filters
1. 1st Row Dashboard filters selected:
Dataset: Nationwide
Location: State-California
Class: Health care access
Topic: Last checkup
Question Year (Labeled as Year): 2022
Question: The only question that would show.
2. Click View Results
Expected: 2 more filters appear
3. 2nd Row Dashboard filters selected:
View By: Race / Ethnicity
Expected: The Chart below the filter will populate data
4. Click the Table toggle button
Expected: Under each pivot category the Categories below will be there and in order. Double check "Never" since this …

Fix: NEW-50380 Data Table: Add order column configuration

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/Legend/Legend.Component.tsx
packages/chart/src/helpers/dataHelpers.ts
packages/chart/src/types/ChartConfig.ts
packages/core/helpers/coveUpdateWorker.ts
packages/core/helpers/ver/4.25.4.ts
packages/core/helpers/ver/tests/4.25.4.test.ts

Only show legend items with data.
open line chart with multiple legend items
activate filter that has on results for series or remove data for a series
confirm there is no legend item for series without data

feature [new-50339]: only show legend items with data

---

packages/dashboard/src/components/Row.tsx

---
name: Unable to determine the row number without counting
about: 
---
Moved the row label out from behind the Visualization
Scenario: upload [NEW-50364-config.json](https://github.com/user-attachments/files/19668238/NEW-50364-config.json) and open the Configuration tab.
Expected: There are 4 rows and the row are labeled with Row - {row number}

Enhancement/NEW-50364 Unable to determine the row number without counting

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
packages/chart/src/data/initial-state.js
packages/chart/src/types/ChartConfig.ts

Scenario: Upload [NEW-50376-config.json](https://github.com/user-attachments/files/19450425/NEW-50376-config.json), open the Configuration tab, and click on the tools icon on the Line Chart Visualization
Expected: The line chart Editor opens with a line chart with Isolated Dots off of the lines. These Isolated Dots are larger then the dots on the lines.
1. Open the Visual accordion 
2. Uncheck the Enlarge Isolated Dots toggle
Expected: The Isolated Dots are now the same size as the Dots on the lines.

Fix/NEW-50376 Data value dots vary in size on dynamic series line charts

---

packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/APIModal.tsx
packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx

Added type="text" to inputs to make the text boxes have the correct styling
Scenario: Upload [NEW-50375-config.json](https://github.com/user-attachments/files/19448884/NEW-50375-config.json), open the Configuration Tab, and click on the tools icon on the top Filter Dropdowns widget.
Expected: Dashboard Filters Editor opens with 2 filters: Location and Time Period
Open the Filters Accordion tab and open the Location filter
Scroll down to the gray area that has the API Endpoint
Click on the Edit API Values button.
Expected: A module pops up with 3 text inputs: API Endpoint, Value Selector, and Display Text Selector
Change the text in the boxes
Then click the Save button
Expected: The values in the gray box will reflect the changes made in the module.
Scroll up to Filter Style and change it …

Enhancement/Fix: NEW-50375 API sourced dashboard filters editor difficult to work with

---

packages/chart/src/components/LinearChart.tsx

This PR fixes a bug where the "manual ticks" option sometimes resulted in missing x-axis ticks.
The attached config will be missing x-axis ticks on `dev` but will show them on this branch.
[trends-nhsn-broken2.json](https://github.com/user-attachments/files/19782767/trends-nhsn-broken2.json)

Fix [NEW-50395] Fix missing x-axis ticks

---

generateViteConfig.js

We have a separate project where we're including COVE on a page locally like this:
```
<div class="react-container" data-config="/bird-flu.json"></div>
<script type="module" src="http://localhost:8080/src/index.tsx"></script>
```
Adding this header makes it possible.
Run COVE locally, ensure it still works.

Enhancement [NO TICKET] Add dev origin header

---

packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.StackedHorizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
packages/chart/src/components/BarChart/components/BarChart.tsx
packages/chart/src/components/BarChart/components/context.tsx
packages/chart/src/components/BarChart/helpers/useBarChart.ts
packages/chart/src/components/EditorPanel/useEditorPermissions.ts

Tool tips were not working on horizontal bar charts which were using a toggle in dashboard on the initial render. I tracked that down to an issue with two separate mouse event handlers in different hooks. I combined the handlers in the useBarChart hook so that they are both called together. 
upload: 
[new-50398-tooltip.json](https://github.com/user-attachments/files/19851589/new-50398-tooltip.json)
1) navigate to preview page.
2) toggle the bar chart.
3) hover over one of the bars.
Expected: you should see a tooltip with corresponding information.

Fix/ [NEW-50398] tooltips horizontal bar charts

---

packages/chart/src/CdcChartComponent.tsx

Added file to test it on Dashboards.
Whole logic behind this fix is : when we are on Dashboards and add data description the CdcChart component was not adding transform.developerStandardize(newData, newConfig.dataDescription) and also dashboard also was not adding transform.developerStandardize(newData, newConfig.dataDescription) on first render. This fixes issue but may or may not create issue for other charts as dependency was changes on useEffect. i did test multiple files and seems working.
[dev-10586-rebuild.json](https://github.com/user-attachments/files/19985906/dev-10586-rebuild.json)

FIX: [DEV-10586a] Update prepareData and useEffect

---

.eslintrc.json
.github/workflows/lint_staged.yml
.husky/pre-commit
.prettierignore
package.json
yarn.lock

This pull request introduces several changes aimed at improving code quality, enforcing consistent formatting, and enhancing the development workflow. The most significant updates include configuring ESLint and Prettier plugins, adding a GitHub Actions workflow for linting staged files, setting up Husky for pre-commit hooks, and updating dependencies to their latest versions.
* Updated `.eslintrc.json` to include the `eslint-plugin-prettier` plugin, enforce stricter rules (e.g., treating `no-console` and `no-debugger` as errors), and disable the `react-hooks/exhaustive-deps` rule.
* Adjusted the order of lint-staged commands in `package.json` to run ESLint before Prettier.
* Added a GitHub Actions workflow (`.github/workflows/lint_staged.yml`) to lint staged files on pull requests, …

[eslint]: add husky/eslint check pre-commit hook and linting workflow

---

packages/chart/src/_stories/_mock/dynamic_series_bar_config.json
packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.StackedHorizontal.tsx
packages/chart/src/components/BarChart/components/context.tsx
packages/chart/src/components/BarChart/helpers/getBarHeights.ts
packages/chart/src/components/BarChart/helpers/tests/getBarHeights.test.ts
packages/chart/src/components/BarChart/helpers/useBarChart.ts
packages/chart/src/components/LinearChart.tsx
packages/chart/src/hooks/useTooltip.tsx

upload:
[new-50398-tooltip.json](https://github.com/user-attachments/files/19851589/new-50398-tooltip.json)
navigate to preview page.
toggle the bar chart.
hover over one of the bars.
Expected: you should see a tooltip with corresponding information.
*Single and Multiple series tooltips should work for dynamic data series.

fix-2 [new-50398] single/multiple series issues

---

packages/core/helpers/isRightAlignedTableValue.js

Adds `<` and `>` to regex for determining data table column alignment.
Create a data table with `<` in a column, ensure that it's right-aligned.

Fix [DEV-10399] Add more characters to data table alignment

---

packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
packages/chart/src/components/LineChart/index.tsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/hooks/useTooltip.tsx

Hovering over data points show tooltip for specific data point
Scenario: Upload [NEW-50393-config.json](https://github.com/user-attachments/files/19980751/NEW-50393-config.json), open the configuration tab, and then click the tools icon on the Line Visualization.
Expected: A Line Chart with multiple lines and isolated points
1. Hover over any point
Expected: The tooltip shows with the correct information for all data on the x-Axis.
2. Open the Visual accordion on the left 
3. Test that hovering displays tooltip for all options of the following:
a. Line Datapoint Symbols
b. Line Datapoint Style
c. Line Datapoint Color
Expected: The tooltip shows with the correct information for all data on the x-Axis
4. In the Visual accordion, scroll down to the Show Hover for single data series
5. Click …

Enhancement: NEW-50393 Line Chart Tooltip Enhancement

---

packages/chart/src/types/ChartConfig.ts
packages/core/components/Legend/Legend.Gradient.tsx
packages/map/src/_stories/CdcMap.Legend.Gradient.stories.tsx
packages/map/src/components/EditorPanel/components/EditorPanel.tsx
packages/map/src/hooks/useLegendSeparators.ts
packages/map/src/types/MapConfig.ts

Option to allow the adding of spaces between linear block gradient legend items 
1. Create of view map with gradient linear block legend in editor
2. Add comma separated number to "Legend Spaces" field 
3. Observe legend has spaces with dotted line after specified legend items
http://localhost:6006/?path=/story/components-templates-map-legend-gradient--gradient-with-space

feature: legend block spaces

---

packages/core/components/DataTable/DataTable.tsx
packages/core/components/Table/components/Row.tsx

This issue is happening on production, so for local we cannot test it. here is the link for prod :https://wwwdev.cdc.gov/nwss/rv/COVID19-currentlevels.html
Issue is overlap for table cells as shown in the image :

FIX : [DEV-50354] - Fix table cell overlap issue

---

packages/map/src/_stories/CdcMap.stories.tsx
packages/map/src/components/EditorPanel/components/EditorPanel.tsx

When legends are set to equal number the numbers shouldn't repeat, ie [10-11, 11-12, 12-13]. Instead they should start at the next number [10-11, 12-13, 14-15]
- Open story: http://localhost:6006/?path=/story/components-templates-map--equal-number-map
- The legend items should repeat [12-40, 40-55]
- Under legend type > change the legend to equal interval, then back to quantile. They shouldn't repeat now.

[DEV-8148] fix: equal number opt in button

---

packages/core/components/Legend/Legend.Gradient.tsx

color var fallback for editor
'overflow-visible' not consistently working so adding explicit inline-style
needs to be tested on the wcms editor and dev page

fix: legend gradient minor fixes

---

packages/map/src/components/NavigationMenu.tsx
packages/map/src/helpers/titleCase.ts

Four issues with the Navigation Map
1) Select an Item - Change this to "Select a Location"
2) District Of Columbia - The "o" in District Of Columbia should be lowercase (District of Columbia)
3) The "Go" button is misaligned with the dropdown
4) The .csv doesn't work and isn't necessary - remove
Scenario: Upload [new-50438-config.json](https://github.com/user-attachments/files/20208989/new-50438-config.json) and open Configuration
Expected: There is a map of the US. At the bottom there is a drop down labeled "Select a Location", the Go button is aligned with the dropdown and there is no link to the csv.
1. Click on the dropdown
Expected: a list of states and the District of Columbia, where the "of" in DC is lowercased.

Fix/NEW-50438 Navigation Map Bugs/Improvements

---

packages/chart/src/_stories/Chart.CI.stories.tsx
packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx

Open Horizontal bars
Add CI
Add labels to the bars
Before: bar labels were overlapping with CI lines
After : bar labels are move to the right side of bar where CI lines overlap, if no overlap the bar labels stays on the middle
Added storybook scenaria as well  under Chart/Conficence Intervals/ bar_chart_horizontal_labels

FIX :[DEV-50389] Fix horizontal bar chart CI labels

---

packages/chart/src/CdcChartComponent.tsx

horizontal bar charts were toggling negative when you changed the labelOffset
1) Start storybook.
2) navigate to Templates > Chart > Dynamic Series > Bar Horizontal
3) toggle edit mode.
4) add a label
5) change the label offset
Expected: the label offset should respond with the value you are incrementing it to.

Fix [new-50440] Chart Horizontal Label Offset

---

packages/chart/src/CdcChartComponent.tsx
packages/chart/src/_stories/ChartPrefixSuffix.stories.tsx
packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/EditorPanel/useEditorPermissions.ts
packages/chart/src/components/Legend/helpers/index.ts
packages/chart/src/components/LinearChart.tsx
packages/chart/src/hooks/useTooltip.tsx
packages/chart/src/types/ChartConfig.ts
packages/core/helpers/cove/number.ts
packages/core/helpers/coveUpdateWorker.ts
packages/core/helpers/ver/4.25.6.ts
packages/core/helpers/ver/tests/4.25.6.test.ts
packages/core/types/Axis.ts

1. Allow resize of tooltip when necessary
2. Replaced left axis `suffix`+ `onlyShowTopPrefixSuffix` with inlineLabel
3. Added migration script for change 2.
4. Remove the now-called inlinedLabel from tooltip
Test for change 1.
1. Open chart with tooltip
2. Change to mobile view or shrink screen <350px
3. Confirm tooltip resizes instead of overflowing
Test for change 2.
1. Open chart in editor
2. Confirm inlineLabel is available and behaves like a suffix that only appears on top axis gridline and is allowed to overflow if label contains spaces
3. Confirm `onlyShowTopPrefixSuffix` is removed and `suffix` behaves normally
Test for change 3.
1. Open config with `suffix`+ `onlyShowTopPrefixSuffix`
2. Confirm that it behaves the same way and now show a populated `inlineLabel` in the editorf …

Enhancement [NEW-50450] dynamic tooltip inline title

---

packages/core/helpers/ver/4.25.3.ts

For legacy configurations the CSV download links disappeared in some cases after the 2.25.5 release. This was due to a migration error.
https://www.cdc.gov/maternal-mortality/php/pregnancy-mortality-surveillance-data/index.html?cove-tab=1 this page should have download links under all the tables.

fix chart csv download

---

packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx

Tooltips stop working if Dynamic Category is changed back to '- Select -'
Scenario: Upload 
[tooltips-dynamic-category.config.json](https://github.com/user-attachments/files/20353897/tooltips-dynamic-category.config.json) and open, configuration tab, and click on the tools icon on the bar graph visualization
Expected: There is a bar graph with all 50 states and the tooltip appears if you hover any of the bars. 
1, Open the Data Series accordion
2. Open Rate
3. Change Dynamic Category to Select
4. Hover over the bars in the chart
Expected: Tooltip displays with data about the state
Actual: No Tooltip is displayed

Fix [new-50449] tooltips dynamic series chart

---

packages/core/components/Filters/components/Dropdown.tsx

!important doesn't take in react inline styles
Open dropdown with iphone emulator and confirm it is white

fix: inline-style not taking

---

packages/chart/src/scss/main.scss
packages/core/styles/_global.scss
packages/core/styles/filters.scss

Focus indicators should inherit from their wrapping container.

[NEW-50505] Fix/focus indicators

---

packages/core/helpers/ver/4.25.6.ts
packages/core/helpers/ver/tests/4.25.6.test.ts

Updater not working for dashboard
open [mhdc-flash.json](https://github.com/user-attachments/files/20778887/mhdc-flash.json) and confirm it has inline label

fix: inline label dashboard updater

---

packages/core/components/DataTable/helpers/mapCellMatrix.tsx
packages/core/types/Table.ts
packages/map/index.html
packages/map/src/CdcMapComponent.tsx
packages/map/src/_stories/CdcMap.Table.stories.tsx
packages/map/src/_stories/_mock/default-patterns.json
packages/map/src/components/EditorPanel/components/EditorPanel.tsx
packages/map/src/helpers/generateRuntimeData.ts
packages/map/src/helpers/generateRuntimeLegend.ts

option to not filter non geo data rows
1. Open map with non-geographic data
2. Check "showNonGeoData" in the Data Table section
3. Confirm that data shows up
http://localhost:6006/?path=/story/components-templates-map-table--show-non-geo-data

feature: [DEV-10997] option to not filter non geo data rows

---

packages/chart/src/components/EditorPanel/useEditorPermissions.ts
packages/chart/src/components/LinearChart.tsx

Fix tooltips for single series.
It was working wrong and always showing all tooltips even if checkbox wa clicked.

FIX : [DEV-10707 ] -Show Hover for Single Data Series is not working for stand-alone Horizontal Stacked Bar

---

packages/chart/src/components/Legend/Legend.Suppression.tsx
packages/chart/src/hooks/useTooltip.tsx
packages/core/components/DataTable/helpers/getChartCellValue.ts
packages/core/helpers/cove/number.ts

Fixed Tooltips to show only percentage values if user selects "show data value " checkbox
else shows two values : original data value and calculated percentage
Added data table default % sign all times.

Fix : [DEV-10945] Fix Pie Chart Tooltips and Data Table

---

packages/chart/src/hooks/useScales.ts

Fixed scales for area chart to remove padding when axis is categorical or Date type.

Fix Area chart scales

---

packages/chart/src/components/EditorPanel/EditorPanel.tsx
packages/chart/src/components/LineChart/helpers.ts
packages/chart/src/types/ChartConfig.ts
packages/core/helpers/coveUpdateWorker.ts
packages/core/helpers/ver/4.25.7.ts

This allows the user to associate line effects with multiple series instead of just one series. 
Load [multiple-dashed-lines.json](https://github.com/user-attachments/files/20909695/multiple-dashed-lines.json) locally in the chart package.
In the editor, go to [Data Series -> Effect Data] and associate the existing dashed line effect with multiple series. (Careful, you have to click on the down arrow on the dropdown, otherwise it thinks you're deleting the last selected value.)
In the grey area on the chart, you will see a dashed line for each series you've selected. You may have to show/hide some series to see it working. The dashed line item in the chart legend will appear only once.
If you go through the same process on the `dev` branch, you will only be able to associate the dashed …

Feature [DEV-10991] Multiple series

---

packages/chart/src/components/LinearChart.tsx
packages/chart/src/helpers/countNumOfTicks.ts

This improves tick generation for y-axes with small numbers by doing two things:
1. The number of ticks is no longer set to two
2. The number of decimal points visible in the y-axis respects the value in the "round to decimal point" option
Load [small-numbers.json](https://github.com/user-attachments/files/20909265/small-numbers.json) locally in the chart package.
On the `dev` branch, there will be two ticks on the y-axis, on this branch there will be more. If you change the [Left Value Axis => round to decimal point] option, the ticks will match the desired rounding on this branch, but will always show one decimal on the `dev` branch.

Fix [DEV-10990] Improve tick generation for y-axes with small ranges

---

packages/chart/src/_stories/Chart.tooltip.stories.tsx
packages/chart/src/_stories/_mock/bar-chart-suppressed.json
packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx

Open Bar Charts regular
Add Suppresseed data or if there is missing data value like "ABC"
Turn on "Show missing data value label " from General panel
Turn on "Show Simgle series tooltips" from Visual Panel
Hover to the short bar that is missing.
Increased hover area so hovering over the bar will show tooltip.
Added new story under Charts/Tooltips/Increaed Tooltips

FIX : [DEV-10723] -Increase target size for N/A hovers

---

packages/chart/src/components/AreaChart/components/AreaChart.Stacked.jsx
packages/chart/src/components/LinearChart.tsx
packages/chart/src/helpers/filterAndShiftLinearDateTicks.ts
packages/chart/src/hooks/useScales.ts

Adjusted scales for Area chart to remove padding from both sides of the chart when axis type is 'date' or 'categorical'
To test : open area chart and switch to categorical axis or date and there should not be any paddings
here is example image :

FIX: [DEV-10704] - Adjust Area Chart Scales for date & categorial axis

---

packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx

Open Horizontal Bar charts
Add CI keys
Add bar labels
The bar labels should be on the left(start) of each bar escaping the CI lines

FIX : [DEV-10672] - Fix Horizontal bar chart labels with CI keys

---

packages/map/src/_stories/CdcMap.stories.tsx
packages/map/src/_stories/_mock/floating-point.json
packages/map/src/components/Legend/components/Legend.tsx
packages/map/src/helpers/applyColorToLegend.ts
packages/map/src/helpers/applyLegendToRow.ts
packages/map/src/helpers/generateRuntimeLegend.ts
packages/map/src/types/runtimeLegend.ts

* [DEV-11002]: On maps with filters color palettes generated wrong colors after filtering.
* [DEV-11094]: In certain situations bins had floating point artifacts which caused colors to not be colored in. ie. 35.800000004 instead of 35.8
* [DEV-11093]: When legend > separate zero was checked and use new quantile legend was being used, bin numbers were repeated, ie. 0, 1-10, 10-12 instead of 0, 1-10, 11-12
* [DEV-11095]: When special class was toggled to the end of the legend area the colors were displaying wrong, ie white instead of the first color in the color palette.
* [DEV-11096]: When special classes were set to show last, toggling the special class toggled the first color on the map instead of the special class.

[DEV-11002] Multiple Map Legend Color Fixes

---

packages/core/helpers/isRightAlignedTableValue.js

This considers falsey values (e.g. `0`) to be right-alignable in data tables. 
Check data tables in storybook, make sure they are right-aligned appropriately.

Fix [DEV-10399] Consider falsey values to be right-alignable

---

packages/chart/src/components/Forecasting/Forecasting.jsx
packages/chart/src/hooks/useScales.ts

Open Forecasting chart by uploading this provided config file
Before: the chart had grouped chunks
Now : forecasting chart is connected and also CI upper and lower still visible
Also check for axis offset aligment. ticks and chart should start at the same level without offset for both area and foreacsting
[forecasting.json](https://github.com/user-attachments/files/21304080/forecasting.json)

FIX : [DEV-10704]  Fix Forecasting and Area chart offset

---

packages/core/components/DataTable/DataTable.tsx
packages/core/components/DataTable/helpers/customSort.ts

Currently, when sorting, if there is one falsey value a zero is being returned no matter which value is falsey - which effectively leaves them in place
I believe empty strings/ values should always be sorted to the bottom, even when sort order is descending
1. Open 
[test.json](https://github.com/user-attachments/files/21414210/test.json) in map package
2. Sort the "Reason For N/A" column
3. Confirm normal sorting works and strings are sorted to the bottom

Fix [sorting] empty string sort

---

packages/chart/src/components/Forecasting/Forecasting.tsx
packages/chart/src/helpers/getBridgedData.ts
packages/chart/src/helpers/tests/getBridgedData.test.ts
packages/core/types/ForecastingSeriesKey.ts
packages/core/types/Runtime.ts

Fixed forecasting chart colors (segmented colors) and also connected segments using helper function getBridge data.

FIX [ DEV-11138] Fix Forecasting Chart colors

---

packages/dashboard/examples/no-data-markup.json
packages/markup-include/src/CdcMarkupInclude.tsx
packages/markup-include/src/components/EditorPanel.tsx
packages/markup-include/src/data/initial-state.js
packages/markup-include/src/types/Config.ts

Adds a checkbox for stating "No Data Available" when the markup include has nothing to show.
Open the attached example `no-data-markup.json` and change the filter to something that doesn't match.

Markup Inc. > No Data Message Enhancement

---

packages/chart/src/data/initial-state.js
packages/core/components/DataTable/DataTable.tsx
packages/core/components/DataTable/components/ExpandCollapse.tsx
packages/core/components/EditorPanel/DataTableEditor.tsx
packages/core/styles/_button-section.scss
packages/core/types/Table.ts
packages/map/src/data/initial-state.js

Add control to collapse long data tables from the bottom
*Only shows on charts with at least 20 rows
1. Open Viz with data table
2. Check `SHOW COLLAPSE BELOW TABLE`
3. Expand data table
4. Confirm collapse button shows at bottom of table
http://localhost:6006/?path=/story/private-respiratory-virus--all-configs

Feature [DEV-11034] Add control to collapse long data tables from the bottom

---

packages/core/components/MediaControls.jsx

On charts without a title we need padding added around the screenshot
- On a chart add the download image button and hide the title. 
- Click "Download Image" button
- The downloaded screenshot should have 35px of padding

enhancement: add padding on screenshots when title isn't present

---

packages/map/src/CdcMapComponent.tsx
packages/map/src/components/EditorPanel/components/EditorPanel.tsx
packages/map/src/components/Modal.tsx
packages/map/src/data/initial-state.js
packages/map/src/scss/main.scss
packages/map/src/types/MapConfig.ts

This PR removes the automatic capitalization functionality from map tooltips and modals in the COVE map
component. The changes eliminate the capitalizeLabels configuration option and related UI controls, removing
automatic text transformation that was previously applied to tooltip content.
- Removed capitalizeLabels configuration: Eliminated the capitalizeLabels boolean property from tooltip
configuration in MapConfig.ts and initial state
- Updated tooltip rendering: Removed conditional CSS class application that added capitalize styling to
tooltips in CdcMapComponent.tsx
- Cleaned up modal styling: Removed capitalization logic from modal content rendering in Modal.tsx
- Removed editor controls: Eliminated the checkbox control for "Capitalize text inside tooltip" from the map
editor panel …

[DEV-11204] Remove auto capitalizing

---

packages/chart/src/hooks/useTooltip.tsx
packages/core/helpers/cove/number.ts

Added default % suffix to the Pie Chart Data table
If % added by user it will not add % by default
if user adds manual suffix the % will be replaced by users added suffix

Fix Pie Chart Data Table

---

packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
packages/chart/src/components/BarChart/helpers/index.ts

This sets a minimum height of 3px for non-zero bars in stacked bar charts.
Load [this config](https://github.com/user-attachments/files/21798880/vertical-bar-chart-stacked.json), see that a bit of bar is shown for 2015. Experiment with the `MIN_BAR_HEIGHT` variable, or by changing the data in the config.

Fix [DEV-11177] Also add min bar heights to stacked bars

---

packages/map/src/data/supported-geos.js

This changes the display name for CNMI from “Northern Marianas” to the official name of “Northern Mariana Islands”. 
Check [this storybook](http://localhost:6006/?path=/story/components-templates-map--standard-color-distributions-without-special-classes), see that the tooltip and data table display "Northern Mariana Islands".

Fix [DEV-11265] Northern Mariana Islands

---

packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
packages/chart/src/components/BarChart/helpers/index.ts

This sets a minimum height of 3px for non-zero bars in stacked bar charts.
This [dashboard config](https://github.com/user-attachments/files/22027120/stacked-bars.json) is the one that was causing an issue with the original PR and is now fixed.
Or, load [this config](https://github.com/user-attachments/files/21798880/vertical-bar-chart-stacked.json), see that a bit of bar is shown for 2015. Experiment with the MIN_BAR_HEIGHT variable, or by changing the data in the config.

Feature [DEV-11177] Add min heights to stacked bars

---

packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
packages/chart/src/components/BarChart/helpers/index.ts

Aligns the font size of suppressed bar labels to the rest of the new labels.
In this [chart config](https://github.com/user-attachments/files/22048319/bar-suppressed.json), see that the suppressed symbol sizes match the other labels.

Fix [DEV-11296] Suppressed bar label size

---

packages/chart/src/CdcChartComponent.tsx
packages/core/helpers/vegaAsyncLoader.ts
packages/core/helpers/vegaConfig.ts
packages/editor/src/components/ChooseTab.tsx
packages/editor/src/components/DataImport/components/DataImport.tsx
packages/map/src/CdcMap.tsx

This PR loads the vega libraries asynchronously instead of including them in the chart/map bundles. This means the libraries will only be loaded when the Vega feature is being used.
Run a build, make sure everything works, and a Vega chart can still be created using the "paste configuration JSON" box.

Refactor [DEV-10733] Load vega libraries async

---

package.json
packages/core/generateViteConfig.js
packages/core/package.json
packages/core/styles/_global.scss
packages/core/styles/base.scss
packages/core/styles/v2/components/button.scss
packages/core/styles/v2/components/editor.scss
packages/core/styles/v2/layout/_data-table.scss
packages/core/styles/v2/themes/_color-definitions.scss
packages/dashboard/src/scss/grid.scss
packages/editor/src/components/DataImport/components/data-import.scss
yarn.lock

This removes all the sass deprecation warnings from the console. Migrating to sass 2 and 3 will be a decent chunk of work, whenever they come out.
`lerna run --scope @cdc/dashboard start`no longer shows a bunch of warnings.

Fix: Sass warnings

---

packages/map/src/components/CityList.tsx
packages/map/src/components/UsaMap/components/UsaMap.County.tsx
packages/map/src/helpers/displayGeoName.ts

This PR addresses title case formatting issues in geocode and city map components to ensure consistent and proper display of geographic names.
CityList.tsx: Fixed title casing logic for city name display
UsaMap.County.tsx: Updated title case formatting for county names
displayGeoName.ts: Corrected title casing helper function for geographic name display

Fix title casing for geocode/city maps
