- packages/map/src/components/EditorPanel.js
Move Legend Type select input to Columns accordion, re-label as Data Classification Type
> WCMSRD-11415-data-type-usability

- packages/map/package-lock.json
- packages/map/package.json
- packages/map/src/CdcMap.js
- packages/map/src/scss/btn.scss
- packages/map/src/scss/map.scss
Resolve minor IE display bugs, set media download ui display as static, refactor saveAs function to support IE blob behaviors, remove unused package dependencies
> WCMSRD-11558-generate-image-pdf

- packages/map/src/components/DataTable.js
- packages/map/src/examples/default-usa.json
- packages/map/src/scss/map.scss
This commit is for WCMSRD-11498 and WCMSRD-11463
> Wcmsrd 11498

- packages/chart/src/components/LinearChart.tsx
Dates were being placed with scaleLinear which was changing the number of ticks and sometimes repeating them.
> changing xscale to be point based 

- packages/map/src/CdcMap.js
- packages/map/src/components/EditorPanel.js
- packages/map/src/components/Modal.js
- packages/map/src/components/Sidebar.js
- packages/map/src/components/Territory.js
- packages/map/src/components/UsaMap.js
- packages/map/src/components/WorldMap.js
- packages/map/src/data/initial-state.js
This was necessary as most of the developers on the project are unfamiliar with older, class based components. It brings the architecture more in line with Charts
> Update CdcMap to a functional component

- packages/data-bite/src/CdcDataBite.tsx
- packages/data-bite/src/components/EditorPanel.js
- packages/data-bite/src/scss/bite.scss
- packages/data-bite/src/scss/editor-panel.scss
Adjust image definitions and placement, move filters to Data section, refactor subtext display, connect fontSize state with other display styles.
> Date Bite Updates

- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/PieChart.tsx
> Pie Chart > add regular and donut pie chart variations

- packages/data-bite/src/CdcDataBite.tsx
- packages/data-bite/src/components/EditorPanel.js
- packages/data-bite/src/data/initial-state.js
Add Alt image options for static/dynamic images
> WCMSRD-12771-databite-conditional-img

- packages/chart/examples/case-rate-example-config.json
- packages/chart/examples/case-rate-example-data.json
- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/BarChart.tsx
- packages/chart/src/components/DataTable.tsx
- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/LineChart.tsx
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/components/PieChart.tsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/index.html
Add exclusionary options for categories and dates
> WCMSRD-12848-chart-data-exclusions

- packages/map/src/components/CountyMap.js
-Use a thin border when zoomed in on county maps
> Wcmsrd 13188

- packages/core/styles/_data-table.scss
- packages/map/examples/default-usa.json
- packages/map/src/CdcMap.js
- packages/map/src/components/DataTable.js
- packages/map/src/components/Sidebar.js
- packages/map/src/index.html
- packages/map/src/scss/main.scss
- Updates table sorting structure to match accessibility examples
- Updates skip components to show when focused
- Shows focus outline when tabbing on maps
> Maps > Datatable Accessibility Improvements

- packages/map/src/CdcMap.js
- should resolve #112, after recreating the example on my local I know longer receive the error.
> Issue > Should resolve 112

- packages/markup-include/src/CdcMarkupInclude.jsx
Update logic to resolve issues with parsed statements not properly being sent
> Markup Include > Resolve Improper Parsing

- packages/chart/src/components/LinearChart.tsx
Hide Axis should not hide whole axis instead it should hide only Line while Ticks and Labels are still visible unsless user hides them
> Chart > update hiding Axis to Hiding Line

- packages/core/styles/base.scss
- packages/core/styles/v2/layout/_component.scss
- packages/core/styles/v2/themes/_color-definitions.scss
- packages/data-bite/src/CdcDataBite.tsx
- packages/data-bite/src/components/EditorPanel.js
- packages/data-bite/src/data/initial-state.js
- packages/data-bite/src/scss/bite.scss
- packages/data-bite/src/scss/main.scss
- packages/waffle-chart/src/CdcWaffleChart.tsx
- packages/waffle-chart/src/components/EditorPanel.js
- packages/waffle-chart/src/data/initial-state.js
- packages/waffle-chart/src/scss/waffle-chart.scss
Hey @rshelnutt -
Just wanted to loop you in on this update since there were scss changes. Feel free to push back on anything you see that's not fitting in. It won't be 100% complete, because we're in the middle of your refactor, but I did try to use `cove-component__header` and `cove-component__content` in the files and then checked the packages to make sure they were still working.
> Wcmsrd 13168

- prepare-commit-msg
- Uses WCMS pre commit hook
- Is Opt In
- Will take the feature name, ie feature/WCMSRD-12345 and update the commit message:
[WCMSRD-12345] last commit
[WCMSRD-12345] middle commit
[WCMSRD-12345] first commit
> Add prepare-commit-msg hook

- packages/core/components/inputs/InputSelect.jsx
- packages/waffle-chart/src/components/EditorPanel.js
- packages/waffle-chart/src/scss/waffle-chart.scss
- It appears some styles went missing in the Waffle Chart Editor panel. This is a patch to fix that.
> [wcmsrd-14492b] Style changes for release

- packages/map/src/CdcMap.js
Resolves DEV-907:
- Issue with thousand separator commas, and rounding
- Resolves issue with improper legend displays/groupings/values
- Reformats Maps code to proper standards
> [Dev 907] Maps - Thousand Separators, Rounding, Legend Issues

- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/data/initial-state.js
Added a function to calculate number of ticks on X and Y axis by default or when user enter manually.
[DEV-779](#!)
> Chart>  add tickCount function

- packages/chart/src/components/LineChart.tsx
> [line-null-issue] line gap fixes for null values

- packages/map/src/CdcMap.js
> Fixes Role Warning in Axe

- packages/chart/src/components/BarChart.tsx
> Reverses Data Series Order

- packages/map/src/components/UsaMap.js
> Fixes Territory Label Color

- packages/chart/src/components/BarChart.tsx
- packages/chart/src/components/LineChart.tsx
> Fixes Series Labels in Tooltip

- packages/filtered-text/src/CdcFilteredText.tsx
Fixed Filtered text component so it works properly with Dashboard filters.
> [DEV-1713b] fix filtered text

- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/components/PieChart.tsx
- packages/chart/src/components/useIntersectionObserver.tsx
- packages/chart/yarn.lock
> adding animation functionality to test

- packages/core/components/managers/DataDesigner.jsx
- packages/core/helpers/DataTransform.js
- packages/editor/src/scss/main.scss
> Allows Selecting Multiple Value Columns

- packages/chart/src/components/BarChart.tsx
- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/LineChart.tsx
- packages/chart/src/data/initial-state.js
> [tooltips] Fix tooltip errors

- packages/chart/src/components/LineChart.tsx
Fixed bug on tolltips. Removed ":" on Line charts if "Label"  && "LegendValue" doest not exist.
> [DEV-818c] Update axis formatting

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/Legend.js
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/scss/main.scss
Added "Label Offset" on horizontal charts , and Added dynamic space between Data table and chart using "Size" field on Value axis.
- [] CDC Internal Checks
> [DEV-2759] Add dynamic margin bottom to charts && labelOffset

- packages/chart/src/components/PieChart.tsx
- packages/chart/src/scss/main.scss
- [ X] My pull request was branched from and targets the test branch
- [ X] I have performed a self-review of my code
- [X ] I have manually tested all packages affected (bonus points for automations)
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] My changes generate no new warnings
- [X ] I have checked to ensure there aren't other open pull requests for the same change
- [X ] Standalone Component
- [ X] Standalone Full Editor
- [ X] CDC Internal Checks
> fix the height issue for pie chart and center on page

- packages/chart/src/components/Legend.js
> [4231-hotfixes] Legend: add bottom margin when in bottom position

- packages/chart/src/components/BarChart.tsx
- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/LineChart.tsx
> Makes Legend Values in Tooltips Optional

- packages/chart/src/components/LineChart.tsx
> Hides Line Labels if All Points Null

- packages/map/src/components/Filters.js
Fixes filter ordering from resetting when filter order changes.
> [DEV-2954] fix filtering from resetting

- packages/waffle-chart/src/CdcWaffleChart.jsx
> Fixes Load From URL Waffle Chart

- packages/chart/src/components/EditorPanel.js
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/data/initial-state.js
> [axis-padding] Add axis padding

- packages/chart/src/components/LinearChart.jsx
> [fix-hz] Fix horizontal height

- packages/chart/src/components/BarChart.jsx
- packages/chart/src/scss/main.scss
> adding animation for the horizontal stacked charts

- packages/dashboard/src/CdcDashboard.jsx
- packages/dashboard/src/components/DataTable.tsx
> Downloads Full Dataset Without Filters in Dashboards

- packages/chart/src/components/BarChart.jsx
Added format number for vertical bars values
> [DEV-3034] Add formatNumber for vertical bars values

- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/components/PairedBarChart.jsx
On Paired bar chart added room between bar and Left side axis.So bar does not touch axis anymore.
- [] CDC Internal Checks
> [DEV-2963] Add room between bar and Value axis

- packages/core/components/managers/DataDesigner.jsx
- packages/core/helpers/DataTransform.js
- packages/editor/src/scss/main.scss
> Fixes Merge Issues

- packages/chart/src/components/LinearChart.jsx
- packages/map/src/CdcMap.jsx
- packages/map/src/components/UsaMap.jsx
> Update Maps tooltips with cleanup from previous troubleshooting conflicts

- packages/chart/src/components/DataTable.jsx
- packages/core/components/ui/Icon.jsx
- packages/core/styles/_data-table.scss
- packages/dashboard/src/components/DataTable.tsx
- packages/map/src/components/DataTable.jsx
> Table Icon Fix

- packages/core/styles/_data-table.scss
> Small Cleanup

- packages/map/src/components/Filters.jsx
> [reset-filter-action] testing prevent default behavior on map filters

- packages/map/examples/default-geocode.json
- packages/map/examples/world-geocode-data.json
- packages/map/examples/world-geocode.json
- packages/map/index.html
- packages/map/src/CdcMap.jsx
- packages/map/src/components/CityList.jsx
- packages/map/src/components/CountyMap.jsx
- packages/map/src/components/EditorPanel.jsx
- packages/map/src/components/UsaMap.jsx
- packages/map/src/components/WorldMap.jsx
> [DEV-1721] add world geocode maps

- packages/core/styles/_global.scss
- packages/editor/src/components/DataImport.jsx
- packages/editor/src/scss/main.scss
Added or replace file button text that does the same as the RED Clear button right above it.
This required code to be added to DataImport.jsx as well as CSS edits to get the formatting and spacing correct.
Updated text to be slightly larger per feedback from Kayla
> DRAFT: Feature/dev 851 add replace file link import

- packages/core/components/hoc/Component.jsx
- packages/core/hooks/store/useSetConfig.js
- packages/core/hooks/store/useSetVizConfigDefaults.js
- packages/core/hooks/store/useVisualization.js
- packages/core/store/store.js
- packages/core/stores/multiStore.ts
- packages/markup-include/src/CdcMarkupInclude.jsx
- packages/markup-include/src/components/EditorPanels.jsx
- packages/markup-include/src/components/MarkupInclude.jsx
- packages/markup-include/src/data/initial-state.js
- packages/markup-include/src/useMarkupInclude.jsx
> wip try hook-based approach

- packages/chart/index.html
- packages/chart/src/components/EditorPanel.jsx
- packages/map/index.html
> [chart-load] chart not loading

- packages/map/src/components/CityList.jsx
> Fixes Crash When City Clickable

- packages/chart/src/components/BarChart.jsx
There was a bug, text was not fitting into the bar when we had horizontal stacked bars.
> [DEV-3511] fix small bug for text fitting

- packages/chart/src/components/BarChart.jsx
- packages/chart/src/components/LineChart.jsx
> Charts: Fixes Number Format on Labels and Tooltips

- packages/chart/src/scss/main.scss
- packages/core/components/Filters.jsx
- packages/map/src/scss/filters.scss
> [DEV-3506] adjust filter margins

- packages/map/src/components/CountyMap.jsx
> Fix Legend Click Behavior for Geocode Maps

- packages/chart/src/components/LinearChart.jsx
Added padding to axis when it has negative values.
> [DEV-3643] Add padding to value axis

- packages/map/src/CdcMap.jsx
> Fixes Color Switch Not Working in Maps

- packages/map/src/components/CountyMap.jsx
> Geo Code Fixes

- packages/chart/index.html
- packages/map/src/components/EditorPanel.jsx
> [filter-release] continue working on the filter issue

- packages/map/src/components/EditorPanel.jsx
Commented out "Show Special Classes Last" checkbox on Legen accordian in editor
and in CdcMap EditorPanel.
> [dev-784-correction] Fixed editor panel for maps

- packages/core/components/Filters.jsx
- packages/map/src/CdcMap.jsx
- packages/map/src/components/EditorPanel.jsx
> [filter-release] filters: fixing sorting

- packages/chart/src/components/DataTable.jsx
> [feature-2224] Remove duplicated data table caption

- packages/chart/src/components/EditorPanel.jsx
- packages/map/src/components/EditorPanel.jsx
> [resets-for-release] Add hidden items back in for 4.23.5

- packages/dashboard/src/CdcDashboard.jsx
> Hotfix Dashboard Filters

- packages/chart/examples/feature/__data__/planet-example-data.json
- packages/chart/examples/feature/__data__/planet-logaritmic-data.json
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/hooks/useMinMax.js
- packages/chart/src/hooks/useScales.js
Added new logic for min value input, cleanup up code, change tick lengths, cleanup data set from duplicate data
- [x ] I have performed a self-review of my code
> [DEV-2917]  Fix min value input & cleanup code

- packages/chart/src/CdcChart.jsx
> Fixes Chart Filter

- packages/core/data/colorPalettes.js
> [DEV-3370] Update two color palette

- packages/chart/src/components/BarChart.jsx
Changes bar  labels color to black.
> [DEV-4013] change bar text color

- packages/map/src/components/CountyMap.jsx
> Geocode Map: Hides Hover When City Hidden

- packages/chart/src/components/LineChart.jsx
Change label colors on Line charts.
> [DEV-4013a] Change label color

- packages/editor/src/components/DataImport.jsx
> Ensures Existing Data Always Shows Without Type

- packages/editor/src/components/DataImport.jsx
> Fixes Preview for Load by URL

- packages/chart/src/components/EditorPanel.jsx
- packages/map/src/components/EditorPanel.jsx
Fixed the CSS for help icons in dashboard so they dont appear large.
Tested every chart type although still possible I missed one.  Not a difficult fix if there is one I missed.
> DRAFT: Bugfix/dev 759 fix help icons

- packages/dashboard/src/CdcDashboard.jsx
> Hotifx Dashboard Filters

- packages/filtered-text/src/CdcFilteredText.jsx
removed redundant margin top on filtered text
> [DEV-4211] remove margin

- packages/chart/examples/feature/forecasting/forecasting.json
- packages/chart/index.html
- packages/chart/src/CdcChart.jsx
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/Forecasting.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/components/Series.jsx
- packages/chart/src/hooks/useMinMax.js
- packages/chart/src/hooks/useScales.js
> [DEV-2363] fixes standalone forecast charts

- packages/core/styles/v2/components/input/_input.scss
- packages/waffle-chart/src/scss/main.scss
> [DEV-810] resolve styling issues with wcms

- packages/core/components/DataTable.jsx
- packages/map/src/CdcMap.jsx
- packages/map/src/components/DataTable.jsx
- packages/map/src/components/EditorPanel.jsx
- packages/map/src/data/initial-state.js
Added checkbox to include FullGeoName or not on Maps CSV download.
Also Fixed State codes getting titleCased in the resulting CSV file by changing displayGeoName in maps to look for 2 character codes.
> [DEV-4251] Added checkbox to include FullGeoName and Fixed State codes getting titleCased

- packages/editor/src/components/ChooseTab.jsx
- packages/editor/src/components/ConfigureTab.jsx
- packages/waffle-chart/src/CdcWaffleChart.jsx
Bug fix on Waffle chart when user selects waffle on editor panel
> [waffle-chart] Fix bug on Waffle in Editor

- packages/chart/index.html
- packages/chart/src/components/DataTable.jsx
- packages/core/components/DataTable.jsx
- packages/core/helpers/cove/date.js
- packages/core/helpers/cove/number.js
- Format dates in vertical data
- Use the format number function to enable prefix/sufix
- Future: possibly use hooks or re-use new functions
> [DEV-4258] Resolve data table prefix and date formatting issues

- packages/chart/src/CdcChart.jsx
- packages/core/helpers/DataTransform.js
For Editor charts not using Dashboard, loadConfig is what fetches the url, so the code I had added before in remoteFetch also needed to be in the loadConfig code area.
> Bugfix/dev 4137 fix csv by url - part 2

- packages/map/src/components/CountyMap.jsx
> Fix for Highlighting With Multiple County Maps

- packages/waffle-chart/examples/example-config.json
- packages/waffle-chart/src/components/EditorPanel.jsx
- packages/waffle-chart/src/scss/waffle-chart.scss
Added error  handling style on select box and removed "waffle" text from chart.
> [DEV-2911b] Fix error style & title text

- packages/chart/examples/feature/forecasting/forecasting.json
- packages/chart/index.html
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/Forecasting.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/components/Series.jsx
- packages/chart/src/hooks/useMinMax.js
> [DEV-4321] Remove forecast stage column selector

- packages/map/src/hooks/useTooltip.js
> [tooltips] 4.23.7: update geolabel override

- packages/waffle-chart/src/data/initial-state.js
Updated the Title default name in initial state for waffle and Gaue charts.
> [DEV-2911c] Update default chart title

- packages/chart/src/CdcChart.jsx
- packages/chart/src/components/EditorPanel.jsx
> [DEV-4272b] Fix bug

- packages/waffle-chart/src/components/EditorPanel.jsx
Added dynamic logic to show Gauge chart features
> [DEV-2911d] add panel on Gauge chart

- packages/chart/src/data/initial-state.js
remove default responsive ticks state
- [] I have commented my code, particularly in hard-to-understand areas
> [fix-ticks] Change ticks

- packages/chart/src/components/LinearChart.jsx
Fixed ticks wrapping while they are not rotated
> [ticks-fix] update ticks

- packages/chart/src/components/LinearChart.jsx
> [fix-ticks-a] Fix ticks

- packages/chart/src/CdcChart.jsx
- packages/chart/src/components/AreaChart.jsx
Fixed bug on charts when we switch from Bar/Horizontal to Box Plot, Scatter Plot & Area Chart.
> [DEV-4756] Fix orientation bug

- packages/chart/index.html
- packages/chart/src/components/BarChart.jsx
- packages/chart/src/components/LinearChart.jsx
> [DEV-4651] additional working updateS

- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/hooks/useScales.js
Added proper error handling for Paired bar chart.
> [DEV-4759] handle errors for Paired abr chart

- packages/map/src/components/CountyMap.jsx
> Increases Zoom for Puerto Rico

- packages/chart/index.html
- packages/chart/src/components/BarChart.Horizontal.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/hooks/useMinMax.js
When useMinMax was refactored, an enable padding checkbox was added to Editor, but for CI data with negative values we must add padding no matter what in order for it to render properly.
> [DEV-4653-fix-CI-padding] Added CI for minimum values

- packages/map/examples/default-geocode.json
- packages/map/index.html
- packages/map/src/components/CountyMap.jsx
- packages/map/src/components/EditorPanel.jsx
> [DEV-4642] re-add county map pin styles

- packages/chart/src/components/BarChart.Horizontal.jsx
On horizontal/regular bars  labels on bars fixed.
> [DEV-5023] update bug for bar labels

- packages/chart/index.html
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/LinearChart.jsx
Removed brush for August production release
> [aug-release-brush-removed] Hotfix for production removed brush

- packages/chart/index.html
- packages/chart/src/components/LinearChart.jsx
> [vertical-anchor] fix vertical anchor positioning

- packages/chart/examples/feature/filters/bar-filter.json
- packages/chart/index.html
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/data/initial-state.js
- packages/core/components/Filters.jsx
> [DEV-3586] No data available message

- packages/chart/src/components/EditorPanel.jsx
Fixed bug for confidence keys when the keys be "upper" and "lower"
> [DEV-5056] Fix confidence keys bug

- lerna.json
- package-lock.json
- packages/chart/package.json
- packages/core/package.json
- packages/dashboard/package.json
- packages/data-bite/package.json
- packages/editor/package.json
- packages/filtered-text/package.json
- packages/map/package.json
- packages/markup-include/package.json
- packages/waffle-chart/package.json
- yarn.lock
Reverts CDCgov/cdc-open-viz#815
> Revert "Bump tough-cookie from 4.1.2 to 4.1.3"

- packages/map/src/CdcMap.jsx
fixed a bug for coloring the map for each single US state change
> [DEV-5070] Fix bug around coloring

- packages/dashboard/src/components/Widget.jsx
- packages/editor/src/CdcEditor.jsx
- packages/editor/src/components/DataImport.jsx
> Removes Extraneous Data From WCMS Config

- packages/chart/src/CdcChart.jsx
fix orientation issue for Line and Forecating charts.
> [DEV-5259] update to vertical Line and Forecasting charts

- packages/chart/src/components/EditorPanel.jsx
- packages/map/src/components/EditorPanel.jsx
> Re-enables Image Download for Chart and Map

- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/Legend.jsx
- packages/chart/src/data/initial-state.js
> [DEV-5217a] add lined style legend

- packages/waffle-chart/src/CdcWaffleChart.jsx
> [DEV-5266a] fix Gauge chart calculation bug

- packages/chart/src/hooks/useReduceData.js
> Fixes Chart Not Rendering When Series Value Missing

- packages/chart/index.html
- packages/chart/src/CdcChart.jsx
> [DEV-5295] fix intro text wrapping style

- packages/waffle-chart/src/CdcWaffleChart.jsx
fixed a bug for right calculation
> [hotfix-gauge] fix bug

- packages/core/components/DataTable.jsx
> [dataTable-sort] fix data table sort

- packages/chart/index.html
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/hooks/useLegendClasses.js
- packages/chart/src/scss/main.scss
- packages/core/helpers/useDataVizClasses.js
- packages/map/examples/default-usa.json
- packages/map/index.html
- packages/map/src/CdcMap.jsx
- packages/map/src/components/EditorPanel.jsx
- packages/map/src/components/Sidebar.jsx
- packages/map/src/data/initial-state.js
- packages/map/src/scss/sidebar.scss
> Legend ordering

- packages/editor/src/components/DataImport.jsx
> Allows Relative URL For Data Imports

- packages/core/components/MediaControls.jsx
> Fixes Foreign Objects Not Rendering in Image Download

- packages/dashboard/src/CdcDashboard.tsx
> Fix #849: added fix for generateValuesForFilter

- packages/core/components/Filters.jsx
> Accessibility Label Fix for Dropdowns

- packages/chart/index.html
- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/SparkLine.jsx
- packages/chart/src/hooks/useEditorPermissions.js
- packages/core/helpers/useDataVizClasses.js
> [DEV-5296] 4.23.10: spark line editor adjustments

- packages/dashboard/index.html
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/dashboard/src/_stories/_mock/api-filter-chart.json
- packages/dashboard/src/_stories/_mock/api-filter-map.json
> [DEV-5653] logi poc stories

- packages/core/components/DataTable.jsx
- packages/core/helpers/cove/date.js
Fixed sorting for Horizontal table
> [4242e] Update sorting for horizontal table

- packages/chart/src/CdcChart.tsx
> Fixes Stripped FormattedData Issues

- packages/chart/src/components/DeviationBar.jsx
> [update-import] Update import path

- packages/core/styles/_data-table.scss
Fixed horizontal table align rows
> [fix-table-align] fix table alignment

- packages/core/components/DataTable.jsx
> Fixes Sort Order

- packages/markup-include/src/CdcMarkupInclude.tsx
- packages/markup-include/src/_stories/MarkupInclude.stories.tsx
- packages/markup-include/src/store/mi.actions.ts
- packages/markup-include/src/store/mi.reducer.ts
- packages/markup-include/src/types/Config.ts
- Converts Markup Include to TypeScript
- Adds useReducer to Markup Include
> [PORT-134] Markup Include TS & useReducer

- packages/chart/src/components/BarChart.Horizontal.jsx
- packages/chart/src/components/BarChart.StackedHorizontal.jsx
- packages/chart/src/components/BarChart.StackedVertical.jsx
- packages/chart/src/components/BarChart.Vertical.jsx
- packages/chart/src/components/DeviationBar.jsx
- packages/chart/src/scss/main.scss
> Fixes Bars Not Showing in Firefox

- packages/chart/src/components/Legend.jsx
> [fix-legend] Fix legend margin

- packages/dashboard/src/CdcDashboard.tsx
Updated dashboard table settings.
> [dashboard-table] Update dashboard table settings

- packages/chart/src/_stories/Chart.tooltip.stories.tsx
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/hooks/useTooltip.jsx
Added Additional column tooltip
> [DEV-6020] Add Additional Tooltip cols

- packages/chart/index.html
- packages/chart/src/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart.StackedHorizontal.tsx
- packages/chart/src/components/BarChart.StackedVertical.tsx
- packages/chart/src/components/BarChart.Vertical.tsx
- packages/chart/src/hooks/useTooltip.jsx
- packages/chart/src/types/ChartProps.ts
- packages/dashboard/index.html
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/_stories/_mock/dashboard-filter.json
- packages/map/index.html
- packages/map/src/CdcMap.tsx
- packages/map/src/components/EditorPanel.jsx
- packages/map/src/hooks/useTooltip.js
- When dashboards have a vertical bar chart, and a setBy filter driven by that bar chart, update the colors of the bar chart.
- Add types on bar charts
> [DEV-5189] Dashboard: filter charts with setBy key

- packages/chart/src/CdcChart.tsx
- packages/editor/src/components/ChooseTab.jsx
update configuration from edtior to charts, fixing issue with orientation and regular/stacked
> [DEV-2004] Update editor config

- packages/chart/src/components/EditorPanel.jsx
Change criteria of option  "Use Legend Value in Hover"
> [DEV-5958] change option criteria of "Use Legend Value in Hover"

- packages/chart/index.html
- packages/chart/src/components/LineChart.Circle.tsx
- packages/chart/src/components/Series.jsx
- packages/chart/src/hooks/useTooltip.jsx
- Shows data seris options when changing from forecast to combo chart
- Fixes console errors related to keys in legend circles
- Fixes console errors related to tooltips
> [DEV-6015] fix forecast chart issues in combo charts

- packages/chart/src/components/DeviationBar.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/components/PairedBarChart.jsx
- packages/editor/src/components/ChooseTab.jsx
Deviation and Paired Bar: Remove error when adding and removing data series
> [DEV-6194] Remove error when adding and removing data series

- packages/chart/examples/feature/line/line-points.json
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/LineChart/LineChart.Circle.tsx
- packages/chart/src/components/LineChart/LineChartProps.ts
- packages/chart/src/components/LineChart/index.tsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/types/ChartConfig.ts
- packages/chart/src/types/ChartContext.ts
- Added chart context type
- Added line chart props type
- Removed unused functions: handleAxisFormatting, formatDate in Line Chart
- Remvove unused variables: xAxis, yAxis values in Line Chart
> [DEV-6202] Add Line Chart Circle Color Option

- packages/chart/examples/feature/regions/index.json
- packages/chart/index.html
- packages/chart/src/components/BarChart.Vertical.tsx
- packages/chart/src/components/LinearChart.jsx
@mpallansch & @Atash3000 - can you do a quick pass on this? It sets regions on grouped bar charts to account for the full bar width. Thanks!
> [DEV-6286] 4.23.11: updated logic for region highlighting

- packages/chart/examples/gallery/bar-chart-vertical/combo-line-chart.json
- packages/chart/index.html
- packages/chart/src/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart.StackedHorizontal.tsx
- packages/chart/src/components/BarChart.StackedVertical.tsx
- packages/chart/src/components/BarChart.Vertical.tsx
- packages/chart/src/components/BarChart.jsx
- packages/chart/src/components/EditorPanel.jsx
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/hooks/useBarChart.js
- packages/chart/src/hooks/useEditorPermissions.js
- packages/chart/src/hooks/useScales.ts
- packages/chart/src/hooks/useTooltip.jsx
Added single series tooltip for Bars & added series highligh on hover on bars.
> [DEV-6084] 

- packages/chart/src/components/LineChart/LineChart.Circle.tsx
- packages/chart/src/components/LineChart/index.tsx
Fixed line chart circle hovers
> [line-circle] Fix Line chart circle visibility

- packages/chart/index.html
- packages/chart/src/components/BarChart.Vertical.tsx
- packages/chart/src/hooks/useTooltip.tsx
- packages/chart/src/types/ChartContext.ts
- packages/dashboard/index.html
- packages/map/index.html
- adds an offset for bar width to get the closest x value
- changes useTooltip.jsx file to .tsx
- adds logic for handling dates better in useTooltip file
> [DEV-6574] fix dashboard tooltip click behavior

- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/Table/Table.tsx
- packages/core/components/Table/components/Cell.tsx
- packages/core/components/Table/components/Row.tsx
- packages/map/index.html
- packages/map/src/CdcMap.tsx
- packages/map/src/components/EditorPanel.jsx
- packages/map/src/data/initial-state.js
- packages/map/src/scss/main.scss
This adds support for data table wrapping in maps. 
Editor Panel > Data Table > Wrap Data Table Columns
> [DEV-13577] 4.23.12 > wrap table columns

- packages/chart/examples/feature/sankey/initial.json
- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/data/initial-state.js
@navbajwa97 and @jnorris2135 - Here is the update that fixes the spacing issue. I noticed the last items were overflowing the svg container, so I created a ref to get the largest width and subtract that from the sankeys extent.
> [sankey-diagram-outward] fit last nodes inside of svg

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/ForestPlot/ForestPlotSettings.tsx
- packages/chart/src/types/ChartConfig.ts
- packages/chart/src/types/ChartContext.ts
- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/EditorPanel/DataTableEditor.tsx
- packages/core/components/EditorPanel/Inputs.tsx
- packages/core/components/Table/components/Cell.tsx
- packages/core/components/Table/components/Row.tsx
- packages/core/types/Axis.ts
- packages/core/types/Column.ts
- packages/core/types/FilterBehavior.ts
- packages/core/types/Runtime.ts
- packages/core/types/Series.ts
- packages/core/types/Table.ts
- packages/dashboard/src/types/Config.ts
refactored adding additional types and pulled DataTable out to its own component
> Chart EditorPanel Refactor

- packages/chart/src/components/LinearChart.jsx
Hide tick mars on horizontal bars.
> [DEV-6688] Hide Tick marks

- packages/chart/examples/feature/sankey/initial.json
- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
Adding all the tooltip data and some minor css & html for the hover over card
> Tooltip Data

- packages/chart/examples/feature/sankey/initial.json
adding tooltip data for suicide ems responses
> Missing EMS responses data

- packages/chart/src/components/Sankey/index.tsx
Node selection updated to behave as expected
> Node Selection

- packages/chart/examples/feature/sankey/initial.json
- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
Updating script to import the rest of the data
Adding styling to the card to mimc the designs
> Hover Card 

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/LineChart/helpers.ts
Fix bugs in Line Special Cases - Preliminary Data
> [DEV-6643a] Fix Line Special Cases

- packages/chart/src/components/AreaChart/components/AreaChart.Stacked.jsx
Stacked Area Charts: Remove Opacity from the Area
> [DEV-6707] Stacked Area Charts: Remove Opacity from the Area

- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
- packages/chart/src/data/initial-state.js
I added media queries and updated the sankey typescript file to use the media queries for font size.
> add media queries for autoscaling.

- packages/chart/examples/feature/sankey/initial.json
- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
- packages/data-bite/src/components/KPIComponent.jsx
- packages/data-bite/src/scss/kpi.scss
Creating KPI Component
Styling it 
Adding the data
> KPI Component

- packages/chart/src/components/Legend/Legend.tsx
Fixed legend for preliminary data legend
> [fix-legend] Fix legend

- packages/chart/examples/feature/line/line-chart-preliminary.json
- packages/chart/index.html
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/LineChart/index.tsx
- packages/chart/src/scss/main.scss
Removed Dashes and kept only open circles on effect along with legend
> [remove-dashes]  Remove Dashes

- packages/chart/examples/feature/sankey/sankey-example-data.json
fixing the first column issue in the data table
> Data Table Fix

- packages/core/components/ui/_stories/Icon.stories.tsx
> Icon stories

- packages/chart/index.html
- packages/chart/src/components/EditorPanel/editor-panel.scss
- packages/dashboard/index.html
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/scss/editor-panel.scss
- packages/dashboard/src/scss/grid.scss
- packages/dashboard/src/scss/main.scss
- packages/data-bite/src/scss/editor-panel.scss
- packages/editor/index.html
- packages/editor/src/scss/configure-tab.scss
- packages/editor/src/scss/main.scss
- packages/map/src/scss/editor-panel.scss
I had to make room for new features coming with the MultiDashboard
> [dev-6597] editor css refactor and TP4 css added

- packages/dashboard/src/components/MultiConfigTabs/MultiConfigTabs.tsx
- packages/dashboard/src/scss/grid.scss
fixed modal not closing
fixed bug where deleting new tab was causing an error.
fixed nav overlapping widgets when multiselect active.
> [dev-6597] fix modal not closing

- packages/core/components/DataTable/helpers/customSort.ts
Fixed Map regions map table sorting order
> [DEV-6952] Fix Regions table sorting

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/LinearChart.jsx
Fix Value Axis Label Disappearing
> [DEV-6954] Fix Value Axis Label Disappearing

- packages/chart/src/CdcChart.tsx
Combo Chart: Series Type settled default to Bar
> [DEV-7041] set default series in combo chart

- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
> updates for mobile

- packages/chart/src/components/LineChart/LineChartProps.ts
- packages/chart/src/components/LineChart/index.tsx
Updated raw data to table data for splitLinePath component
> [line-chart] Update data to table data

- packages/chart/src/components/Sankey/sankey.scss
Fixing the text sizing so it will be 508 compliant for all screen sizes
> 508 Compliance - Text Sizing

- packages/chart/src/components/Sankey/sankey.scss
Changing the opacity of the sankey chart in mobile to draw more attention to the pop up
> Opacity Mobile

- packages/chart/src/components/Sankey/index.tsx
- packages/chart/src/components/Sankey/sankey.scss
Fixing mobile text sizing and pop up
> Mobile Fixes

- .storybook/main.ts
- package.json
- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/MultiSelect/multiselect.styles.css
- packages/core/components/Table/Table.tsx
- packages/core/components/_stories/MultiSelect.stories.tsx
- packages/core/components/ui/Tooltip.jsx
- packages/core/types/UpdateFieldFunc.ts
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/DashboardContext.tsx
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/dashboard/src/_stories/_mock/pivot-filter.json
- packages/dashboard/src/components/Filters.tsx
- packages/dashboard/src/components/Header/FilterModal.tsx
- packages/dashboard/src/components/Header/Header.tsx
- packages/dashboard/src/helpers/filterData.ts
- packages/dashboard/src/helpers/getUpdateConfig.ts
- packages/dashboard/src/helpers/tests/filterData.test.ts
- packages/dashboard/src/store/dashboard.actions.ts
- packages/dashboard/src/store/dashboard.reducer.ts
- packages/dashboard/src/types/DataSet.ts
- packages/dashboard/src/types/InitialState.ts
- packages/dashboard/src/types/SharedFilter.ts
- packages/dashboard/src/types/Tab.ts
- packages/editor/src/_stories/Editor.stories.tsx
- packages/editor/src/_stories/_mock/pivot-filter.json
- yarn.lock
- updated multiselect for 508 compliance. 
- added pivot column filter. 
- refactored filter modal.
> Feature: [dev -7048] [dev-6815] multiselect and filter pivot table

- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/index.ts
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/core/components/_stories/NestedDropdown.stories.tsx
> Feature [dev-6387] Nested Dropdown

- .storybook/main.ts
- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/MultiSelect/multiselect.styles.css
- packages/dashboard/src/helpers/filterData.ts
- request on ticket was made to display no columns when nothing is selected.
- also added update for storybook to include name in the storybook js bundles to give insight into which stories are largest. Dashboard is currently very large so maybe we can figure out how to reduce that
> Fix: [dev-7048] Pivot Filter fix after UX comments 

- packages/chart/src/components/Sankey/sankey.scss
fixing the story node text size issue
> UAT Issue 1 - Text Size

- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/scss/main.scss
- Legends should receive h3 based on feedback
- Matches original font sizes
> [DEV-7415] Accessibility > adjust legend title heading

- packages/core/components/ui/Title/Title.scss
- packages/core/components/ui/Title/index.tsx
- Reads out title in voice over
- Matches previous font size
- Able to reach Headings in VO menu
> [DEV-7414] Accessibility > Support Viz titles

- packages/chart/src/components/Sankey/index.tsx
adding a visually hidden button for pop up on mobile for users using the screen reader
> UAT Issue 2 - PopUp

- packages/chart/examples/feature/sankey/sankey-example-data.json
- packages/editor/src/samples/valid-sankey-data.json
adding commas to the values in the data table
> UAT Issue 3 - Data Table 

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/EditorPanel/useEditorPermissions.js
Added Prelimenary data to Combo
> [DEV-7503] Add PreliminaryData to Combo

- packages/chart/src/components/PairedBarChart.jsx
- Test using dequeue svg pattern 7 from the following url: https://www.deque.com/blog/creating-accessible-svgs/
> [DEV-7438] Accessibility > Paired Bar Alt Text

- packages/chart/src/components/EditorPanel/useEditorPermissions.js
- packages/chart/src/hooks/useBarChart.js
- packages/core/components/createBarElement.jsx
Fixed errors for isolate bars and showing Preliminary data in Line & Combo bars.
> [DEV-7397a] Fix errors

- packages/chart/examples/sparkline.json
- packages/chart/index.html
- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Sparkline/components/SparkLine.tsx
- packages/chart/src/components/Sparkline/index.scss
- packages/chart/src/components/Sparkline/index.tsx
- packages/chart/src/types/ChartContext.ts
- packages/core/components/Filters.jsx
- packages/core/types/Axis.ts
- packages/core/types/Runtime.ts
- Update aria descriptions
- Add TS improvements
- Remove theme class for filters on spark lines to display properly
- Move filter container for sparklines into body for proper wrapping
> [DEV-7442] Acessibility > Spark Line Updates

- packages/chart/src/CdcChart.tsx
- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/DataTable/components/SkipNav.tsx
- packages/core/components/elements/SkipTo.tsx
- packages/map/src/CdcMap.tsx
- packages/map/src/components/DataTable.jsx
- Rename SkipNav to SkipTo
- Allow changing skipMessage
- Update chart/map packages where skipping is used
- Update core data table where SkipNav was used
> [DEV-7425] Update Skip components

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/BoxPlot/BoxPlot.jsx
- packages/chart/src/components/DeviationBar.jsx
- packages/chart/src/components/PairedBarChart.jsx
- packages/chart/src/components/ScatterPlot/ScatterPlot.jsx
- Remove tab index on scatter plot, box plot, deviation bar, and paired bar charts
> [DEV-7436] Scatter Plot > Remove tab indexes

- packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart/components/BarChart.StackedHorizontal.tsx
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
- packages/chart/src/components/DeviationBar.jsx
- packages/chart/src/components/PairedBarChart.jsx
- packages/chart/src/components/PieChart/PieChart.tsx
- packages/core/data/colorPalettes.js
- packages/core/helpers/cove/accessibility.js
- packages/map/src/CdcMap.tsx
- packages/map/src/components/UsaMap/components/Territory/Territory.Hexagon.tsx
- packages/map/src/components/UsaMap/components/Territory/Territory.Rectangle.tsx
- packages/map/src/components/UsaMap/components/UsaMap.Region.tsx
- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
- Change ratio from 3.5 to 4.5 and use variable
- Verified color palettes against B.A. Notes.
> [DEV-7622] WCAG 4.5 Color Contrast Changes

- packages/chart/src/components/LineChart/index.tsx
Add right axis scale for preliminary circles
> [DEV-7503a] Handle right axis circles on LineChart

- packages/chart/src/components/BumpChart/components/BumpChart.tsx
import statements were throwing errors
> fixing imports

- packages/map/src/components/CityList.jsx
Updated map shape props to skip tab focusing for each shape & updated title
> [map-shapes] Update map shape props

- packages/map/src/components/CityList.jsx
Added Tab index props to skip tabbing on Pin shape.
> [map-tabIndex] Add tabindex to the Pin shape

- packages/chart/examples/feature/bump_chart/index.json
- packages/chart/src/components/LineChart/components/LineChart.BumpCircle.tsx
- packages/chart/src/components/LinearChart.jsx
Fixing the chart to match what it was pre-transition to LinearChart
Also looping in the following Items from sprint 2 & 3:
- fixing the format of the numbers and circles on the lines
- format x & y axis labels and values
- inactive / active state --using the cove legend feature
> Transition to LinearChart Fixes

- packages/editor/src/components/DataImport.tsx
> HotFix: url data sources not working

- packages/core/components/MediaControls.jsx
@adamdoe They are requesting this change be included in the 5/7 release
> Fix for Image Download

- packages/editor/src/components/PreviewDataTable.tsx
Fixed table preview on Editor table data.
> [DEV-0000] Fix table preview data

- packages/map/src/components/CityList.jsx
@adamdoe Palak wanted this to be included in the release next week, is that possible?
> Fixes Crash When Using Shared Filter

- packages/core/components/Filters.jsx
Removed intro text when filters are not on.
> [sparkLine-filters] Fix intro text apperance on filters

- packages/core/components/DataTable/DataTableStandAlone.tsx
- packages/core/components/DataTable/types/TableConfig.ts
- packages/core/components/EditorWrapper/EditorWrapper.tsx
- packages/core/types/Visualization.ts
- packages/dashboard/src/components/VisualizationRow.tsx
data table filters were failing
> fix: [dev-7807] data table filters

- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/getFilteredData.ts
- packages/editor/src/CdcEditor.tsx
Steps to test are listed in the ticket
> bug: [dev-8575] ardi multi viz

- packages/chart/src/components/LinearChart.jsx
Needed on wwwdev for 4.26.6 release to fix respiratory page issues
> Fixes Excessive Space Beneath Axis Issue

- lerna.json
- packages/dashboard/examples/filtered-dash.json
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/CollapsibleVisualizationRow.tsx
- packages/dashboard/src/components/DataDesignerModal.tsx
- packages/dashboard/src/components/ExpandCollapseButtons.tsx
- packages/dashboard/src/components/VisualizationRow.tsx
- packages/dashboard/src/scss/main.scss
- packages/dashboard/src/types/ConfigRow.ts
Testing Instructions
New Dashboard
1. Open CDC Editor, choose Dashboard, and import data.
2. In the Dashboard editor, hover over the hamburger icon on the top left of the visualization box and select the "Toggle between up to three visualizations" icon all the way to the right
3. Drag and drop up to 3 visualizations into the box
4. Click on the Gear icon in the top right corner of the visualization row box
5. Choose the dataset and select the "Configure Multiple Visualizations" checkbox
6. Choose an option from the drop down
7. Click the "Add Expand/Collapse All Buttons" checkbox
8. Click Continue
9. Configure the visualizations if needed
10. Click on, Dashboard Preview Tab
11. In preview click the Expand All and Collapse All buttons to see that they are functioning properly
12. Click on …
> DEV-7763 Expand/Collapse Buttons

- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
fixed typo and fixed filter preview styling caught during QA.
> Fix: [dev-8409] dashboard filter styling typo

- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/formatConfigBeforeSave.ts
- packages/core/types/Visualization.ts
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/components/MultiConfigTabs/MultiConfigTabs.tsx
- packages/dashboard/src/components/Toggle/Toggle.tsx
- packages/dashboard/src/components/VisualizationRow.tsx
- packages/dashboard/src/helpers/getVizConfig.ts
- packages/dashboard/src/helpers/hasDashboardApplyBehavior.ts
- packages/dashboard/src/helpers/iconHash.tsx
- packages/dashboard/src/helpers/processData.ts
- packages/dashboard/src/types/DashboardConfig.ts
- packages/dashboard/src/types/DashboardFilters.ts
see testing instructions in ticket
> Fix: [dev-8825] API Dashboard Issues

- packages/core/components/AdvancedEditor/AdvancedEditor.tsx
ticket was rejected because large file was not loading in advanced editor. This fix collapses the large data fields and reduces the amount of json parsing to improve performance.
> Fix: [dev-8574] advanced editor

- packages/core/helpers/coveUpdateWorker.ts
> multi-dashboard-fix

- packages/chart/examples/gallery/bar-chart-vertical/vertical-bar-chart-stacked.json
- packages/chart/index.html
- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Axis/Categorical.Axis.tsx
- packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/EditorPanel/useEditorPermissions.ts
- packages/chart/src/components/LinearChart.jsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/hooks/useMinMax.ts
- packages/chart/src/hooks/useScales.ts
- packages/chart/src/types/ChartConfig.ts
- packages/core/components/EditorPanel/Inputs.tsx
- packages/core/components/createBarElement.jsx
- packages/core/helpers/ver/4.24.7.ts
- packages/core/types/Axis.ts
* [DEV-8841] Add categorical axis
* [DEV-8841] Add Category Axis
* [DEV-8841] Update versioning
* [DEV-8841] Cleanup code
* [DEV-8841] add clamp to prevent overflow
* [DEV-8841] Update code issues
> Feature/dev 8841 (#1430)

- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/ver/4.24.7.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
> fix dev-8912 updated 4.24.7 migration

- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/ver/4.24.7.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
> [DEV-8912-ACTIVE] [DEV-8912] updated 4.24.7 migration (#1448)

- packages/core/helpers/ver/4.24.7.ts
> Fix dev 8912 active property additional fix

- packages/core/helpers/ver/4.24.7.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/components/Header/Header.tsx
- packages/dashboard/src/components/VisualizationRow.tsx
- packages/dashboard/src/helpers/FilterBehavior.ts
- packages/dashboard/src/helpers/changeFilterActive.ts
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/dashboard/src/types/SharedFilter.ts
testing steps are in the ticket https://websupport.cdc.gov/browse/DEV-8715?filter=-1
> feature [dev-8715] dashboard-multi-select

- packages/chart/src/components/Axis/Categorical.Axis.tsx
> [grid-line] Fix grid line

- .github/workflows/storybook-deploy.yml
> storybook deployment config

- packages/dashboard/src/_stories/_mock/bump-chart.json
PR#1468
Applied 508 updates to bump chart storybook json. Updated the legend text and adjusted the header tags for the markup include HTML.
> Applied 508 updates to bump chart storybook json

- packages/core/components/DataTable/helpers/getDataSeriesColumns.ts
Create a standalone table within a dashboard and open the editor for it
> fix: [dev-8791] Fixes Crash with Standalone Tables

- packages/chart/src/components/Sankey/index.tsx
> [DEV-8579] Sankey > Tooltip Toggling

- packages/core/helpers/addValuesToFilters.ts
> Fixes Blanks in Dashboard Filter Dropdowns

- packages/core/components/Filters.tsx
- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/helpers/addValuesToFilters.ts
- packages/core/helpers/formatConfigBeforeSave.ts
- packages/core/helpers/tests/addValuesToFilters.test.ts
- packages/core/helpers/ver/4.24.7.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/dashboard/src/_stories/_mock/api-filter-map.json
- packages/dashboard/src/_stories/_mock/methodology.json
- packages/dashboard/src/_stories/_mock/methodologyAPI.ts
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/getFilteredData.ts
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/dashboard/src/helpers/tests/addValuesToDashboardFilters.test.ts
- packages/dashboard/src/helpers/tests/apiFilterHelpers.test.ts
- packages/dashboard/src/helpers/tests/getFilteredData.test.ts
- packages/dashboard/src/helpers/tests/reloadURLHelpers.test.ts
For dev-8912: Storybook: Pages/Dashboard/Regression Hidden Filter
For dev-8944: Storybook. Pages/Dashboard/Regression API Filters Chart
> fix [dev-8944] and feature [dev-8912] hidden methodology

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Annotations/components/AnnotationDraggable.tsx
- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/components/PieChart/PieChart.tsx
- packages/chart/src/hooks/useScales.ts
- packages/chart/src/types/ChartContext.ts
- packages/core/components/Filters.tsx
- packages/core/types/Dimensions.ts
- packages/map/src/CdcMap.tsx
- packages/map/src/components/Legend/components/Legend.tsx
Updated types for Dimensions and created separate new type file
> [type-dimensions] Update dimensions type

- packages/chart/src/CdcChart.tsx
- packages/core/helpers/addValuesToFilters.ts
> Fix: [dev-9076] filter active issue

- packages/dashboard/src/components/VisualizationRow.tsx
> [dashboard-col-classes] update classes for 4.24.9 release

- packages/map/src/components/Legend/components/index.scss
Open Maps, update legend to Bottom, and Click single row. All items should have proper spacing and no word wrap.For small screens items should wrap.
> [DEV-9077] Update CSS styled for single row legend

- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/DashboardContext.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/changeFilterActive.ts
- packages/dashboard/src/helpers/loadAPIFilters.ts
- packages/dashboard/src/helpers/tests/apiFilterHelpers.test.ts
- packages/dashboard/src/helpers/tests/loadAPIFiltersWrapper.test.ts
testing steps are in the ticket.
> Fix: [dev-9093] multi select integration issue

- packages/dashboard/index.html
- packages/map/index.html
- packages/map/src/CdcMap.tsx
- packages/map/src/components/UsaMap/components/UsaMap.County.tsx
> [DEV-9057] 4.24.9 > County Map Sizing Updates

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/EditorPanel/useEditorPermissions.ts
Updated bugs for suppression for stacked bars
> [DEV-8849a] Update suppression for Horizontal charts

- packages/chart/src/components/EditorPanel/components/Panels/Panel.General.tsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/hooks/useTooltip.tsx
- packages/core/types/General.ts
Added new checkbox to controll tooltips where null values appear as 'N/A" or just null as it is.To test we need missing data or null value on data set.
> [DEV-8977] add feature to hide null val from tooltips

- packages/map/src/components/Annotation/AnnotationDropdown.tsx
> [DEV-9145] 4.24.9 > remove class on annotation dropdown

- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
Hided city styles button and options (square,triangle, etc) when map is geocode type.
> [DEV-9143] Hide city styles on geocode map

- packages/map/src/CdcMap.tsx
- packages/map/src/scss/main.scss
- packages/map/src/scss/map.scss
> [DEV-9146] 4.24.9 > match chart container styles

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/LinearChart.tsx
- packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
- packages/core/components/Filters.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nestedDropdownHelpers.ts
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/core/components/NestedDropdown/tests/nestedDropdownHelpers.test.ts
- packages/core/components/_stories/NestedDropdown.stories.tsx
- packages/core/components/_stories/_mocks/nested-dropdown.json
- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/ver/4.24.10.ts
- packages/core/helpers/ver/4.24.9.ts
- packages/core/helpers/ver/tests/4.24.10.test.ts
- packages/core/types/VizFilter.ts
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/NestedDropDownDashboard.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/helpers/changeFilterActive.ts
- packages/dashboard/src/helpers/filterData.ts
- packages/dashboard/src/scss/main.scss
- packages/dashboard/src/types/SharedFilter.ts
> dev-8412 Nested Dropdown Enhancement - Dashboard Level

- packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
- packages/chart/src/components/LineChart/helpers.ts
- packages/chart/src/components/LineChart/index.tsx
> [line-chart] Fix Line chart bugs

- packages/chart/src/components/EditorPanel/useEditorPermissions.ts
Hiding brush chart for upcoming sprint.the bug could not be fixed right now.
> [hideBrush] Hide brush chart

- packages/chart/src/CdcChart.tsx
> fix dev-8412 nested-dropdown

- packages/chart/src/CdcChart.tsx
- packages/core/helpers/coveUpdateWorker.ts
- packages/data-bite/src/CdcDataBite.tsx
- packages/filtered-text/src/CdcFilteredText.jsx
- packages/map/src/CdcMap.tsx
- packages/markup-include/src/CdcMarkupInclude.tsx
- packages/waffle-chart/src/CdcWaffleChart.tsx
General regression testing of waffle charts within dashboards
> Changes Update Worker to Synchronous

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/EditorPanel/useEditorPermissions.ts
- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/components/Legend/helpers/index.ts
- packages/core/components/Filters.tsx
- packages/core/helpers/getGradientLegendWidth.ts
- packages/core/styles/_global.scss
- packages/core/styles/filters.scss
Fixed Legend spacing when legend on the top of the chart
> [legend-top] Fix Legend spacing

- packages/chart/src/components/EditorPanel/useEditorPermissions.ts
Hiding back brush chart for this sprint.Did not pass the test.
> [DEV-4215g] Hide Brush chart for 4.24.9

- packages/core/components/Filters.tsx
> [DEV-9256] Add guards for legend on filters

- packages/core/helpers/gatherQueryParams.ts
- packages/core/helpers/tests/gatherQueryParams.test.ts
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/tests/apiFilterHelpers.test.ts
- packages/dashboard/src/helpers/tests/loadAPIFiltersWrapper.test.ts
> Fix: [dev-9117] url param and multi select

- packages/chart/src/CdcChart.tsx
- packages/core/components/EditorPanel/VizFilterEditor/NestedDropdownEditor.tsx
- packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
- packages/core/components/EditorPanel/VizFilterEditor/components/FilterOrder.tsx
- packages/core/components/Filters.tsx
- packages/core/types/VizFilter.ts
Testing steps are in the ticket.
> hot-fix [dev-9257] broken custom sort order in viz filters

- packages/dashboard/src/helpers/apiFilterHelpers.ts
Testing instructions are in the ticket
> fix [dev-9295] fixes issue with dashboard filter not getting set by query param

- packages/chart/src/components/Axis/Categorical.Axis.tsx
- packages/chart/src/components/LinearChart.tsx
Lightens grid lines from `rgb(0,0,0,0.3)` to `#d6d6d6` as shown in ticket.
> [dev-9287] lighten grid

- packages/chart/src/components/Regions/components/Regions.tsx
Removes grey region top border as described in ticket.
> [dev-9289] Remove region top border

- packages/map/src/CdcMap.tsx
1. Using editor, select map
2. Load URL for Data: https://wcms-wp.cdc.gov/wcms/4.0/cdc-wp/data-presentation/data/county-year.csv with "Always load" *unchecked*
3. Data Mapping:  
Vertical orientation
Yes multiple data series
Multiple Rows, answer "FIPS", "YEAR", and "VALUE" to the first three questions in that order.
4. On configure screen, ensure column dropdowns have FIPS numbers as options 
> Maps, Supports Formatting of Non-URL Data

- packages/core/helpers/formatConfigBeforeSave.ts
- packages/core/helpers/gatherQueryParams.ts
- packages/core/helpers/tests/gatherQueryParams.test.ts
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/dashboard/src/helpers/tests/reloadURLHelpers.test.ts
Testing instructions are in the ticket.
> PATCH: [dev-9341] runtimeDataURL

- packages/markup-include/src/CdcMarkupInclude.tsx
> PATCH: [dev-8923] Memory leak fixed

- packages/map/src/CdcMap.tsx
> Fixes Race Condition With Tooltips

- packages/chart/src/CdcChart.tsx
1. Build cove
2. Run editor
3. Select chart
4. Upload this dataset as CSV: https://cdc-my.sharepoint.com/:x:/g/personal/wms4_cdc_gov/EXsqBh4Y4khJjihf693t95cBjVkXtZ85HUZttAodV4OfXA?email=yfz3%40cdc.gov&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1727363565324&web=1
5. Answer editor questions: vertical, yes, multi-row, category, year, value
6. Check dynamic series in editor, and year for x axis
7. Add filters for State, HFS Indictator, and Demographic
8. Ensure chart isn't blank
> Allows Dynamic Series for Null Values

- packages/core/helpers/coveUpdateWorker.ts
it seems like there was an issue with a merge or something?
run `yarn workspace @cdc/core run test`
tests should pass
> FIX coveUpdateWorker

- _stories/Guide.NewStories.stories.mdx
I've been meaning to add this checklist into the storybook docs for a while. 
> Storybook Docs: New Story Checklist

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
Fixed the bug with open circles for line chart.It is going to patch.
> [DEV-9391] Fix line chart circle

- packages/dashboard/src/helpers/changeFilterActive.ts
> Fixes Query String Parameter Update From Filter

- packages/map/src/CdcMap.tsx
Use a random ID instead of react tooltip hook to show/hide the tooltips
> [location-tooltip-issue] update tooltip id to random id

- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/components/Legend/Legend.Suppression.tsx
- packages/chart/src/scss/main.scss
Fixed small bugs on Legend suppression and also update styling from css to bootstrap classes to align legend lines.
Testing steps:
Open line chart 
On legend panel select Legend Styles ==> "Lines" style.
And Lines has to be properly aligned with labels.
> [DEV-9399] Update legend  items

- packages/chart/src/hooks/useColorPalette.js
- packages/core/data/colorPalettes.js
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
Added new color pallete "safeBlind" for users who needs accecibility.It goes under non-sequantial palette for Maps and Charts.
To test it we need to open charts or maps ==>Visual Panel ==>non sequantial pallete.
> [DEV-9273] Add new color palette for Maps & Charts

- packages/dashboard/src/store/dashboard.reducer.ts
testing steps are in the ticket.
> Fix: [dev-9094] multi dashboard filters

- packages/core/components/Filters/Filters.tsx
- packages/core/components/Filters/helpers/getNestedOptions.ts
- packages/core/components/Filters/helpers/handleSorting.ts
- packages/core/components/Filters/helpers/tests/handleSorting.test.ts
- packages/core/components/Filters/index.ts
> Fix: [dev-9346] nested dropdown viz options

- .storybook/coreStyles_storybook.scss
- packages/dashboard/src/components/MultiConfigTabs/multiconfigtabs.styles.css
first tab is active:
second tab is hovered:
> Feature: dev-8901 styling tabs

- packages/dashboard/src/CdcDashboardComponent.tsx
testing steps are in the ticket
> Fix dev-9295  additional setByQueryParam Fixes

- packages/map/src/scss/map.scss
Updated Css style for Hex Map territories.Full instruction is on the ticket.
> [DEV-9279] Update margin for Hex map territories

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
Updated Link for Data category parsing info.To test it : open any chart, on Date Category Panel change to Time or Date scale. Result in this attached image.
> [DEV-9417] Update Link for Date parsing information

- packages/editor/src/components/ChooseTab.tsx
Updated Epi chart to be Combo chart by default.
> [DEV-7043a] Update Epi chart to Combo

- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/DataTable/components/ChartHeader.tsx
- packages/core/components/DataTable/helpers/getDataSeriesColumns.ts
- packages/core/components/DataTable/helpers/getNewSortBy.ts
- packages/core/components/EditorPanel/DataTableEditor.tsx
- packages/core/helpers/pivotData.ts
- packages/core/helpers/tests/pivotData.test.ts
- packages/core/helpers/ver/4.24.10.ts
- packages/core/helpers/ver/tests/4.24.10.test.ts
- packages/core/types/Table.ts
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/dashboard/src/_stories/_mock/group-pivot-filter.json
- packages/dashboard/src/_stories/_mock/pivot-filter.json
> enhancement [dev-8930] transpose table

- packages/core/components/DataTable/DataTableStandAlone.tsx
- packages/core/components/Loader/Loader.tsx
- packages/core/components/Loader/index.ts
- packages/core/components/Loader/loader.styles.css
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/components/MultiConfigTabs/MultiTabs.tsx
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/markup-include/src/CdcMarkupInclude.tsx
Testing instructions are in the ticket
> fix [dev-9487] switching dashboard tabs causing errors

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/core/helpers/addValuesToFilters.ts
> Fix [dev-9506] dashboard chart memory leak

- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
removed unfinished code from filter editor
steps to reproduce the issue are in the ticket
> Fix: [dev-9522] multi select filter issue caused by dev-8412

- packages/dashboard/src/CdcDashboardComponent.tsx
1) Open dashboard editor panel.
2) click first "Add Footnotes" button.
expected: you should see the footnotes editor panel.
> Fix [dev-9534] footnotes editor panel

- packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
- packages/chart/src/hooks/useColorPalette.js
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
Added new Color scheme for Visual panel color ==> Accessible Color Schemes. it has only one palette.
Open Visual tab for any chart or Map to see results.
> [DEV-9273a] Add new color scheme

- packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
Updated Label as was requested for changes.
> [DEV-9273b] Update Label for colors schema

- packages/chart/src/CdcChart.tsx
> [trim-values] Update a function to trim each value and make it unique

- packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
> [trim-values-dashboard] Update function

- packages/chart/src/components/LinearChart.tsx
Tooltip is fixed. Add more text to message field to have more space above chart and hover on bars. tooltip should not overflow out of bars.
> [DEV-9556] Fix Tooltip position

- packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
> [DEV-9198b] Update Filters

- packages/chart/src/data/initial-state.js
- packages/chart/src/hooks/useScales.ts
Default padding added to time scale bar. Fixed padding right side of bars when time scale. On date category tab add padding value to see result. make sure it is Time scale.
> [DEV-9547a] Update time scale padding

- packages/chart/src/hooks/useScales.ts
Removed padding from Line charts
> [DEV-9631] remove padding from Line charts

- packages/core/components/Alert/components/Alert.tsx
- packages/core/components/DataTable/components/SortIcon/sort-icon.css
- packages/core/components/DataTable/data-table.css
- packages/core/helpers/fetchRemoteData.js
- packages/core/styles/_global-variables.scss
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/loadAPIFilters.ts
- packages/dashboard/src/helpers/tests/loadAPIFiltersWrapper.test.ts
- packages/dashboard/src/store/errorMessage/errorMessage.actions.ts
- packages/dashboard/src/store/errorMessage/errorMessage.reducer.ts
- packages/editor/src/components/PreviewDataTable.tsx
- yarn.lock
Scenario: Open a Default Editor and choose the Dashboard Viz. 
Expected: On the Import Data screen
1. Choose Load from URL
2. Add the following link: https://nccd-cove-public-api.apps.ecpaas-dev.cdc.gov/od-public?$datakey=brfss_prevalence_cove_explore_by_t
3. Check the "Always load from URL" checkbox
4. Click on the "Load" button
5. Click the "Configure your Visualization" button
Expected: On the Configure screen
6. Drag a Filter Dropdowns viz into the Visualization area
7. Click on the tools icon
Expected: In the Configure Dashboard Filter screen
8. Click the Filter Accordion
9. Click Add Filter
10. Click the Down arrow button next to "New Dashboard Filter 1"
11. Select URL in the Filter Type dropdown
12. Click inside the textbox of "API EndPoint"
13. Add this "broken" API link (link …
> Enhancement: Dev-9439 API Error Message Display

- packages/core/helpers/queryStringUtils.ts
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/components/MultiConfigTabs/MultiTabs.tsx
Scenario: Tester is on a Dashboard with Tabs.
1) navigate to any other tab which isn't the first one.
2) copy the URL in the address bar.
3) paste and reload the URL.
expected: the page should reload on that tab.
> Enhancement: [dev-8244] link to tab

- packages/dashboard/src/components/Header/Header.tsx
- packages/dashboard/src/components/VisualizationRow.tsx
- packages/dashboard/src/components/Widget.tsx
- packages/dashboard/src/helpers/getVizRowColumnLocator.ts
testing instructions in the ticket require network access to see chronic api data. @Matt-DiPaolo could you check that?
> Fix [dev-9074] editor api data

- packages/core/helpers/DataTransform.ts
Dynamic Data Series: Filter column plotting, plus undefined
New viz
Dashboard
Use the attached data set (in ticket)
Drag on filter
Drag on bar chart
Configure the filter. Data filter, StratificationCategory2, used by the chart
Configure the chart.
Data config: Vertical, Yes, Multiple, StratificationId2, YearEnd, Data Value, ignore StratificationCategory1
Bar chart config: Data Series - Check Dynamic, Date/Category - YearEnd, I'm Done
Bar chart config: Add filter for StratificationCategory2 with hidden input
You should see Overall (good), and the filter column (not good)
Go back to the dash preview. You see those two plus an "undefined" which should not be there
- My changes …
> Fixes Undefined in Dynamic Series

- packages/core/components/DataTable/data-table.css
- packages/core/styles/_global-variables.scss
- packages/editor/src/_stories/Editor.stories.tsx
- packages/editor/src/components/PreviewDataTable.tsx
- packages/editor/src/scss/data-import.scss
https://websupport-cdc.msappproxy.net/browse/DEV-9633
- Table was missing margins between the table and search bar
- Table was missing margins between the table and pagination buttons
- Pagination buttons were missing icons (using react-icon since we don't have the svgs for these)
- Header didn't stretch to fill entire space
- Table data cells didn't stretch to fill space
- Text was overlapping cells instead of using the ellipsis
- `table-responsive` class wasn't used
> [DEV-9633] Update preview table

- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/Table/Table.tsx
- packages/core/components/_stories/DataTable.stories.tsx
- packages/core/components/_stories/_mocks/DataTable/no-data.json
https://websupport.cdc.gov/projects/DEV/issues/DEV-9452
If a table has no data then the message "No Data" is displayed within the Table
Testing Instructions
Scenario: Upload [dev-9452-no-data.json](https://github.com/user-attachments/files/17622316/dev-9452-no-data.json) and in Configuration, open the Dashboard preview
Expected: Table with no data and the words "No Data" in place of the table cells.
> Enhancement: Dev-9452 Table No Data Scenario

- packages/chart/src/CdcChart.tsx
regression found, chart tables were showing N/A. Tables should now show values
> Enhancement Fix: [dev-9672] dynamic data series

- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/MultiSelect/multiselect.styles.css
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/core/styles/_reset.scss
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
fixes for issues described in the ticket. to test add a nested dropdown, multiselect dropdown, and a regular dropdown next to eachother on a dashboard filter widget.
> Enhancement-fix [dev-8903] dropdown styling

- packages/core/components/DataTable/DataTable.tsx
Removed default sorting logic. 
> [DEV-9694] remove default state

- packages/chart/src/components/LinearChart.tsx
Updated tick count logic for horizontal bars
> [DEV-9667] Update tick counter

- packages/core/components/Legend/Legend.Gradient.tsx
> [DEV-9708] Add pointer cursor to the legend gradient

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx
> enhancement fix [dev-9672] dynamic series notes

- packages/core/components/EditorPanel/DataTableEditor.tsx
- packages/dashboard/src/components/Widget.tsx
fixes issue with loadSampleData using csv
> fix-part2/dev-9074-data-not-initially-loading

- packages/chart/src/hooks/useReduceData.ts
- packages/core/helpers/useDataVizClasses.ts
> Feature fix/ [dev-9672] dynamic series

- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/MultiSelect/multiselect.styles.css
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
adding nested dropdown, multiselect and regular dropdown to a screen you should see each with '- Select -' as the default option. See screenshot.
> Feature: [dev-9760] default dropdown option

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/EditorPanel/components/Panels/Panel.Annotate.tsx
- packages/chart/src/components/EditorPanel/components/Panels/Panel.Sankey.tsx
- packages/chart/src/components/EditorPanel/components/Panels/Panel.Series.tsx
- packages/data-bite/src/CdcDataBite.tsx
- packages/data-bite/src/components/EditorPanel.jsx
- packages/filtered-text/src/components/EditorPanel.jsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
- packages/map/src/components/EditorPanel/components/Panels/Panel.Annotate.tsx
- packages/map/src/components/EditorPanel/components/Panels/Panel.PatternSettings.tsx
- packages/map/src/components/UsaMap/components/UsaMap.County.tsx
- packages/markup-include/src/CdcMarkupInclude.tsx
- packages/markup-include/src/components/Conditions.tsx
- packages/waffle-chart/src/CdcWaffleChart.tsx
Updates various button class names for proper styling (see link)
> [DEV-9735] Buttons > Update Class Names

- .storybook/preview-head.html
- packages/core/components/EditorPanel/Inputs.tsx
- packages/core/components/Filters/Filters.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/core/styles/_global.scss
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
1) run storybook. 
2) navigate to pages/dashboard/dashboard filters.
3) in the code navigate to .storybook/preview-header.html and comment out the bootstrap and tp4 reference and uncomment the tp5 reference.
you should see the dashboard filters looking about the same and they should have arrows. Ultimately you'll need to test this in DFE
> fix [dev-9789] dropdown arrow

- packages/core/components/Filters/Filters.tsx
> [DEV-9794] Make filters section 100% width

- packages/core/components/Filters/Filters.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
Reverts CDCgov/cdc-open-viz#1676
> Revert "Fix: Dev-9755 - Nested dropdown doesn't close on blur to another dropdown"

- packages/core/components/Filters/Filters.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
> Fix [dev-9755] nested dropdown blur

- packages/core/helpers/formatConfigBeforeSave.ts
testing instructions are in the ticket.
> Fix [dev-9753] dashboard footnotes

- packages/chart/index.html
- packages/chart/src/_stories/Chart.stories.tsx
- packages/chart/src/_stories/_mock/area_chart_stacked.json
- packages/chart/src/components/AreaChart/components/AreaChart.Stacked.jsx
- packages/chart/src/hooks/useMinMax.ts
> [DEV-9715] Area Chart > Stacked > Force 0 on y scale

- packages/editor/src/components/ChooseTab.tsx
> [DEV-9309b] Remove white space

- packages/chart/src/_stories/_mock/dynamic_series_bar_config.json
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
1) run storybook 
2) navigate to Templates/Chart/Dynamic Series/Bar
expected: you should see groupings of bar charts with confidence intervals
for a regression you can check `/examples/gallery/bar-chart-vertical/vertical-bar-chart-confidence.json`
> Fix [dev-9817] dynamic confidence interval

- packages/map/src/components/Legend/components/index.scss
Open Maps
Change Legend postion Top or Bottom
On Legend panel click checkbox "Single Row Legend"
Once checkbox is ON hover to legend items. the cursor should be pointer.
Before it was mouse pointer.
> [DEV9708] Update cursor pointer

- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/components/DashboardFilters/dashboardfilter.styles.css
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/loadAPIFilters.ts
- packages/dashboard/src/helpers/tests/apiFilterHelpers.test.ts
- packages/dashboard/src/helpers/tests/loadAPIFiltersWrapper.test.ts
testing steps are in the original ticket
> enhancement fix [dev-9440] dropdown loaders

- packages/chart/src/components/Axis/Categorical.Axis.tsx
- packages/chart/src/hooks/useMinMax.ts
> Fix:[dev-9922] Categorical Axis on Line charts

- packages/chart/src/CdcChart.tsx
- packages/chart/src/helpers/getQuartiles.ts
- packages/core/components/DataTable/helpers/boxplotCellMatrix.tsx
Box plot table issues are fixed. Steps are on the ticket
> Fix:[DEV-9924] Box Plot tables

- packages/map/src/components/UsaMap/components/UsaMap.Region.tsx
Feedback based on comment to carry over some new territory styles to the region map as well
1. Open `components-templates-map--hhs-region-map`
2. Observe border radius matches state map
> Enhancement [DEV-9861] Match region border radius territory shape to state territories

- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/VisualizationRow.tsx
Upload [ardi-reports.json](https://github.com/user-attachments/files/17939963/ardi-reports.json) and navigate to Dashboard Preview
> Enhancement-Fix- Dev-9448 Data Reset Scenario

- packages/core/components/MultiSelect/MultiSelect.tsx
- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/helpers/gatherQueryParams.ts
- packages/core/helpers/queryStringUtils.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/changeFilterActive.ts
- packages/dashboard/src/helpers/loadAPIFilters.ts
- packages/dashboard/src/helpers/shouldLoadAllFilters.ts
- packages/dashboard/src/helpers/tests/apiFilterHelpers.test.ts
- packages/dashboard/src/helpers/tests/loadAPIFiltersWrapper.test.ts
- packages/dashboard/src/helpers/tests/shouldLoadAllFilters.test.ts
testing in structions are in the ticket. they require access to the chronic api. 
> Enhancement: [dev 9724] fetch on load

- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
- packages/dashboard/src/helpers/filterData.ts
Reverts CDCgov/cdc-open-viz#1688
Suggest to revert this because it's blocking WCMS devs
> Revert "[DEV-9624] Update filters reset label logic"

- packages/chart/src/components/LinearChart.tsx
> [DEV-9822] continue work on anchors

- packages/chart/src/components/LinearChart.tsx
No data throws error
1. Open config that loads with no data at first
2. Confirm no error is thrown
> Fix [DEV-9961] no data throws bug

- packages/chart/index.html
- packages/chart/src/_stories/Chart.stories.tsx
- packages/chart/src/_stories/_mock/line_chart_dynamic_ci.json
- packages/chart/src/_stories/_mock/line_chart_non_dynamic_ci.json
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/LineChart/index.tsx
> [DEV-9840-2] DEV-9840 > Use dynamic data series

- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/dashboard/src/helpers/tests/reloadURLHelpers.test.ts
testing instructions are in the ticket but require access to chronic api
> Fix [dev-9973] dashboard filter row association

- packages/chart/src/components/LineChart/helpers.ts
- packages/chart/src/components/LineChart/index.tsx
Removed  this functionality  from Line charts. We will work on in for next sprint.
> FIX:[DEV-9662a] Appended Text Behind Legend

- packages/core/components/Legend/Legend.Gradient.tsx
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/data/initial-state.js
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/shouldLoadAllFilters.ts
- packages/dashboard/src/helpers/shouldLoadUnfilteredDataset.ts
- packages/dashboard/src/helpers/tests/shouldLoadAllFilters.test.ts
- packages/dashboard/src/helpers/tests/shouldLoadUnfilteredDataset.test.ts
testing steps are in the ticket and require connection to Chronic API
> Fix [dev-9970] dashboard long page load time

- packages/map/src/_stories/CdcMap.Patterns.stories.tsx
- packages/map/src/components/UsaMap/components/Territory/Territory.Rectangle.tsx
- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
> [DEV-10021] State Maps > update pattern keys and background color props

- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
> [DEV-9726b] State Maps > Update stroke widths

- packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
testing steps are in the ticket and require chronic api access
> Fix: [dev-9943] line chart values not displaying

- packages/map/index.html
- packages/map/src/components/UsaMap/components/UsaMap.Region.tsx
> [DEV-9726d] Region Map > Border Color and Stroke Updates

- packages/map/src/scss/filters.scss
Fixes the issue described in the ticket.
Use the map config attached to the ticket, ensure gap is gone.
> [DEV-10023] Remove filter gap

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/BoxPlot/BoxPlot.tsx
- packages/core/components/DataTable/DataTable.tsx
1.Updated Box plot max calculation logic. 
2.Added unique key to JSX return.
Fixed small bugs.
> FIX: [DEV-9924a]-Box Plot: Table Issues

- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/addValuesToDashboardFilters.ts
Scenario: upload attached dev-10027.json config attached to the ticket. navigated to dashboard preview. 
1) Change the option under Location.
Expected: you should see the "Please complete your selections to continue" message.
2) Click "Submit"
Expected: you should see data in the table respective to the Location you've selected.
> Fix: [dev-10027] apply button not working

- packages/dashboard/src/components/VisualizationRow.tsx
> 4.24.12 Hotfixes from dev

- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/DashboardContext.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/helpers/shouldLoadAllFilters.ts
- packages/dashboard/src/helpers/tests/shouldLoadAllFilters.test.ts
- packages/dashboard/src/store/dashboard.reducer.ts
Testing instructions are in the ticket. It requires Chronic api access.
If I could get a general review of the code from anyone without access. 
> FIX: [dev-10074] Dashboard autoloading issues

- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
> Fix/Dev-10076 Parent filter section labeled incorrectly (#1770)

- packages/chart/src/components/BrushChart.tsx
- packages/chart/src/scss/main.scss
Basically added to format dates on Irish slider handler. Small changes.
> FIX:[DEV-10056]-Brush slider -- start / end dates don't correlate to chart

- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/helpers/reloadURLHelpers.ts
- packages/dashboard/src/helpers/shouldLoadUnfilteredDataset.ts
testing steps are in the ticket and require Chronic api access
> fix [dev-10077] footnotes filters not applying

- packages/core/components/Footnotes/FootnotesStandAlone.tsx
- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/helpers/shouldLoadAllFilters.ts
- packages/dashboard/src/helpers/tests/shouldLoadAllFilters.test.ts
- packages/dashboard/src/helpers/tests/shouldLoadUnfilteredDataset.test.ts
this also cleans up some test cases.
> Fix for footnotes wp test [dev-10077] [dev-10074]

- packages/core/components/EditorPanel/DataTableEditor.tsx
> fix missing labels on table editor caused by [dev-9864]

- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/components/Widget.tsx
Fixed error that prevented page from loading
Scenario: Upload [dev-10114-config.json](https://github.com/user-attachments/files/18154022/dev-10114-config.json) and open Configuration. Then open the Filters Dropdown Editor.
Expected: Page loads and there is no dataUrl error
> Hot Fix Dev-10114 & Dev-10115 Removed multidashboard and dataUrl Errors

- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
testing steps are in the ticket
> Hotfix: dev-9951 usedby not showing saved usedby selections

- packages/dashboard/examples/ed-visits-county-file.json
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/helpers/shouldLoadAllFilters.ts
point the dashboard index.html to `/examples/ed-visits-county-file.json`
run `yarn workspace @cdc/dashboard run start`
expected: you should see the second dropdown populate with options. Switching to Hawaii should give you multiple counties in the second dropdown and changing the county should change the graph below.
> fix [dev-10114] data filters not populating

- packages/dashboard/src/helpers/shouldLoadUnfilteredDataset.ts
load: [dengue.json](https://github.com/user-attachments/files/18170590/dengue.json)
navigate to preview. 
expected: Data should load on page load
> hot-Fix [dev-10114] caused by [dev-9970] data filters not populating

- packages/chart/src/types/ChartConfig.ts
- packages/core/components/DataTable/helpers/mapCellMatrix.tsx
- packages/core/helpers/displayDataAsText.ts
- packages/core/types/Version.ts
- packages/dashboard/src/types/DashboardConfig.ts
- packages/data-bite/src/types/Config.ts
- packages/map/index.html
- packages/map/src/CdcMap.tsx
- packages/map/src/components/CityList.tsx
- packages/map/src/components/DataTable.tsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
- packages/map/src/components/Legend/components/Legend.tsx
- packages/map/src/components/Modal.tsx
- packages/map/src/components/UsaMap/components/UsaMap.County.tsx
- packages/map/src/components/UsaMap/components/UsaMap.Region.tsx
- packages/map/src/components/UsaMap/components/UsaMap.SingleState.tsx
- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
- packages/map/src/components/WorldMap/WorldMap.tsx
- packages/map/src/context.ts
- packages/map/src/helpers/closeModal.ts
- packages/map/src/helpers/handleMapAriaLabels.ts
- packages/map/src/helpers/navigationHandler.ts
- packages/map/src/helpers/toTitleCase.ts
- packages/map/src/helpers/validateFipsCodeLength.ts
- packages/map/src/hooks/useTooltip.ts
- packages/map/src/types/MapConfig.ts
- packages/map/src/types/MapContext.ts
- packages/markup-include/src/types/Config.ts
- packages/waffle-chart/src/types/Config.ts
- Remove supported geo data (ie. supportedTerritories) out of context and directly import
- Move closeModal to map/helpers
- Move validateFipsCodeLength to map/helpers
- Move displayDataAsText to core/helpers
- Move navigationHandler to map/helpers
- General typescript, spelling, and sorting enhancements
> [map-functions] map helper function refactors

- packages/editor/src/samples/valid-data-map.csv
> [DEV-10041] update sample data

- packages/core/helpers/formatConfigBeforeSave.ts
testing steps are in the ticket. 
> PATCH Fix: [dev-10127] filters saving current active value

- packages/core/components/Filters/Filters.tsx
- packages/map/src/CdcMap.tsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
- packages/map/src/types/MapConfig.ts
1) Regression test: Open storybook and navigate to Templates/ Map/ Filterable Map.
Expected: you should be able to filter the map.
2) Open CDC Editor and select dashboard filter.
3) Select the 'United States: State sample Data' example data file and click configure visualization.
4) drag and drop a US map widget to the visualization panel & map the data source you just added.
5) click the tools icon. Under columns map Geography to State and Data to Rate.
Expected: Map should show up with data.
6) add a new filter.
7) select: nested filter. make State the grouping and Rate the sub grouping.
Expected: a nested dropdown should show up with rates mapped for each state. Changing the nested dropdown should change the map data.
- I have commented my …
> PATCH Fix: dev-9866 nested dropdown maps

- packages/chart/src/components/LinearChart.tsx
- packages/core/styles/_typography.scss
Conform spacing and font sizes to [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
Open a chart and check fonts elements and spacing against UX document
> Enhancement [DEV-10065] chart font sizing and spacing

- packages/core/components/MediaControls.jsx
> [DEV-10122b] adjust map button

- packages/chart/src/CdcChart.tsx
- packages/core/components/DataTable/DataTable.tsx
Default sort date data newest to oldest
1. Open chart with date axis
2. confirm sorting is newest to oldest
> Enhancement [DEV-10198] sort date data newest to oldest

- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/components/Legend/helpers/getLegendClasses.ts
confirm line legend has no margin left
> fix [DEV-10065]: line legend has no margin

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Annotations/components/AnnotationDraggable.tsx
- packages/chart/src/components/Annotations/components/AnnotationDropdown.tsx
- packages/chart/src/components/Axis/Categorical.Axis.tsx
- packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart/components/BarChart.StackedHorizontal.tsx
- packages/chart/src/components/DeviationBar.jsx
- packages/chart/src/components/ForestPlot/ForestPlot.tsx
- packages/chart/src/components/Legend/helpers/index.ts
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/components/PairedBarChart.jsx
- packages/chart/src/components/ZoomBrush.tsx
- packages/chart/src/hooks/useBarChart.ts
- packages/chart/src/scss/main.scss
- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/DataTable/components/ExpandCollapse.tsx
- packages/core/helpers/cove/fontSettings.ts
- packages/core/helpers/getTextWidth.ts
- packages/core/styles/_global-variables.scss
- packages/core/styles/_global.scss
- packages/core/styles/filters.scss
- packages/core/styles/v2/components/button.scss
- packages/dashboard/src/components/CollapsibleVisualizationRow.tsx
- packages/editor/src/scss/main.scss
- packages/map/src/CdcMap.tsx
- packages/map/src/components/Annotation/AnnotationDropdown.tsx
- packages/map/src/components/Legend/components/index.scss
- packages/map/src/scss/filters.scss
- packages/map/src/scss/main.scss
Conform fonts and spacing to [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
Inspect and compare below-chart spacing to UX document.
> [DEV-10065] Clean up fonts & spacing

- packages/core/components/Filters/Filters.tsx
- packages/core/styles/_global-variables.scss
- packages/core/styles/filters.scss
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
- packages/dashboard/src/components/DashboardFilters/dashboardfilter.styles.css
- packages/dashboard/src/components/VisualizationRow.tsx
- packages/dashboard/src/scss/main.scss
Conform dashboard fonts and spacing to [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
Inspect and compare dashboard fonts/spacing to UX document.
> [DEV-10065] Improve spacing for dashboards

- packages/chart/src/CdcChart.tsx
- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/components/Legend/Legend.Suppression.tsx
- packages/chart/src/components/Legend/helpers/index.ts
- packages/chart/src/types/ChartContext.ts
Conform legend fonts and spacing to [Fonts, Spacing, and Elements in Charts [UX-1249]](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3&g=15)
Move legend to top, ensure spacing above and below matches specs.
> [DEV-10065] Improve spacing for top legends

- packages/dashboard/src/components/Column.tsx
- packages/dashboard/src/components/Widget.tsx
> [DEV-9377] Add titles to dashboard widgets

- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/isOlderVersion.ts
- packages/core/helpers/useDataVizClasses.ts
- packages/core/helpers/ver/4.24.11.ts
- packages/core/helpers/ver/4.25.1.ts
- packages/core/helpers/ver/versionNeedsUpdate.ts
- packages/map/index.html
- packages/map/src/CdcMap.tsx
- packages/map/src/_stories/CdcMap.stories.tsx
- packages/map/src/_stories/_mock/example-city-state.json
- packages/map/src/components/Annotation/Annotation.Draggable.tsx
- packages/map/src/components/Annotation/AnnotationDropdown.tsx
- packages/map/src/components/DataTable.tsx
- packages/map/src/components/Legend/components/Legend.tsx
- packages/map/src/components/Legend/components/LegendItem.Hex.tsx
- packages/map/src/components/Modal.tsx
- packages/map/src/helpers/applyColorToLegend.ts
- packages/map/src/hooks/useResizeObserver.ts
> [resize-observer] fix resize observer issue

- packages/chart/src/CdcChart.tsx
> [add-deps] add deps

- packages/chart/src/index.jsx
- packages/dashboard/src/components/Column.tsx
- packages/dashboard/src/index.tsx
- packages/data-bite/src/index.jsx
- packages/editor/src/index.jsx
- packages/filtered-text/src/index.jsx
- packages/map/src/index.jsx
- packages/markup-include/src/index.jsx
- packages/waffle-chart/src/CdcWaffleChart.tsx
- packages/waffle-chart/src/index.jsx
The cove-main styles are imported in various environments. However, for folks that don't use them in those environments we either need to share that they need to import this style into their header, or use this hotfix. 
Please do a rough test on visual styles for each package
> [DEV-10226] fixes visualizations outside of environments

- packages/core/components/DataTable/DataTableStandAlone.tsx
- packages/core/components/Filters/Filters.tsx
- packages/core/helpers/addValuesToFilters.ts
- packages/map/src/CdcMap.tsx
[Replace With Ticket Number]
1) upload 
[dev-10201.json](https://github.com/user-attachments/files/18402558/dev-10201.json)
2) navigate to dashboard preview and wait for page to load.
Expected: Response dropdown should have No selected. Hovering over the Washington state tooltip should also say No for response.
3) Change Response to Yes
Expected: respective tooltips should say Yes for response.
4) Navigate to the Table tab.
Expected: there should only be one row under each table category grouping. 
> PATCH Fix [dev-10201] Visualization Filters don't filter map correctly

- packages/map/src/CdcMap.tsx
> Patch fix/dev-10201 debug

- packages/core/helpers/formatConfigBeforeSave.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/components/Header/Header.tsx
- packages/dashboard/src/store/dashboard.actions.ts
- packages/dashboard/src/store/dashboard.reducer.ts
Scenario: upload 
[DEV-10289-cessation-20250113.json](https://github.com/user-attachments/files/18429782/DEV-10289-cessation-20250113.json)
1. Open data visualization
2. Choose Compare Years - Dashboard Description - after a few seconds modules inner content disappears
3. Choose Dashboard Preview the error appears error "Something went wrong with component CdcDashboard." 
*note that the issue may not happen if you don't switch tabs quickly. There's an async api call that is setting the wrong visualizations*
> Fix [dev-10289] multi tab switching

- packages/core/components/Filters/Filters.tsx
scenario: upload 
[dev-10311.json](https://github.com/user-attachments/files/18444867/dev-10311.json)
1) in second dropdown make a different selection
Expected: The map should not change. The nested filter should reflect the selected value.
2) click apply.
Expected: The map should change
> Fix dev-10311 nested viz filters apply

- packages/chart/src/CdcChart.tsx
> [fix-join] add spacing for join function

- packages/core/components/NestedDropdown/nesteddropdown.styles.css
- packages/core/styles/base.scss
- packages/markup-include/src/scss/main.scss
Cleans up some issues found in regression testing.
> Fix [DEV-10065] Regression fixes

- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
Testing steps are in the ticket
> Fix [dev-10359] nested dropdown part2

- packages/dashboard/src/helpers/apiFilterHelpers.ts
> fix [dev-10368] year string number comparison

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
1. Open editor
2. Find axis label field
3. Confirm tooltip
> Enhancement [DEV-10066] add tooltip for axis label character limit

- packages/chart/src/CdcChart.tsx
Fixed issue when user skips Yes & No button on editor
> [Fix-load-issue] Fixed load issue on editor

- packages/core/components/Filters/Filters.tsx
Makes filter section full width.
Load the config attached to the ticket. On `dev`, the filter pills will be squished, on this branch they should be wide enough.
> Fix [DEV-10345] Fix filter pill width

- packages/core/components/NestedDropdown/nesteddropdown.styles.css
> Fix [DEV-10065] Adjust nested dropdown padding

- packages/core/components/DataTable/helpers/customSort.ts
date-time sort not working correctly
1. open or create chart with date-time axis
2. sort date column
> Fix [DEV-10198] date-time sort not working correctly

- packages/core/helpers/addValuesToFilters.ts
- packages/core/helpers/tests/addValuesToFilters.test.ts
Scenario: upload: 
[dev-10309.json](https://github.com/user-attachments/files/18508953/dev-10309.json)
1) navigate to the preview page. 
2) change first dropdown 
Expected: every change in the first dropdown should cause the option in the second dropdown to change.
> fix [dev-10309] viz filter parent apply

- packages/core/helpers/addValuesToFilters.ts
> hot-Fix / [dev-10309] viz filter parent filters apply

- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/components/EditorPanel/components/Panels/Panel.Visual.tsx
- packages/chart/src/helpers/getColorPalette.js
> [fix-colorPalette] fix color palette issiue

- packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
- packages/core/helpers/addValuesToFilters.ts
> fix [dev-10397] viz filter order

- packages/chart/src/components/Legend/helpers/createFormatLabels.tsx
> FIX : [DEV-10331]-Reverse Legend Labels - Right and Left

- packages/chart/src/hooks/useScales.ts
> FIX:[DEV-10351] Apply Button Jumps Chart off Axis

- packages/chart/src/CdcChartComponent.tsx
> [prepare-data] update prepare data function

- packages/dashboard/src/CdcDashboard.tsx
- packages/dashboard/src/store/dashboard.reducer.ts
testing steps are in the ticket.
> fix [dev-10471] [dev-10413] issues saving changes on dashboard

- packages/dashboard/src/helpers/loadAPIFilters.ts
> fix [dev-10455] error notices repeating after 500 request

- packages/chart/examples/feature/tests-non-numerics/example-combo-bar-nonnumeric.json
- packages/chart/index.html
- packages/chart/src/CdcChartComponent.tsx
> [fix-line-chart] Fix

- packages/dashboard/index.html
- packages/editor/src/scss/main.scss
> [DEV-9625] Remove padding on intro text

- packages/dashboard/src/helpers/apiFilterHelpers.ts
> Fix [dev-10491] set by query param

- packages/chart/src/hooks/useBarChart.ts
testing steps are in the ticket
> fix [dev-10157] bar chart dynamic series tooltip

- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
- packages/chart/src/components/BarChart/components/BarChart.jsx
- packages/chart/src/components/BarChart/components/context.tsx
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/helpers/isConvertLineToBarGraph.ts
- packages/chart/src/hooks/useMinMax.ts
https://websupport.cdc.gov/browse/DEV-10450
In the ticket
> Fix/Dev-10450 Convert to bar option not working for Dynamic Series

- packages/chart/src/_stories/Chart.DynamicSeries.stories.tsx
- packages/chart/src/components/LineChart/components/LineChart.Circle.tsx
Run storybook
open Templates/Chart/Dynamic Series/Line Show Points
Expected: there should be three lines, the top line should have a break in it. There should be dots on the lines. the first dot on the top line which is disconnected should be larger than the rest of the dots.
open Templates/Chart/Dynamic Series/ Line Hover Points
Expected: There should be three lines and dots should show up on the lines when you hover.
> Fix [dev-10439] chart dots in dynamic series

- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/components/BrushChart.tsx
- packages/chart/src/components/Legend/helpers/index.ts
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/scss/main.scss
Fixed issues with brush slider. IT is very hard to test it since the issue only on wcms.
> FIX : [DEV-10329] Brush Slider Malfunction for Long Years

- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
> fixed merge conflict between dev-8488 and dev-10421

- packages/chart/index.html
- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/ConfigContext.tsx
- packages/chart/src/components/BrushChart.tsx
- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/helpers/getColorScale.ts
- packages/chart/src/hooks/useBarChart.ts
- packages/chart/src/store/chart.actions.ts
- packages/chart/src/store/chart.reducer.ts
> Refactor:[DEV-9730] Implement reducer

- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/components/LineChart/index.tsx
- packages/core/helpers/DataTransform.ts
Testing file provided in the ticket.
> FIX:[DEV-9629] Dynamic Data Series: Tall Data issues with first value being null

- packages/core/components/DataTable/DataTable.tsx
- packages/dashboard/src/scss/main.scss
Testing steps are on ticket. [https://websupport.cdc.gov/browse/DEV-9932](https://websupport.cdc.gov/browse/DEV-9932)
> Fix: DEV-9932 Table styling spacing issues

- packages/dashboard/src/helpers/getFilteredData.ts
Scenario: Upload [dev-9744-config.json](https://github.com/user-attachments/files/18801237/dev-9744-config.json) and open Dashboard Preview
Expected: A single dashboard filter with a GO! button
Select Alabama from the dropdown and Click GO!
Expected: The Chart below will populate with Horizontal bars
> Fix: DEV-10557 IndexOf error when using Dashboard filters

- packages/core/components/NestedDropdown/NestedDropdown.tsx
- packages/core/components/NestedDropdown/nesteddropdown.styles.css
Testing steps in ticket
(https://websupport.cdc.gov/browse/DEV-10446)
> FIX: DEV-10446 Nested Dropdown arrows not working

- packages/core/components/EditorPanel/Inputs.tsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
- Adds a useEffect in Inputs.tsx when the column dropdown is changed to show the proper label name
1. Create a new USA map
2. Set the geo column to be the state column
3. Set the primary column to be the rate column
4. The data label input should change when the primary column is updated.
- Updates a number of select dropdowns on maps to be the core component select dropdowns
> [DEV-10587] update col label on changes

- packages/chart/src/components/DeviationBar.jsx
Updateed text aligment issue on Deviation bar.
> FIX: [DEV-10573] Deviation Label On the Bar

- packages/core/helpers/queryStringUtils.ts
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersWrapper.tsx
- packages/dashboard/src/helpers/changeFilterActive.ts
Testing instructions are in the ticket and require network access
> Fix: [dev-10600] Query Params not updating on filter select properly

- packages/core/helpers/queryStringUtils.ts
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/DashboardFiltersEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/NestedDropDownDashboard.tsx
- packages/dashboard/src/helpers/apiFilterHelpers.ts
- packages/dashboard/src/helpers/changeFilterActive.ts
testing steps are in the ticket.
> fix [dev-10601] url filter nested dropdown params

- packages/core/components/DataTable/DataTable.tsx
- packages/dashboard/src/components/CollapsibleVisualizationRow.tsx
Scenario: Upload 
[test-in-percent-test-positivity-in-usa 2.json](https://github.com/user-attachments/files/18949969/test-in-percent-test-positivity-in-usa.2.json) and open Dashboard Preview.
Expected: There is a Chart with a description below it and a data table below the description. There is a space between the description and the data table
> Hot fix/dev 9932 multiviz h4 adding white space

- packages/chart/src/store/chart.reducer.ts
> [viewport-bug] fix spelling

- packages/chart/src/components/LinearChart.tsx
Fixed issue with undefined tooltips  rendering emty box.
> [tooltips-issue] Fixed issue with undefined tooltips

- packages/chart/src/CdcChartComponent.tsx
- packages/chart/src/components/EditorPanel/helpers/updateFieldRankByValue.ts
> [clean-CI-keys] add CI keys to cleanup

- packages/core/components/DataTable/DataTable.tsx
> [hotfix] Add table margins correctly

- packages/chart/src/store/chart.reducer.ts
> [viewport-issue] Fixed spelling

- packages/core/components/AdvancedEditor/AdvancedEditor.tsx
Updates the advanced settings links to go to the right url and adds the pointer cursor.
> [DEV-10422] update COVE help links

- packages/chart/src/helpers/isConvertLineToBarGraph.ts
testing steps are in the ticket. the issue does not occur locally so need to test after deployment.
> Fix [dev-10602] convert line to barchart

- packages/core/components/EditorPanel/Inputs.tsx
- packages/core/components/Filters/Filters.tsx
- packages/core/components/elements/Button.jsx
- packages/core/styles/_global-variables.scss
- packages/core/styles/_global.scss
- packages/core/styles/filters.scss
- packages/core/styles/v2/components/button.scss
- packages/core/styles/v2/themes/_color-definitions.scss
- packages/dashboard/src/components/DashboardFilters/DashboardFilters.tsx
[dropdown styles](https://uxpreview.cdc.gov/84WBNF/?id=txxh1d&p=dropdowns)
[filter button styles](https://uxpreview.cdc.gov/3GE5EW/?id=6cg4ol&p=fonts__spacing__and_elements_in_charts__ux-1249_&sc=3)
1. Run `/examples/filtered-dash.json` or flip through Dashboard stories
2. Check against UX document
> feature [DEV-10067]: update dropdown and buttons styles to match UX document

- packages/core/helpers/labelHash.ts
- packages/dashboard/src/components/Column.tsx
- packages/dashboard/src/components/DashboardFilters/DashboardFiltersEditor/components/FilterEditor.tsx
- packages/dashboard/src/components/Row.tsx
- packages/dashboard/src/components/Toggle/Toggle.tsx
- packages/dashboard/src/components/VisualizationsPanel/VisualizationsPanel.tsx
- packages/dashboard/src/components/Widget/Widget.tsx
- packages/dashboard/src/components/Widget/widget.styles.css
- packages/dashboard/src/scss/grid.scss
- packages/dashboard/src/store/dashboard.actions.ts
- packages/dashboard/src/store/dashboard.reducer.ts
- packages/dashboard/src/types/ConfigRow.ts
> [DEV-10286] allow name change on toggles

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
> [DEV-10371] fix editor setting not showing on bump charts

- packages/chart/src/components/LinearChart.tsx
--
</body></html></div>
</body>
</html>
Scenario: Upload [explore-by-location-private-2025-02-26.json](https://github.com/user-attachments/files/19030716/explore-by-location-private-2025-02-26.json) and openDashboard Preview 
Expected: There is a row of filters.
1. Use the following items for the 1st row of Dashboard level filters and click View Results:
Dataset: Nationwide
Location: States - California
Class: Health Care Access/Coverage
Topic: Last Checkup
Year: 2022
Question: About how long has it been since you last visited a doctor for a routine checkup?
Expected: Another row of filters appear and also a bar graph
2. Change the View By dropdown to Household Income
Expected: The bar graph will change and there will be a bar graph with the xAxis showing different categories of time. The …
> Fix: [NEW-50346] Bug-Vertical Bar Chart Date/Category Axis Tick Rotation

- packages/core/components/EditorPanel/VizFilterEditor/VizFilterEditor.tsx
- packages/core/helpers/addValuesToFilters.ts
- packages/map/examples/hex-colors.json
- packages/map/index.html
- packages/map/src/CdcMap.tsx
Create a one off map or chart with a filter.
On the filter change the default value to show.
Save the config and refresh the page to verify the default filter value is shown
> [DEV-10609] work on default filter value for maps and charts

- packages/chart/src/components/LinearChart.tsx
Open Combo chart and add Area chart
Before : there was a shadow cause in COmbo chart both Area stacked and Area regular was rendefed
> FIX: [DEV-50351] Fix if statement for Area chart

- packages/chart/src/data/initial-state.js
- packages/core/components/DataTable/DataTable.tsx
- packages/core/components/DataTable/helpers/mapCellMatrix.tsx
- packages/core/components/DataTable/helpers/tests/mapCellMatrix.test.ts
- packages/core/components/EditorPanel/DataTableEditor.tsx
- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/ver/4.25.3.ts
- packages/core/helpers/ver/tests/versionNeedsUpdate.test.ts
- packages/core/types/General.ts
- packages/core/types/Table.ts
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/dashboard/src/helpers/getVizConfig.ts
- packages/map/src/CdcMap.tsx
- packages/map/src/components/DataTable.tsx
- packages/map/src/components/EditorPanel/components/EditorPanel.tsx
- packages/map/src/data/initial-state.js
- packages/map/src/helpers/formatLegendLocation.ts
- packages/map/src/helpers/tests/formatLegendLocation.test.ts
- packages/map/src/types/MapConfig.ts
Scenario: run storybook locally.
1) open Pages/Dashboard/Regression API Filters Map
2) toggle edit mode.
3) navigate to the map editor.
4) under Data Table accordion check the 'Show Data Table' Dashboard Filters
5) check 'Show CSV Download Link'
6) check 'Download Only Visible Data'
7) navigate back to dashboard preview.
8) click 'Download Data CSV' 
Expected: You should receive a downloaded CSV with a column corresponding to each associated Dashboard Filter and also a column for each of the columns in the data table.
9) Repeat steps 3-8, except uncheck the 'Download Only Visible Data' in step 6
Expected: You should receive a downloaded CSV with a column corresponding to add data in the api response.
10) Open Pages/Dashboard/Regression API Filters Chart and repeat steps 2-9
- I have added …
> [dev-10412] CSV download enhancement

- packages/data-bite/src/CdcDataBite.tsx
- packages/data-bite/src/components/EditorPanel.jsx
- packages/data-bite/src/data/initial-state.js
- packages/data-bite/src/types/Config.ts
Open Data bite
On general panel under title text field there is new checkbox "Show title" which is checked by defrault
It toggles title of the component
Before it was "hide title" and inside visual panel
now : moved to general panel and updated name
> Feature:[DEV-10447a] update show title on Data bite

- packages/chart/src/CdcChartComponent.tsx
> Fix: [dev-10575] chart cove update worker

- packages/dashboard/src/components/DataDesignerModal.tsx
- packages/dashboard/src/components/Widget/Widget.tsx
This is fixes a Dashboard regression
upload 
[4-25-03-api-dash.json](https://github.com/user-attachments/files/19343432/4-25-03-api-dash.json)
1) navigate to dashboard preview. 
2) drag and drop a table viz to the viz panel.
3) map the only data source to this table.
4) click the tools icon to edit the table.
Expected: After a couple seconds the table should populate with some sample data.
> fix2 [dev-10575] performance improvement: fixed data loading issues

- packages/chart/src/components/Legend/LegendGroup/LegendGroup.styles.css
- packages/chart/src/components/Legend/LegendGroup/LegendGroup.tsx
> [update-css-file] rename file extension

- packages/map/src/components/UsaMap/helpers/shapes.ts
Instead of backing up whole code for DEV0-10007 we giving another shot updating the scale sizes to lower amount to see if we hit it. here is pic for value(size) 5 :
> REFIX:[DEV-10007a] Update GeoCode shapes scale values

- packages/chart/src/components/Legend/Legend.Component.tsx
- packages/chart/src/helpers/dataHelpers.ts
add dynamicCategory to seriesWithData logic.
1. open config that used "dynamicCategory" key
2. ensure that legend items show
> Fix [50339]: add dynamicCategory

- packages/chart/index.html
- packages/chart/src/_stories/Chart.stories.tsx
- packages/chart/src/_stories/_mock/barchart_labels.mock.json
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
> [fix-CI-labels] Fix CI labels on bars

- packages/chart/src/CdcChartComponent.tsx
Removed right side padding from Spark Line
> FIX :[DEV-10142] Remove SparkLine right padding

- .github/workflows/reject_scss_files.yml
Adds new workflow with checks for new scss files and fails if there are any new ones: 
> Workflow: Prevent new SCSS files

- packages/chart/src/components/BarChart/components/BarChart.Horizontal.tsx
- packages/chart/src/components/BarChart/components/BarChart.Vertical.tsx
- packages/chart/src/components/BarChart/helpers/index.ts
Open Vertical/Horizontal regular bar chart.
Update dataset value to "ABC" or zero( 0) to see missing bars.
In General Panel turn on checkboxes for zero value and missing data values to see bars that are missing
on visual panel turn on Bars Border
Result : Bars with missing values or zero values or suppressed values should not get any borders as shown on the below image:
> FIX:[DEV-50467] Remove bar Border from supressed & missing bars

- packages/core/helpers/coveUpdateWorker.ts
- packages/core/helpers/ver/4.25.3.ts
seems like I missed actually adding the migration.
> Patch fix/dev-10412 csv download enhancement

- packages/dashboard/src/helpers/reloadURLHelpers.ts
Scenario: upload 
[footnote-filters.json](https://github.com/user-attachments/files/19540366/footnote-filters.json)
and navigate to dashboard preview
1) Select: United States, DC & Territories, Mental Health, and Frequent mental distress
2) On Trends over Time graph/table, select:
Age Group = 50-64 years
Demographic= Overall
3) Go to table view
4) See footnote symbols in the COVE table vs footnotes displaying below chart
Expected: For this particular combination, we only need the footnote "* Fewer than 50 states reporting" to display, as that is the only relevant footnote for the data in the table. 
> Fix [new-50392] footnotes filtering

- packages/dashboard/Dynamic_Data.md
- packages/dashboard/src/CdcDashboardComponent.tsx
- packages/dashboard/src/types/DataSet.ts
Scenario: add 
[mirror-test.json](https://github.com/user-attachments/files/19473137/mirror-test.json)
to a index.html file in the dashboard package and start dashboard package.
Expected: The page should load with a single row of data.
1) add the following to the url and reload: `?$d=W3siYSI6MSwiYiI6OTI0LjY2LCJjIjoxMC4zMywiZCI6WzY2LDY1LjAxLDAsMCwwLDAsMCwwLDAsMCwwXSwiZSI6MTMxLjAxLCJmIjo0My4yMzMyOTk5OTk5OTk5OSwiZyI6NDEuOTc0MDc3NjY5OTAyOTA0LCJoIjo2NzcuNTg5LCJpIjo2NTcuODUzMzk4MDU4MjUyNH0seyJhIjoyLCJiIjo4NTQuOTk2MTE1NTk5OTk5OSwiYyI6MjEuNzQzOTQyNzQ5LCJkIjpbNjEuMDI3NTYsNjAuMTEyMTQ2Niw2NC4wMzQ4NSwwLDAsMCwwLDAsMCwwLDAsMF0sImUiOjE4NS4xNzQ1NTY2MDAwMDAwMiwiZiI6NjEuMTA3NjAzNjc4MDAwMDA0LCJnIjo1Ny41OTk3NzcyNDM4NDk1NjYsImgiOjg3Ni4yNzUzNTk3NCwiaSI6ODI1Ljk3MzU2OTM2NTYzM30seyJhIjozLCJiIjo3OTAuNTgwNzA4MjUwNjk …
> feature [new-50378] dashboard loadQueryParam

- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
Nudges map offset labels per [UX recommendations](https://cdc.sharepoint.com/teams/OADC-DPA-DMB-WCMS-TPVisualizationsProject/Shared%20Documents/WCMS-TP%20Visualizations%20Project/COVE/Data%20Viz.one#Map%20Fonts,%20Spacing,%20and%20Patterns&section-id=%7B25C30AAB-4393-4D46-BC0E-E13962464226%7D&page-id=%7BE0DE456D-D45C-4AB7-A685-5FA2C3D880FF%7D&end).
Screenshots below.
Load the attached config, confirm that offset labels are as pictured.
[wastewatermap.json](https://github.com/user-attachments/files/19572595/wastewatermap.json)
Before:
After:
> Enhancement [NEW-50386] Nudge offset labels

- packages/core/styles/_global-variables.scss
- packages/map/src/components/UsaMap/components/TerritoriesSection.tsx
- packages/map/src/scss/map.scss
Updates mobile territory styles to match [UX recommendations](https://cdc.sharepoint.com/teams/OADC-DPA-DMB-WCMS-TPVisualizationsProject/Shared%20Documents/WCMS-TP%20Visualizations%20Project/COVE/Data%20Viz.one#Map%20Fonts,%20Spacing,%20and%20Patterns&section-id=%7B25C30AAB-4393-4D46-BC0E-E13962464226%7D&page-id=%7BE0DE456D-D45C-4AB7-A685-5FA2C3D880FF%7D&end).
Load the attached config, ensure territory styles match UX specs on mobile.
[wastewatermap.json](https://github.com/user-attachments/files/19606762/wastewatermap.json)
> Enhancement [NEW-50388] Mobile territory styling

- .github/pull_request_template.md
- .github/workflows/pr_template_validation.yml
- Removes header from pr template file
- Removes ticket number and checks for the summary section
- Decided not to add checks for ticket numbers since some PRs don't have them
Review removals
> PR Template Updates

- packages/core/helpers/ver/4.25.4.ts
- packages/core/helpers/ver/tests/4.25.4.test.ts
**No Ticket**
Remove redundant multidashboard updater
> fix [coveUpdateWorker] remove redundant multidashboard updater

- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
Use old data when legendMemo hasn't been updated yet
1. open [wastewatermap.json](https://github.com/user-attachments/files/19707726/wastewatermap.json) in maps package.
2. change tabs
3. confirm map does not flash
> fix: map flash on tab change

- .eslintrc.json
- packages/chart/src/CdcChartComponent.tsx
Backed up useEffect dependency. Add new rule for Eslint and cleared console.
> FIX : [DEV-10586c] - Update eslint and useEffect

- packages/chart/src/CdcChartComponent.tsx
Pull this branch locally:
git checkout feature/DEV-10586d
2. Backed up changes that i made for prepare data function, since Cailin and Robin reported chart breaks on prod. This should fix it.
> FIX : [DEV-10586d] -update prepareData function to it is default version

- package.json
- packages/core/package.json
- packages/map/examples/hex-colors.json
- packages/map/index.html
- packages/map/src/CdcMapComponent.tsx
- packages/map/src/components/EditorPanel/components/Panels/Panel.PatternSettings.tsx
- packages/map/src/components/UsaMap/components/SingleState/SingleState.CountyOutput.tsx
- packages/map/src/components/UsaMap/components/UsaMap.State.tsx
- packages/map/src/helpers/addUIDs.ts
- packages/map/src/helpers/constants.ts
- packages/map/src/scss/main.scss
- packages/map/src/types/MapConfig.ts
- yarn.lock
[DEV-50435] Map Offset Labels
[DEV-50436] Maps not reading territory labels
[DEV-50437] Patterns Malfunctioning
[DEV-50439] Map Hovers
> [map-release-fixes] multiple tickets

- packages/chart/src/components/LineChart/index.tsx
circle points were removed by unknown reason, added them back.
> FIX : [NEW-50426] - Open Circles are Missing on Line Chart Effect Special Lines

- packages/chart/src/components/BarChart/components/BarChart.StackedVertical.tsx
- packages/chart/src/hooks/useScales.ts
Open Bar chart and add time scale
Turn on Brush slider and use brush on time scale
Update bar thickness to se if bars are overlapping while on brush
Switch to stacked bar chart and do same.
> FIX : [DEV-10140] -Fix brush chart scale

- packages/chart/package.json
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/components/PieChart/PieChart.tsx
- packages/chart/src/hooks/useTooltip.tsx
- yarn.lock
Updated Pie chart
On Dashboards or on Editor open Pie chart. Check for tooltips, decimals, etc.
Before: pie chart was broken due to react spring depreciation
> FIX [NEW-50433]- Pie chart issues

- packages/chart/src/CdcChartComponent.tsx
Attached a file which works on Dashboards. It should render bars on initial load.
Added additial data transform logic inside useEffect otherwise it was not transforming properly.
[dev-10586-rebuild (1).json](https://github.com/user-attachments/files/20212724/dev-10586-rebuild.1.json)
> FIX : [DEV-10586] - add data transform to initial load

- packages/map/index.html
- packages/map/src/_stories/CdcMap.Legend.stories.tsx
- packages/map/src/_stories/_mock/legends/legend-tests.json
- packages/map/src/components/Legend/components/index.scss
- packages/map/src/helpers/generateRuntimeLegend.ts
This pull request includes updates to map legend styling, and improvements to the runtime legend generation logic. The changes focus on enhancing keeping special classes in the legend regardless of the filter applied, and keeping breakpoints the same without re-renders when the legend type is unified.
* `packages/map/src/components/Legend/components/index.scss`: 
- Updated `.legend-container__li` to use `display: flex` with alignment improvements (`align-items: center`, `gap: 0.5em`, etc.) and prevented label wrapping using `white-space: nowrap`.
* `packages/map/src/helpers/generateRuntimeLegend.ts`: 
- Introduced logic to calculate and sort numeric domain values (`domainNums`) for better handling of data sets.
- Removed redundant code for calculating domain numbers and replaced it with a …
> [DEV-10123] enhancment: map legend enhancements

- packages/core/helpers/cove/number.ts
Added auto suffix "%" to pie chart to show it when user click " Show Data Value"
> Format number for Pie chart

- packages/chart/src/components/EditorPanel/EditorPanel.tsx
- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/data/initial-state.js
- packages/chart/src/store/chart.actions.ts
- packages/chart/src/store/chart.reducer.ts
- packages/chart/src/types/ChartConfig.ts
> Revert : [DEV-10351s] - Revert brush chart

- packages/chart/src/components/LinearChart.tsx
> fix hover line show/hide

- packages/chart/index.html
- packages/core/components/DataTable/components/ChartHeader.tsx
- packages/core/components/DataTable/helpers/chartCellMatrix.tsx
- packages/core/components/DataTable/helpers/getChartCellValue.ts
This pull request introduces changes to improve the handling of chart data in the `DataTable` component, particularly around supporting right-axis data and enhancing the `getChartCellValue` function. The changes involve refactoring and adding logic to manage right-axis items more efficiently and ensuring consistent formatting and behavior across the codebase.
* **Introduced `rightAxisItemsMap` for efficient access to right-axis series**: A new map was added to store right-axis items (`dataKey` to item mapping) for better performance and cleaner code. This map is used in `ChartHeader` and `chartCellArray` to determine axis-specific behavior. (`[[1]](diffhunk://#diff-ac1f62828082d56b1d13c55d236392349c5a9acdd8647b778d1d8005c8768fd1R123-R127)`, …
> fix: standalone table chart cell value performance

- packages/dashboard/src/helpers/getVizConfig.ts
Footnotes files was throwing erorr. added lodash to set data properly.
> Handle footnotes.data with lodash

- packages/dashboard/src/CdcDashboardComponent.tsx
the data to set the visualization was not updating do to a stale state.
testing steps provide in ticket.
> Fix [dev-11045] single state override

- packages/chart/src/components/LinearChart.tsx
- packages/chart/src/hooks/useTooltip.tsx
Open Line charts
Add Single series tooltips ON from visual panel
Hover on line points. they suppose to show tooltip for each point.
> FIX : [DEV-8890] - Fix Line chart tooltip hovers for single series

- packages/dashboard/src/helpers/getVizConfig.ts
add formatted data support for multi viz config
> RE-FIX : [DEV11132a] -add support for formatted data

- packages/chart/src/components/Legend/helpers/index.ts
> fix: brush chart > legend bottom

- packages/dashboard/src/CdcDashboardComponent.tsx
[DEV-11035](https://websupport-cdc.msappproxy.net/browse/DEV-11035)
1. open 
[mhdc-flash.json](https://github.com/user-attachments/files/21492959/mhdc-flash.json)
2. click out of a tab and back to the same tab
3. chart should not show flash of unfiltered data
> Fix [DEV-11035] Dashboard flickers unfiltered data

- packages/chart/src/components/Brush/BrushChart.tsx
- packages/chart/src/components/Brush/BrushController.tsx
- packages/chart/src/components/Brush/types.tsx
Added Date values for edges of the brush handlers.
> FIX [DEV-9930] - Add brush chart handlers values

- packages/dashboard/src/helpers/getVizConfig.ts
Open Dashboard with provided config file and toogle filters to see if footnotes are filtering for each components that was used by filters. If filters dont use that component inside used by then it should not filters that component and its footnotes.
[beyhany-2-footnote.json](https://github.com/user-attachments/files/21720330/beyhany-2-footnote.json)
> FIX - [DEV-11176b] -Update Footnotes config to work with filters

- packages/dashboard/src/CdcDashboardComponent.tsx
Review ticket in JIRA. When on a multidashboard, "link to dataset" wasn't linking to anything unless "show all datasets" was checked, which then displayed datasets not on the dashboard. This filters the datatsets to display properly.
- Upload 
[DEV-11072.json](https://github.com/user-attachments/files/21759203/DEV-11072.json)
- Check Dashboard Settings > Show all datasets
- Make sure the "Show link to dataset" is checked on the chart or map you're viewing
- Preview the dashboard and click on the link to view the dataset
> [DEV-11072] link to dataset/show all datasets should be filtered on multi dashboards

- packages/core/styles/base.scss
[DEV-10481](https://cdc-wcms.atlassian.net/browse/DEV-10481)
Polyfil needed for editor since TP5 is not present
WCMS ONLY
1. Open chart with legend label
2. Cofirm it is bolded
> Fix [DEV 10481] Legend Header Bug

- packages/map/src/data/initial-state.js
- packages/map/src/store/map.reducer.ts
> fix: use reverse by default

- .github/workflows/test-storybook.yml
- package.json
- packages/chart/src/_stories/ChartEditor.stories.tsx
- packages/core/components/_stories/MultiSelect.stories.tsx
- packages/core/helpers/testing.ts
- packages/dashboard/src/_stories/Dashboard.stories.tsx
- packages/data-bite/src/_stories/DataBite.Editor.stories.tsx
- packages/editor/src/_stories/Editor.stories.tsx
- packages/markup-include/src/_stories/MarkupInclude.Editor.stories.tsx
- packages/waffle-chart/src/_stories/WaffleChart.Editor.stories.tsx
- vitest.setup.ts
Adds editor testing for markup include
> Testing for markup include
